// This file is auto-generated by "@aria-ui/cli". Do not edit this file directly.

import { registerMenuSubmenuRootElement, type MenuSubmenuRootElement } from '@prosekit/web/menu';
import { createElement, type HTMLAttributes, type Ref } from 'preact';
import { forwardRef, type ForwardRefExoticComponent, type RefAttributes } from 'preact/compat';
import { useCallback, useRef } from 'preact/hooks';

/**
 * Props for the {@link MenuSubmenuRoot} Preact component.
 *
 * @public
 */
export interface MenuSubmenuRootProps {}

function MenuSubmenuRootComponent(props: MenuSubmenuRootProps, forwardedRef: Ref<MenuSubmenuRootElement>) {
  registerMenuSubmenuRootElement();

  const elementRef = useRef<MenuSubmenuRootElement>(null);

  const { ...restProps } = props;

  const mergedRef = useCallback(
    (element: MenuSubmenuRootElement | null) => {
      elementRef.current = element;
      if (typeof forwardedRef === 'function') {
        forwardedRef(element);
      } else if (forwardedRef) {
        forwardedRef.current = element;
      }
    },
    [forwardedRef],
  );

  return createElement('prosekit-menu-submenu-root', { ...restProps, ref: mergedRef, suppressHydrationWarning: true });
}

/**
 * A Preact component that renders an `prosekit-menu-submenu-root` custom element.
 *
 * @public
 */
export const MenuSubmenuRoot: ForwardRefExoticComponent<MenuSubmenuRootProps & HTMLAttributes<MenuSubmenuRootElement> & RefAttributes<MenuSubmenuRootElement>> = /* @__PURE__ */ forwardRef(MenuSubmenuRootComponent);
