/**
 * This file is auto-generated by the "@aria-ui/cli" tool. Do not edit this file directly.
 */

import { registerMenuPopupElement, type MenuPopupElement, type MenuPopupProps as MenuPopupElementProps } from '@prosekit/web/menu';
import { createElement, type HTMLAttributes, type Ref } from 'preact';
import { forwardRef, type ForwardRefExoticComponent, type RefAttributes } from 'preact/compat';
import { useCallback, useRef, useLayoutEffect } from 'preact/hooks';

/**
 * Props for the {@link MenuPopup} Preact component.
 *
 * @public
 */
export interface MenuPopupProps {
  /**
   * By default, the MenuPopup element will listen for keydown events.
   * You can pass a different element to listen for keydown events.
   *
   * @default null
   */
  eventTarget?: MenuPopupElementProps['eventTarget'];
}

function MenuPopupComponent(props: MenuPopupProps, forwardedRef: Ref<MenuPopupElement>) {
  registerMenuPopupElement();

  const elementRef = useRef<MenuPopupElement>(null);

  const { eventTarget: p0, ...restProps } = props;

  useLayoutEffect(() => {
    const element = elementRef.current as Record<string, unknown> | null;
    if (!element) return;
    Object.assign(element, { eventTarget: p0 });
  });

  const mergedRef = useCallback(
    (element: MenuPopupElement | null) => {
      elementRef.current = element;
      if (typeof forwardedRef === 'function') {
        forwardedRef(element);
      } else if (forwardedRef) {
        forwardedRef.current = element;
      }
    },
    [forwardedRef],
  );

  return createElement('prosekit-menu-popup', { ...restProps, ref: mergedRef, suppressHydrationWarning: true });
}

/**
 * A Preact component that renders an `prosekit-menu-popup` custom element.
 *
 * @public
 */
export const MenuPopup: ForwardRefExoticComponent<MenuPopupProps & HTMLAttributes<MenuPopupElement> & RefAttributes<MenuPopupElement>> = /* @__PURE__ */ forwardRef(MenuPopupComponent);
