// This file is auto-generated by "@aria-ui/cli". Do not edit this file directly.

import { registerColumnsPopoverPopupElement, type ColumnsPopoverPopupElement } from '@prosekit/web/columns-popover';
import { createElement, forwardRef, useCallback, useRef, type ForwardedRef, type ForwardRefExoticComponent, type HTMLAttributes, type RefAttributes } from 'react';

/** Props for the {@link ColumnsPopoverPopup} React component. */
export interface ColumnsPopoverPopupProps {}

function ColumnsPopoverPopupComponent(props: ColumnsPopoverPopupProps, forwardedRef: ForwardedRef<ColumnsPopoverPopupElement>) {
  registerColumnsPopoverPopupElement();

  const elementRef = useRef<ColumnsPopoverPopupElement>(null);

  const { ...restProps } = props;

  const mergedRef = useCallback(
    (element: ColumnsPopoverPopupElement | null) => {
      elementRef.current = element;
      if (typeof forwardedRef === 'function') {
        forwardedRef(element);
      } else if (forwardedRef) {
        forwardedRef.current = element;
      }
    },
    [forwardedRef],
  );

  return createElement('prosekit-columns-popover-popup', { ...restProps, ref: mergedRef, suppressHydrationWarning: true });
}

/** A React component that renders an `prosekit-columns-popover-popup` custom element. */
export const ColumnsPopoverPopup: ForwardRefExoticComponent<ColumnsPopoverPopupProps & HTMLAttributes<ColumnsPopoverPopupElement> & RefAttributes<ColumnsPopoverPopupElement>> = /* @__PURE__ */ forwardRef(ColumnsPopoverPopupComponent);
