/**
 * This file is auto-generated by the "@aria-ui/cli" tool. Do not edit this file directly.
 */

import {
  createElement,
  forwardRef,
  useCallback,
  useRef,
  type ForwardedRef,
  type ForwardRefExoticComponent,
  type HTMLAttributes,
  type RefAttributes,
  useLayoutEffect,
} from "react";
import {
  registerAutocompletePopoverElement,
  type AutocompletePopoverElement,
  type AutocompletePopoverProps as AutocompletePopoverElementProps,
  type AutocompletePopoverEvents,
} from "@prosekit/web/autocomplete";
import { useEditorContext } from "../../contexts/editor-context.ts";

/**
 * Props for the {@link AutocompletePopover} React component.
 *
 * @public
 */
export interface AutocompletePopoverProps extends HTMLAttributes<AutocompletePopoverElement> {
  /**
   * The ProseKit editor instance.
   *
   * @default null
   * @hidden
   */
  editor?: AutocompletePopoverElementProps["editor"];
  /**
   * The regular expression to match the query text to autocomplete.
   *
   * @default null
   */
  regex?: AutocompletePopoverElementProps["regex"];
  /**
   * The placement of the popover, relative to the text cursor.
   *
   * @default "bottom-start"
   */
  placement?: AutocompletePopoverElementProps["placement"];
  /**
   * The distance between the popover and the hovered block.
   *
   * @default 4
   */
  offset?: AutocompletePopoverElementProps["offset"];
  /** @default true */
  inline?: AutocompletePopoverElementProps["inline"];
  /** @default true */
  hoist?: AutocompletePopoverElementProps["hoist"];
  /** @default true */
  fitViewport?: AutocompletePopoverElementProps["fitViewport"];
  /** @default "The body element" */
  boundary?: AutocompletePopoverElementProps["boundary"];
  /** @default 8 */
  overflowPadding?: AutocompletePopoverElementProps["overflowPadding"];
  /**
   * The strategy to use for positioning
   *
   * @default "absolute"
   */
  strategy?: AutocompletePopoverElementProps["strategy"];
  /**
   * Options to activate auto-update listeners
   *
   * @see https://floating-ui.com/docs/autoUpdate
   *
   * @default true
   */
  autoUpdate?: AutocompletePopoverElementProps["autoUpdate"];
  /**
   * Whether to flip the `placement` in order to keep it in view when the
   * preferred placement(s) will overflow the clipping boundary. You can also
   * provide an array of placements to try sequentially if the preferred
   * `placement` does not fit.
   *
   * @default true
   */
  flip?: AutocompletePopoverElementProps["flip"];
  /**
   * Whether the floating element should shift to keep it in view.
   *
   * @default true
   */
  shift?: AutocompletePopoverElementProps["shift"];
  /**
   * Whether the floating element can overlap the reference element to keep it
   * in view.
   *
   * @default false
   */
  overlap?: AutocompletePopoverElementProps["overlap"];
  /**
   * Whether to constrain the floating element's width so that it matches the
   * reference element.
   *
   * @default false
   */
  sameWidth?: AutocompletePopoverElementProps["sameWidth"];
  /**
   * Whether to constrain the floating element's height so that it matches the
   * reference element.
   *
   * @default false
   */
  sameHeight?: AutocompletePopoverElementProps["sameHeight"];
  /**
   * Whether to hide the floating element when the reference element or the
   * floating element is fully clipped.
   *
   * @default false
   */
  hide?: AutocompletePopoverElementProps["hide"];
  /**
   * Describes the root boundary that the element will be checked for overflow relative to.
   * Please see https://floating-ui.com/docs/detectoverflow#rootboundary for more information.
   *
   * @default 'viewport'
   */
  rootBoundary?: AutocompletePopoverElementProps["rootBoundary"];
  /**
   * The element that will be used to check for overflow. Please see
   * https://floating-ui.com/docs/detectoverflow#elementcontext for more
   * information.
   *
   * @default 'floating'
   */
  elementContext?: AutocompletePopoverElementProps["elementContext"];
  /**
   * Whether to check the alternate elementContext's boundary. Please see
   * https://floating-ui.com/docs/detectoverflow#altboundary for more
   * information.
   *
   * @default false
   */
  altBoundary?: AutocompletePopoverElementProps["altBoundary"];
  /** Fired when the open state changes. */
  onOpenChange?: (event: AutocompletePopoverEvents["openChange"]) => void;
  /** Fired when the query changes. */
  onQueryChange?: (event: AutocompletePopoverEvents["queryChange"]) => void;
}

function AutocompletePopoverComponent(
  props: AutocompletePopoverProps,
  forwardedRef: ForwardedRef<AutocompletePopoverElement>,
) {
  registerAutocompletePopoverElement();

  const elementRef = useRef<AutocompletePopoverElement>(null);
  const handlersRef = useRef<Array<((event: Event) => void) | undefined>>([]);

  const p3Fallback = useEditorContext();

  const {
    altBoundary: p0,
    autoUpdate: p1,
    boundary: p2,
    editor: p3,
    elementContext: p4,
    fitViewport: p5,
    flip: p6,
    hide: p7,
    hoist: p8,
    inline: p9,
    offset: p10,
    overflowPadding: p11,
    overlap: p12,
    placement: p13,
    regex: p14,
    rootBoundary: p15,
    sameHeight: p16,
    sameWidth: p17,
    shift: p18,
    strategy: p19,
    onOpenChange: e0,
    onQueryChange: e1,
    ...restProps
  } = props;

  useLayoutEffect(() => {
    const element = elementRef.current as Record<string, unknown> | null;
    if (!element) return;
    Object.assign(element, {
      altBoundary: p0,
      autoUpdate: p1,
      boundary: p2,
      editor: p3 ?? p3Fallback,
      elementContext: p4,
      fitViewport: p5,
      flip: p6,
      hide: p7,
      hoist: p8,
      inline: p9,
      offset: p10,
      overflowPadding: p11,
      overlap: p12,
      placement: p13,
      regex: p14,
      rootBoundary: p15,
      sameHeight: p16,
      sameWidth: p17,
      shift: p18,
      strategy: p19,
    });
    handlersRef.current = [e0, e1] as Array<
      ((event: Event) => void) | undefined
    >;
  });

  useLayoutEffect(() => {
    const element = elementRef.current;
    if (!element) return;
    const ac = new AbortController();
    for (const [index, eventName] of ["openChange", "queryChange"].entries()) {
      element.addEventListener(
        eventName,
        (event: Event) => {
          handlersRef.current[index]?.(event);
        },
        { signal: ac.signal },
      );
    }
    return () => ac.abort();
  }, []);

  const mergedRef = useCallback(
    (element: AutocompletePopoverElement | null) => {
      elementRef.current = element;
      if (typeof forwardedRef === "function") {
        forwardedRef(element);
      } else if (forwardedRef) {
        forwardedRef.current = element;
      }
    },
    [forwardedRef],
  );

  return createElement("prosekit-autocomplete-popover", {
    ...restProps,
    ref: mergedRef,
    suppressHydrationWarning: true,
  });
}

/**
 * A React component that renders an `prosekit-autocomplete-popover` custom element.
 *
 * @public
 */
export const AutocompletePopover: ForwardRefExoticComponent<
  AutocompletePopoverProps & RefAttributes<AutocompletePopoverElement>
> = /* @__PURE__ */ forwardRef(AutocompletePopoverComponent);

export type { AutocompletePopoverEvents };
export {
  AutocompletePopoverOpenChangeEvent,
  AutocompletePopoverQueryChangeEvent,
} from "@prosekit/web/autocomplete";
