/**
 * This file is auto-generated by the "@aria-ui/cli" tool. Do not edit this file directly.
 */

import {
  registerAutocompleteItemElement,
  type AutocompleteItemElement,
  type AutocompleteItemProps as AutocompleteItemElementProps,
} from "@prosekit/web/autocomplete";
import {
  createElement,
  forwardRef,
  useCallback,
  useRef,
  type ForwardedRef,
  type ForwardRefExoticComponent,
  type HTMLAttributes,
  type RefAttributes,
  useLayoutEffect,
} from "react";

/**
 * Props for the {@link AutocompleteItem} React component.
 *
 * @public
 */
export interface AutocompleteItemProps extends HTMLAttributes<AutocompleteItemElement> {
  /**
   * The value of the item, which will be matched against the query.
   *
   * If not provided, the value is the item's text content.
   *
   * @default ""
   */
  value?: AutocompleteItemElementProps["value"];
  /**
   * Whether this option is disabled.
   *
   * @default false
   */
  disabled?: AutocompleteItemElementProps["disabled"];
}

function AutocompleteItemComponent(
  props: AutocompleteItemProps,
  forwardedRef: ForwardedRef<AutocompleteItemElement>,
) {
  registerAutocompleteItemElement();

  const elementRef = useRef<AutocompleteItemElement>(null);

  const { disabled: p0, value: p1, ...restProps } = props;

  useLayoutEffect(() => {
    const element = elementRef.current as Record<string, unknown> | null;
    if (!element) return;
    Object.assign(element, { disabled: p0, value: p1 });
  });

  const mergedRef = useCallback((element: AutocompleteItemElement | null) => {
    elementRef.current = element;
    if (typeof forwardedRef === "function") {
      forwardedRef(element);
    } else if (forwardedRef) {
      forwardedRef.current = element;
    }
  }, []);

  return createElement("prosekit-autocomplete-item", {
    ...restProps,
    ref: mergedRef,
    suppressHydrationWarning: true,
  });
}

/**
 * A React component that renders an `prosekit-autocomplete-item` custom element.
 *
 * @public
 */
export const AutocompleteItem: ForwardRefExoticComponent<
  AutocompleteItemProps & RefAttributes<AutocompleteItemElement>
> = /* @__PURE__ */ forwardRef(AutocompleteItemComponent);
