<script lang="ts">
  // This file is auto-generated by "@aria-ui/cli". Do not edit this file directly.
  import { registerAutocompleteRootElement } from '@prosekit/web/autocomplete'
  import type { AutocompleteRootElement } from '@prosekit/web/autocomplete'
  import { useEditorContext } from '../../contexts/editor-context.ts'
  registerAutocompleteRootElement()

  let { anchor: p0, editor: p1, filter: p2, followCursor: p3, queryBuilder: p4, regex: p5, onOpenChange: e0, onQueryChange: e1, onValueChange: e2, onValuesChange: e3, children = undefined, ...restProps } = $props()
  let element: AutocompleteRootElement | undefined
  const handlers: EventListener[] = []

  const p1Fallback = useEditorContext()

  $effect(() => {
    if (!element) return

    Object.assign(element, { anchor: p0, editor: p1 ?? p1Fallback, filter: p2, followCursor: p3, queryBuilder: p4, regex: p5 })

    handlers.length = 0
    handlers.push(e0)
    handlers.push(e1)
    handlers.push(e2)
    handlers.push(e3)
  })

  $effect(() => {
    if (!element) return

    const ac = new AbortController()
    for (const [index, eventName] of ["openChange", "queryChange", "valueChange", "valuesChange"].entries()) {
      element.addEventListener(eventName, (event) => handlers[index]?.(event), { signal: ac.signal })
    }
    return () => ac.abort()
  })
</script>

<prosekit-autocomplete-root {...restProps} bind:this={element}>{@render children?.()}</prosekit-autocomplete-root>
