/**
 * This file is auto-generated by the "@aria-ui/cli" tool. Do not edit this file directly.
 */

import type { AutocompleteItemElement, AutocompleteItemEvents, AutocompleteItemProps as AutocompleteItemElementProps } from '@prosekit/web/autocomplete';
import type { Component, Snippet } from 'svelte';
import type { HTMLAttributes } from 'svelte/elements';

import AutocompleteItemComponent from './autocomplete-item.gen.svelte';

/**
 * Props for the {@link AutocompleteItem} Svelte component.
 *
 * @public
 */
export interface AutocompleteItemProps {
  /**
   * The value of the item, which will be matched against the query.
   *
   * If not provided, the value is the item's text content.
   *
   * @default ""
   */
  value?: AutocompleteItemElementProps['value'];
  /**
   * Whether this option is disabled.
   *
   * @default false
   */
  disabled?: AutocompleteItemElementProps['disabled'];
  /** Emitted when the the item is selected. */
  onSelect?: (event: AutocompleteItemEvents['select']) => void;
  children?: Snippet;
}

/**
 * A Svelte component that renders an `prosekit-autocomplete-item` custom element.
 *
 * @public
 */
export const AutocompleteItem: Component<AutocompleteItemProps & HTMLAttributes<AutocompleteItemElement>> = AutocompleteItemComponent as Component<AutocompleteItemProps & HTMLAttributes<AutocompleteItemElement>>;
