/**
 * This file is auto-generated by the "@aria-ui/cli" tool. Do not edit this file directly.
 */

import AutocompleteListComponent from "./autocomplete-list.gen.svelte";
import {
  type AutocompleteListEvents,
  type AutocompleteListProps as AutocompleteListElementProps,
} from "@prosekit/web/autocomplete";
import type { Component, Snippet } from "svelte";

/**
 * Props for the {@link AutocompleteList} Svelte component.
 *
 * @public
 */
export interface AutocompleteListProps {
  /**
   * The ProseKit editor instance.
   *
   * @default null
   * @hidden
   */
  editor?: AutocompleteListElementProps["editor"];
  /**
   * The filter function to determine if an item should be shown in the
   * listbox.
   *
   * @default defaultItemFilter
   */
  filter?: AutocompleteListElementProps["filter"];
  /**
   * Emitted when the selected value changes. Only available when multiple is
   * false.
   */
  onValueChange?: (event: AutocompleteListEvents["valueChange"]) => void;
  /**
   * Emitted when the selected values change. Only available when multiple is
   * true.
   */
  onValuesChange?: (event: AutocompleteListEvents["valuesChange"]) => void;
  children?: Snippet;
  [key: string]: unknown;
}

/**
 * A Svelte component that renders an `prosekit-autocomplete-list` custom element.
 *
 * @public
 */
export const AutocompleteList: Component<AutocompleteListProps> =
  AutocompleteListComponent as unknown as Component<AutocompleteListProps>;

export type { AutocompleteListEvents };
export {
  ValueChangeEvent,
  ValuesChangeEvent,
} from "@prosekit/web/autocomplete";
