<!-- This file is auto-generated by the "@aria-ui/cli" tool. Do not edit this file directly. -->

<script lang="js">
  import { registerAutocompleteItemElement } from '@prosekit/web/autocomplete'
  registerAutocompleteItemElement()

  let { disabled: p0, value: p1, children = undefined, ...restProps } = $props()
  let element

  $effect(() => {
    if (!element) return

    Object.assign(element, { disabled: p0, value: p1 })
  })
</script>

<prosekit-autocomplete-item {...restProps} bind:this={element}>{@render children?.()}</prosekit-autocomplete-item>
