<!-- This file is auto-generated by the "@aria-ui/cli" tool. Do not edit this file directly. -->

<script lang="js">
  import { registerAutocompletePopoverElement } from '@prosekit/web/autocomplete'
  import { useEditorContext } from '../../contexts/editor-context.ts'
  registerAutocompletePopoverElement()

  let { altBoundary: p0, autoUpdate: p1, boundary: p2, editor: p3, elementContext: p4, fitViewport: p5, flip: p6, hide: p7, hoist: p8, inline: p9, offset: p10, overflowPadding: p11, overlap: p12, placement: p13, regex: p14, rootBoundary: p15, sameHeight: p16, sameWidth: p17, shift: p18, strategy: p19, onOpenChange: e0, onQueryChange: e1, children = undefined, ...restProps } = $props()
  let element
  const handlers = []

  const p3Fallback = useEditorContext()

  $effect(() => {
    if (!element) return

    Object.assign(element, { altBoundary: p0, autoUpdate: p1, boundary: p2, editor: p3 ?? p3Fallback, elementContext: p4, fitViewport: p5, flip: p6, hide: p7, hoist: p8, inline: p9, offset: p10, overflowPadding: p11, overlap: p12, placement: p13, regex: p14, rootBoundary: p15, sameHeight: p16, sameWidth: p17, shift: p18, strategy: p19 })

    handlers.length = 0
    handlers.push(e0)
    handlers.push(e1)
  })

  $effect(() => {
    if (!element) return

    const ac = new AbortController()
    for (const [index, eventName] of ["openChange", "queryChange"].entries()) {
      element.addEventListener(eventName, (event) => handlers[index]?.(event), { signal: ac.signal })
    }
    return () => ac.abort()
  })
</script>

<prosekit-autocomplete-popover {...restProps} bind:this={element}>{@render children?.()}</prosekit-autocomplete-popover>
