// This file is auto-generated by "@aria-ui/cli". Do not edit this file directly.

import { registerInlinePopoverPopupElement } from '@prosekit/web/inline-popover';
import { defineComponent, h, type DefineSetupFnComponent, type HTMLAttributes } from 'vue';

/** Props for the {@link InlinePopoverPopup} Vue component. */
export interface InlinePopoverPopupProps {}

/** A Vue component that renders an `prosekit-inline-popover-popup` custom element. */
export const InlinePopoverPopup: DefineSetupFnComponent<InlinePopoverPopupProps & HTMLAttributes> = /* @__PURE__ */ defineComponent<InlinePopoverPopupProps & HTMLAttributes>(
  (props, { slots }) => {
    registerInlinePopoverPopupElement();

    return () => {
      return h('prosekit-inline-popover-popup', props, slots.default?.());
    };
  },
  { props: [] },
);
