// This file is auto-generated by "@aria-ui/cli". Do not edit this file directly.

import { registerInlinePopoverRootElement, type InlinePopoverRootEvents, type InlinePopoverRootProps as InlinePopoverRootElementProps } from '@prosekit/web/inline-popover';
import { defineComponent, h, type DefineSetupFnComponent, type HTMLAttributes, shallowRef, computed, watchEffect } from 'vue';

import { useEditorContext } from '../../injection/editor-context.ts';

/** Props for the {@link InlinePopoverRoot} Vue component. */
export interface InlinePopoverRootProps {
  /**
   * The ProseKit editor instance.
   *
   * @default null
   * @hidden
   */
  editor?: InlinePopoverRootElementProps['editor'];
  /**
   * Whether the popover is open by default when some inline content is
   * selected.
   *
   * @default true
   */
  defaultOpen?: InlinePopoverRootElementProps['defaultOpen'];
  /**
   * Whether the inline popover should be dismissed when the editor receives an
   * Escape key press.
   *
   * @default true
   */
  dismissOnEscape?: InlinePopoverRootElementProps['dismissOnEscape'];
  /**
   * Whether the overlay is currently open.
   * @default null
   */
  open?: InlinePopoverRootElementProps['open'];
  /**
   * Whether the component should ignore user interaction.
   * @default false
   */
  disabled?: InlinePopoverRootElementProps['disabled'];
  /** Emitted when the open state of the popover changes. */
  onOpenChange?: (event: InlinePopoverRootEvents['openChange']) => void;
}

/** A Vue component that renders an `prosekit-inline-popover-root` custom element. */
export const InlinePopoverRoot: DefineSetupFnComponent<InlinePopoverRootProps & HTMLAttributes> = /* @__PURE__ */ defineComponent<InlinePopoverRootProps & HTMLAttributes>(
  (props, { slots }) => {
    registerInlinePopoverRootElement();

    const elementRef = shallowRef<HTMLElement | null>(null);

    const p3Fallback = useEditorContext();

    const splittedProps = computed(() => {
      const { defaultOpen: p0, disabled: p1, dismissOnEscape: p2, editor: p3, open: p4, onOpenChange: e0, ...restProps } = props;
      return [[p0, p1, p2, p3, p4, e0], restProps] as const;
    });

    const handlers: Array<((event: any) => void) | undefined> = [];

    watchEffect(() => {
      const element = elementRef.value;
      if (!element) return;

      const [p0, p1, p2, p3, p4, e0] = splittedProps.value[0];

      Object.assign(element, { defaultOpen: p0, disabled: p1, dismissOnEscape: p2, editor: p3 ?? p3Fallback, open: p4 });

      handlers.length = 0;
      handlers.push(e0);
    });

    watchEffect(() => {
      const element = elementRef.value;
      if (!element) return;

      const ac = new AbortController();
      for (const [index, eventName] of ['openChange'].entries()) {
        element.addEventListener(
          eventName,
          (event: Event) => {
            handlers[index]?.(event);
          },
          { signal: ac.signal },
        );
      }
      return () => ac.abort();
    });

    return () => {
      const restProps = splittedProps.value[1];
      return h('prosekit-inline-popover-root', { ...restProps, ref: elementRef }, slots.default?.());
    };
  },
  { props: ['defaultOpen', 'disabled', 'dismissOnEscape', 'editor', 'open', 'onOpenChange'] },
);
