// This file is auto-generated by "@aria-ui/cli". Do not edit this file directly.

import { registerBlockHandleRootElement, type BlockHandleRootEvents, type BlockHandleRootProps as BlockHandleRootElementProps } from '@prosekit/web/block-handle';
import { defineComponent, h, type DefineSetupFnComponent, type HTMLAttributes, shallowRef, computed, watchEffect } from 'vue';

import { useEditorContext } from '../../injection/editor-context.ts';

/**
 * Props for the {@link BlockHandleRoot} Vue component.
 *
 * @public
 */
export interface BlockHandleRootProps {
  /**
   * The ProseKit editor instance.
   *
   * @default null
   * @hidden
   */
  editor?: BlockHandleRootElementProps['editor'];
  /** Fired when the hovered block changes. */
  onStateChange?: (event: BlockHandleRootEvents['stateChange']) => void;
}

/**
 * A Vue component that renders an `prosekit-block-handle-root` custom element.
 *
 * @public
 */
export const BlockHandleRoot: DefineSetupFnComponent<BlockHandleRootProps & HTMLAttributes> = /* @__PURE__ */ defineComponent<BlockHandleRootProps & HTMLAttributes>(
  (props, { slots }) => {
    registerBlockHandleRootElement();

    const elementRef = shallowRef<HTMLElement | null>(null);

    const p0Fallback = useEditorContext();

    const splittedProps = computed(() => {
      const { editor: p0, onStateChange: e0, ...restProps } = props;
      return [[p0, e0], restProps] as const;
    });

    const handlers: Array<((event: any) => void) | undefined> = [];

    watchEffect(() => {
      const element = elementRef.value;
      if (!element) return;

      const [p0, e0] = splittedProps.value[0];

      Object.assign(element, { editor: p0 ?? p0Fallback });

      handlers.length = 0;
      handlers.push(e0);
    });

    watchEffect(() => {
      const element = elementRef.value;
      if (!element) return;

      const ac = new AbortController();
      for (const [index, eventName] of ['stateChange'].entries()) {
        element.addEventListener(
          eventName,
          (event: Event) => {
            handlers[index]?.(event);
          },
          { signal: ac.signal },
        );
      }
      return () => ac.abort();
    });

    return () => {
      const restProps = splittedProps.value[1];
      return h('prosekit-block-handle-root', { ...restProps, ref: elementRef }, slots.default?.());
    };
  },
  { props: ['editor', 'onStateChange'] },
);
