// This file is auto-generated by "@aria-ui/cli". Do not edit this file directly.

import { registerBlockHandleDraggableElement, type BlockHandleDraggableProps as BlockHandleDraggableElementProps } from '@prosekit/web/block-handle';
import { defineComponent, h, type DefineSetupFnComponent, type HTMLAttributes, shallowRef, computed, watchEffect } from 'vue';

import { useEditorContext } from '../../injection/editor-context.ts';

/**
 * Props for the {@link BlockHandleDraggable} Vue component.
 *
 * @public
 */
export interface BlockHandleDraggableProps {
  /**
   * The ProseKit editor instance.
   *
   * @default null
   * @hidden
   */
  editor?: BlockHandleDraggableElementProps['editor'];
}

/**
 * A Vue component that renders an `prosekit-block-handle-draggable` custom element.
 *
 * @public
 */
export const BlockHandleDraggable: DefineSetupFnComponent<BlockHandleDraggableProps & HTMLAttributes> = /* @__PURE__ */ defineComponent<BlockHandleDraggableProps & HTMLAttributes>(
  (props, { slots }) => {
    registerBlockHandleDraggableElement();

    const elementRef = shallowRef<HTMLElement | null>(null);

    const p0Fallback = useEditorContext();

    const splittedProps = computed(() => {
      const { editor: p0, ...restProps } = props;
      return [[p0], restProps] as const;
    });

    watchEffect(() => {
      const element = elementRef.value;
      if (!element) return;

      const [p0] = splittedProps.value[0];

      Object.assign(element, { editor: p0 ?? p0Fallback });
    });

    return () => {
      const restProps = splittedProps.value[1];
      return h('prosekit-block-handle-draggable', { ...restProps, ref: elementRef }, slots.default?.());
    };
  },
  { props: ['editor'] },
);
