# https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference
version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    cooldown:
      default-days: 1
      exclude:
        - "@ocavue/eslint-config"
        - "@ocavue/tsconfig"
        - "@ocavue/utils"
    groups:
      non-major:
        update-types:
          - minor
          - patch
    commit-message:
      prefix: "chore"
    open-pull-requests-limit: 10

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    cooldown:
      default-days: 1
    groups:
      non-major:
        update-types:
          - minor
          - patch
    commit-message:
      prefix: "chore"
