name: Setup
description: Setup the environment

inputs:
  node-version:
    description: The version of node.js
    required: false
    default: '18'

runs:
  using: composite
  steps:
    - name: Install pnpm
      run: |
        corepack enable
        pnpm --version
      shell: bash

    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: pnpm
        registry-url: 'https://registry.npmjs.org'

    - name: Install
      run: |
        node --version
        pnpm --version
        pnpm install
      shell: bash
