name: Setup
description: Setup the environment

inputs:
  node-version:
    description: The version of node.js
    required: false
    default: "24"

runs:
  using: composite
  steps:
    - name: Set environment variables
      shell: bash
      run: |
        echo "DO_NOT_TRACK=1" >> "${GITHUB_ENV}"

    - name: Install pnpm
      uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0

    - name: Setup node
      uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
      with:
        node-version: ${{ inputs.node-version }}
        cache: "pnpm"

    - name: Install
      run: pnpm install
      shell: bash
