name: Setup
description: Setup the environment

inputs:
  node-version:
    description: The version of node.js
    required: false
    default: "20"

runs:
  using: composite
  steps:
    - name: Set environment variables
      shell: bash
      run: |
        echo "FORCE_COLOR=1" >> "${GITHUB_ENV}"
        echo "DO_NOT_TRACK=1" >> "${GITHUB_ENV}"

    - name: Install pnpm
      uses: pnpm/action-setup@v4

    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: pnpm
        registry-url: "https://registry.npmjs.org"

    # Update npm to use OIDC publishing
    - name: Update npm
      run: npm install -g npm@latest
      shell: bash

    - name: Install
      run: pnpm install
      shell: bash
