name: Setup
description: Setup the environment

inputs:
  node-version:
    description: The version of node.js
    required: false
    default: "24"

runs:
  using: composite
  steps:
    - name: Set environment variables
      shell: bash
      run: |
        echo "DO_NOT_TRACK=1" >> "${GITHUB_ENV}"
        echo "NO_COLOR=1" >> "${GITHUB_ENV}"

    - name: Install pnpm
      uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4.3.0

    - name: Setup node
      uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
      with:
        node-version: ${{ inputs.node-version }}
        cache: "pnpm"

    - name: Install
      run: pnpm install
      shell: bash
