name: Setup
description: Setup the environment

inputs:
  node-version:
    description: The version of node.js
    required: false
    default: "24"

runs:
  using: composite
  steps:
    - name: Set environment variables
      shell: bash
      run: |
        echo "DO_NOT_TRACK=1" >> "${GITHUB_ENV}"

    - name: Install pnpm
      uses: pnpm/action-setup@v4

    - name: Setup node
      uses: actions/setup-node@v5
      with:
        node-version: ${{ inputs.node-version }}

    - name: Install
      run: pnpm install
      shell: bash
