name: Setup
description: Setup the environment

inputs:
  node-version:
    description: The version of node.js
    required: false
    default: "24"

runs:
  using: composite
  steps:
    - name: Set environment variables
      shell: bash
      run: |
        echo "DO_NOT_TRACK=1" >> "${GITHUB_ENV}"
        echo "NO_COLOR=1" >> "${GITHUB_ENV}"

    - name: Install pnpm
      uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9

    - name: Setup node
      uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
      with:
        node-version: ${{ inputs.node-version }}
        cache: "pnpm"

    - name: Install
      run: pnpm install
      shell: bash
