packages:
  - website
  - registry
  - examples/*
  - packages/*

ignoreWorkspaceRootCheck: true

ignoredBuiltDependencies:
  - msw
  - sharp
  - unrs-resolver

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - '@ocavue/*'
  - '@prosemirror-adapter/*'
  - prosemirror-*
  - starlight-theme-nova

overrides: {}

patchedDependencies:
  y-prosemirror: patches/y-prosemirror.patch

strictDepBuilds: true
