packages:
  - website
  - registry
  - packages/*

catalog:
  "@types/node": "^24.10.13"
  "@vitest/browser-playwright": ^4.0.18
  "@vitest/coverage-v8": ^4.0.18
  "@vitest/ui": ^4.0.18
  vitest: ^4.0.18
  tsdown: ^0.20.3
  typescript: ~5.9.3

ignoreWorkspaceRootCheck: true

ignoredBuiltDependencies:
  - dprint
  - esbuild
  - sharp
  - workerd

minimumReleaseAge: 1440 # 24 hours

minimumReleaseAgeExclude:
  - "@ocavue/*"
  - "@prosemirror-adapter/*"
  - prosemirror-*

overrides: {}

patchedDependencies:
  y-prosemirror: patches/y-prosemirror.patch

strictDepBuilds: true

strictPeerDependencies: true

trustPolicy: no-downgrade

trustPolicyIgnoreAfter: 10080 # 7 days
