packages:
  - website
  - registry
  - examples/*
  - packages/*

ignoreWorkspaceRootCheck: true

ignoredBuiltDependencies:
  - dprint
  - esbuild
  - sharp
  - unrs-resolver
  - workerd

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - "@ocavue/*"
  - "@prosemirror-adapter/*"
  - prosemirror-*
  - starlight-theme-nova
  - "@astrojs/*"
  - "astro"

overrides: {
  "@preact/preset-vite": "^2.10.3",
  "@sveltejs/vite-plugin-svelte": "^6.2.4",
  "vite": "^7.3.1",
  "@astrojs/preact": "^5.0.0-beta.2",
  "@astrojs/react": "^5.0.0-beta.3",
  "@astrojs/solid-js": "^6.0.0-beta.2",
  "@astrojs/starlight": "^0.37.4",
  "@astrojs/svelte": "^8.0.0-beta.2",
  "@astrojs/vue": "^6.0.0-beta.0",
  "@astrojs/sitemap": "^3.6.1-beta.2",
  "@astrojs/markdown-remark": "^7.0.0-beta.2",
  "@astrojs/mdx": "^5.0.0-beta.2",
  "astro": "^6.0.0-beta.5",
}

patchedDependencies:
  y-prosemirror: patches/y-prosemirror.patch

strictDepBuilds: true
