packages:
  - website
  - registry
  - examples/*
  - packages/*

catalog:
  typescript: "~5.9.3"
  tsdown: "^0.20.1"
  vitest: "^4.0.18"
  "@vitest/coverage-v8": "^4.0.18"
  "@vitest/ui": "^4.0.18"
  "@vitest/browser-playwright": "^4.0.18"

ignoreWorkspaceRootCheck: true

ignoredBuiltDependencies:
  - dprint
  - esbuild
  - sharp
  - unrs-resolver
  - workerd

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - '@ocavue/*'
  - '@prosemirror-adapter/*'
  - diffable-html-snapshot
  - prosemirror-*
  - starlight-theme-nova

overrides: {}

patchedDependencies:
  y-prosemirror: patches/y-prosemirror.patch

strictDepBuilds: true
