packages:
  - website
  - registry
  - examples/*
  - packages/*

catalog:
  typescript: "6.0.0-beta"
  tsdown: "^0.20.0"
  vitest: "^4.0.18"
  "@vitest/coverage-v8": "^4.0.18"
  "@vitest/ui": "^4.0.18"
  "@vitest/browser-playwright": "^4.0.18"

ignoreWorkspaceRootCheck: true

ignoredBuiltDependencies:
  - dprint
  - esbuild
  - sharp
  - unrs-resolver
  - workerd

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - typescript
  - "@ocavue/*"
  - "@prosemirror-adapter/*"
  - prosemirror-*

overrides: {}

patchedDependencies:
  y-prosemirror: patches/y-prosemirror.patch

strictDepBuilds: true
