packages:
  - website
  - registry
  - packages/*

allowedDeprecatedVersions:
  glob: "10"

catalog:
  "@types/node": "^24.10.13"
  "@vitest/browser-playwright": "^4.0.18"
  "@vitest/coverage-v8": "^4.0.18"
  "@vitest/ui": "^4.0.18"
  vitest: "^4.0.18"
  tsdown: "^0.21.0-beta.1"
  typescript: "~5.9.3"

ignoreWorkspaceRootCheck: true

ignoredBuiltDependencies:
  - dprint
  - esbuild
  - sharp
  - workerd

minimumReleaseAge: 600 # 10 hours

minimumReleaseAgeExclude:
  - "@ocavue/*"
  - "@prosemirror-adapter/*"
  - "prosemirror-*"
  - "@astrojs/*"
  - "astro"

overrides: {
  "@sveltejs/vite-plugin-svelte": "^6.2.4",
  "vite": "^7.3.1",
  "@astrojs/check": "^0.9.7-beta.1",
  "@astrojs/preact": "^5.0.0-beta.4",
  "@astrojs/react": "^5.0.0-beta.3",
  "@astrojs/solid-js": "^6.0.0-beta.2",
  "@astrojs/starlight": "github:withastro/starlight#d252f627506a44bab0c9f1296a27bbfac1f2c048&path:packages/starlight",
  "@astrojs/svelte": "^8.0.0-beta.3",
  "@astrojs/vue": "^6.0.0-beta.1",
  "astro": "^6.0.0-beta.17",
}

patchedDependencies:
  y-prosemirror: patches/y-prosemirror.patch

strictDepBuilds: true

strictPeerDependencies: true

trustPolicy: no-downgrade

trustPolicyIgnoreAfter: 10080 # 7 days
