packages:
  - website
  - registry
  - packages/*

catalog:
  "@types/node": "^24.10.13"
  "@vitest/browser-playwright": "^4.1.0-beta.4"
  "@vitest/coverage-v8": "^4.1.0-beta.4"
  "@vitest/ui": "^4.1.0-beta.4"
  vitest: "^4.1.0-beta.4"
  tsdown: "^0.20.3"
  typescript: "~5.9.3"

allowedDeprecatedVersions:
  glob: "10"

ignoreWorkspaceRootCheck: true

ignoredBuiltDependencies:
  - dprint
  - esbuild
  - sharp
  - workerd

minimumReleaseAge: 600 # 10 hours

minimumReleaseAgeExclude:
  - "@ocavue/*"
  - "@prosemirror-adapter/*"
  - "prosemirror-*"

overrides: {}

patchedDependencies:
  y-prosemirror: patches/y-prosemirror.patch

strictDepBuilds: true

strictPeerDependencies: true

trustPolicy: no-downgrade

trustPolicyIgnoreAfter: 10080 # 7 days
