ignoreWorkspaceRootCheck: true
packages:
  - website
  - registry
  - examples/*
  - packages/*
minimumReleaseAge: 1440 # 24 hours
minimumReleaseAgeExclude:
  - "@prosemirror-adapter/*"
  - "@ocavue/*"
  - "prosemirror-*"
