packages:
  - website
  - registry
  - packages/*
  # TODO: remove me 
  - aria-ui-packages/*
  - aria-ui-wensite

allowedDeprecatedVersions:
  glob: "10"

catalog:
  "@types/node": "^24.10.13"
  "@vitest/browser-playwright": "^4.1.0"
  "@vitest/coverage-v8": "^4.1.0"
  "@vitest/ui": "^4.1.0"
  vitest: "^4.1.0"
  tsdown: "^0.21.2"
  "@tsdown/css": "^0.21.2"
  typescript: "~5.9.3"

ignoreWorkspaceRootCheck: true

ignoredBuiltDependencies:
  - "@parcel/watcher"
  - dprint
  - esbuild
  - sharp
  - workerd

minimumReleaseAge: 600 # 10 hours

minimumReleaseAgeExclude:
  - "@ocavue/*"
  - "prosemirror-*"
  - "astrobook"
  - "@astrobook/*"
  - "vite-plugin-solid"

overrides:
  '@aria-ui/collection': https://pkg.pr.new/ocavue/aria-ui/@aria-ui/collection@b9d0540
  '@aria-ui/combobox': https://pkg.pr.new/ocavue/aria-ui/@aria-ui/combobox@b9d0540
  '@aria-ui/core': https://pkg.pr.new/ocavue/aria-ui/@aria-ui/core@b9d0540
  '@aria-ui/listbox': https://pkg.pr.new/ocavue/aria-ui/@aria-ui/listbox@b9d0540
  '@aria-ui/menu': https://pkg.pr.new/ocavue/aria-ui/@aria-ui/menu@b9d0540
  '@aria-ui/overlay': https://pkg.pr.new/ocavue/aria-ui/@aria-ui/overlay@b9d0540
  '@aria-ui/popover': https://pkg.pr.new/ocavue/aria-ui/@aria-ui/popover@b9d0540
  '@aria-ui/presence': https://pkg.pr.new/ocavue/aria-ui/@aria-ui/presence@b9d0540
  '@aria-ui/select': https://pkg.pr.new/ocavue/aria-ui/@aria-ui/select@b9d0540
  '@aria-ui/tooltip': https://pkg.pr.new/ocavue/aria-ui/@aria-ui/tooltip@b9d0540


patchedDependencies:
  y-prosemirror: patches/y-prosemirror.patch

strictDepBuilds: true

strictPeerDependencies: true

trustPolicy: no-downgrade

trustPolicyIgnoreAfter: 10080 # 7 days
