packages:
  - website
  - registry
  - packages/*

allowedDeprecatedVersions:
  glob: "10.5.0"

catalog:
  "@tsdown/css": "^0.22.1"
  "@types/node": "^24.12.2"
  "@vitest/browser-playwright": "^4.1.8"
  "@vitest/coverage-v8": "^4.1.8"
  "@vitest/ui": "^4.1.8"
  tsdown: "^0.22.1"
  typescript: "~6.0.3"
  vitest: "^4.1.8"

dedupePeers: true

ignoreWorkspaceRootCheck: true

allowBuilds:
  "@parcel/watcher": false
  dprint: false
  esbuild: false
  sharp: false
  workerd: false

patchedDependencies:
  y-prosemirror: patches/y-prosemirror.patch

strictDepBuilds: true

strictPeerDependencies: true

trustPolicy: no-downgrade

trustPolicyIgnoreAfter: 10080 # 7 days

trustLockfile: true

minimumReleaseAgeExclude:
  - 'starlight-theme-nova'
  - '@aria-ui/*'

peerDependencyRules:
  allowedVersions:
    # TODO: remove this after https://github.com/expressive-code/expressive-code/issues/451 is resolved
    astro: "7"
