export { defineItalic, type ItalicExtension } from './italic'
export { defineItalicCommands, type ItalicCommandsExtension } from './italic-commands'
export { defineItalicInputRule } from './italic-input-rule'
export { defineItalicKeymap } from './italic-keymap'
export { defineItalicSpec, type ItalicSpecExtension } from './italic-spec'
