// This file is generated from gen-website-pages.ts

export const loaders = {
  'minimal': () => import('./minimal/editor.svelte'),
  'bold': () => import('./bold/editor.svelte'),
  'change-tracking': () => import('./change-tracking/editor.svelte'),
  'code': () => import('./code/editor.svelte'),
  'code-block': () => import('./code-block/editor.svelte'),
  'code-block-themes': () => import('./code-block-themes/editor.svelte'),
  'drop-cursor': () => import('./drop-cursor/editor.svelte'),
  'emoji-rules': () => import('./emoji-rules/editor.svelte'),
  'full': () => import('./full/editor.svelte'),
  'heading': () => import('./heading/editor.svelte'),
  'italic': () => import('./italic/editor.svelte'),
  'keymap': () => import('./keymap/editor.svelte'),
  'link-mark-view': () => import('./link-mark-view/editor.svelte'),
  'list': () => import('./list/editor.svelte'),
  'readonly': () => import('./readonly/editor.svelte'),
  'save-json': () => import('./save-json/editor.svelte'),
  'slash-menu': () => import('./slash-menu/editor.svelte'),
  'table': () => import('./table/editor.svelte'),
  'text-align': () => import('./text-align/editor.svelte'),
  'toolbar': () => import('./toolbar/editor.svelte'),
  'typography': () => import('./typography/editor.svelte'),
  'word-counter': () => import('./word-counter/editor.svelte'),
}
