// This file is generated from gen-website-pages.ts
import { lazy } from 'preact/compat'

export const loaders = {
  'minimal': lazy(() => import('./minimal/editor')),
  'block-handle': lazy(() => import('./block-handle/editor')),
  'blockquote': lazy(() => import('./blockquote/editor')),
  'bold': lazy(() => import('./bold/editor')),
  'change-tracking': lazy(() => import('./change-tracking/editor')),
  'code': lazy(() => import('./code/editor')),
  'code-block': lazy(() => import('./code-block/editor')),
  'drop-cursor': lazy(() => import('./drop-cursor/editor')),
  'emoji-rules': lazy(() => import('./emoji-rules/editor')),
  'hard-break': lazy(() => import('./hard-break/editor')),
  'heading': lazy(() => import('./heading/editor')),
  'horizontal-rule': lazy(() => import('./horizontal-rule/editor')),
  'image-view': lazy(() => import('./image-view/editor')),
  'italic': lazy(() => import('./italic/editor')),
  'keymap': lazy(() => import('./keymap/editor')),
  'link-mark-view': lazy(() => import('./link-mark-view/editor')),
  'list': lazy(() => import('./list/editor')),
  'mark-rule': lazy(() => import('./mark-rule/editor')),
  'placeholder': lazy(() => import('./placeholder/editor')),
  'readonly': lazy(() => import('./readonly/editor')),
  'slash-menu': lazy(() => import('./slash-menu/editor')),
  'strike': lazy(() => import('./strike/editor')),
  'table': lazy(() => import('./table/editor')),
  'text-align': lazy(() => import('./text-align/editor')),
  'typography': lazy(() => import('./typography/editor')),
  'underline': lazy(() => import('./underline/editor')),
  'word-counter': lazy(() => import('./word-counter/editor')),
}
