<!-- This file is auto-generated by the "@aria-ui/cli" tool. Do not edit this file directly. -->

<script lang="ts">
  import { registerTableHandleColumnMenuRootElement } from '@prosekit/web/table-handle'
  import type { TableHandleColumnMenuRootElement } from '@prosekit/web/table-handle'
  registerTableHandleColumnMenuRootElement()

  let { defaultOpen: p0, disabled: p1, open: p2, children = undefined, ...restProps } = $props()
  let element: TableHandleColumnMenuRootElement | undefined

  $effect(() => {
    if (!element) return

    Object.assign(element, { defaultOpen: p0, disabled: p1, open: p2 })
  })
</script>

<prosekit-table-handle-column-menu-root {...restProps} bind:this={element}>{@render children?.()}</prosekit-table-handle-column-menu-root>
