/**
 * This file is auto-generated by the "@aria-ui/cli" tool. Do not edit this file directly.
 */

import type { Component, Snippet } from 'svelte';

import TableHandleRowPopupComponent from './table-handle-row-popup.gen.svelte';

/**
 * Props for the {@link TableHandleRowPopup} Svelte component.
 *
 * @public
 */
export interface TableHandleRowPopupProps {
  children?: Snippet;
  [key: string]: unknown;
}

/**
 * A Svelte component that renders an `prosekit-table-handle-row-popup` custom element.
 *
 * @public
 */
export const TableHandleRowPopup: Component<TableHandleRowPopupProps> = TableHandleRowPopupComponent as unknown as Component<TableHandleRowPopupProps>;
