// This file is auto-generated by "@aria-ui/cli". Do not edit this file directly.

import type { TableHandleRowPopupElement } from '@prosekit/web/table-handle';
import type { Component, Snippet } from 'svelte';
import type { HTMLAttributes } from 'svelte/elements';

import TableHandleRowPopupComponent from './table-handle-row-popup.gen.svelte';

/** Props for the {@link TableHandleRowPopup} Svelte component. */
export interface TableHandleRowPopupProps {
  children?: Snippet;
}

/** A Svelte component that renders an `prosekit-table-handle-row-popup` custom element. */
export const TableHandleRowPopup: Component<TableHandleRowPopupProps & HTMLAttributes<TableHandleRowPopupElement>> = TableHandleRowPopupComponent as Component<TableHandleRowPopupProps & HTMLAttributes<TableHandleRowPopupElement>>;
