/**
 * This file is auto-generated by the "@aria-ui/cli" tool. Do not edit this file directly.
 */

import TableHandleColumnTriggerComponent from "./table-handle-column-trigger.gen.svelte";
import { type TableHandleColumnTriggerProps as TableHandleColumnTriggerElementProps } from "@prosekit/web/table-handle";
import type { Component, Snippet } from "svelte";

/**
 * Props for the {@link TableHandleColumnTrigger} Svelte component.
 *
 * @public
 */
export interface TableHandleColumnTriggerProps {
  /**
   * @default null
   * @hidden
   */
  editor?: TableHandleColumnTriggerElementProps["editor"];
  children?: Snippet;
  [key: string]: unknown;
}

/**
 * A Svelte component that renders an `prosekit-table-handle-column-trigger` custom element.
 *
 * @public
 */
export const TableHandleColumnTrigger: Component<TableHandleColumnTriggerProps> =
  TableHandleColumnTriggerComponent as unknown as Component<TableHandleColumnTriggerProps>;
