// This file is auto-generated by "@aria-ui/cli". Do not edit this file directly.

import type { TableHandleRowMenuTriggerElement, TableHandleRowMenuTriggerProps as TableHandleRowMenuTriggerElementProps } from '@prosekit/web/table-handle';
import type { Component, Snippet } from 'svelte';
import type { HTMLAttributes } from 'svelte/elements';

import TableHandleRowMenuTriggerComponent from './table-handle-row-menu-trigger.gen.svelte';

/** Props for the {@link TableHandleRowMenuTrigger} Svelte component. */
export interface TableHandleRowMenuTriggerProps {
  /**
   * @default null
   * @hidden
   */
  editor?: TableHandleRowMenuTriggerElementProps['editor'];
  children?: Snippet;
}

/** A Svelte component that renders an `prosekit-table-handle-row-menu-trigger` custom element. */
export const TableHandleRowMenuTrigger: Component<TableHandleRowMenuTriggerProps & HTMLAttributes<TableHandleRowMenuTriggerElement>> = TableHandleRowMenuTriggerComponent as Component<TableHandleRowMenuTriggerProps & HTMLAttributes<TableHandleRowMenuTriggerElement>>;
