<!-- This file is auto-generated by the "@aria-ui/cli" tool. Do not edit this file directly. -->

<script lang="js">
  import { registerTableHandleDropIndicatorElement } from '@prosekit/web/table-handle'
  import { useEditorContext } from '../../contexts/editor-context.ts'
  registerTableHandleDropIndicatorElement()

  let { editor: p0, children = undefined, ...restProps } = $props()
  let element

  const p0Fallback = useEditorContext()

  $effect.pre(() => {
    if (!element) return

    Object.assign(element, { editor: p0 ?? p0Fallback })
  })
</script>

<prosekit-table-handle-drop-indicator {...restProps} bind:this={element}>{@render children?.()}</prosekit-table-handle-drop-indicator>
