/**
 * This file is auto-generated by the "@aria-ui/cli" tool. Do not edit this file directly.
 */

import TableHandleRowRootComponent from "./table-handle-row-root.gen.svelte";
import { type TableHandleRowRootProps as TableHandleRowRootElementProps } from "@prosekit/web/table-handle";
import type { Component, Snippet } from "svelte";

/**
 * Props for the {@link TableHandleRowRoot} Svelte component.
 *
 * @public
 */
export interface TableHandleRowRootProps {
  /**
   * The ProseKit editor instance.
   *
   * @default null
   * @hidden
   */
  editor?: TableHandleRowRootElementProps["editor"];
  /**
   * The placement of the popover, relative to the hovered table cell.
   *
   * @default "left"
   */
  placement?: TableHandleRowRootElementProps["placement"];
  /**
   * Whether to use the browser [Popover API](https://developer.mozilla.org/en-US/docs/Web/API/Popover_API)
   * to place the floating element on top of other page content.
   *
   * @default false
   */
  hoist?: TableHandleRowRootElementProps["hoist"];
  /**
   * @default false
   * @hidden
   */
  flip?: TableHandleRowRootElementProps["flip"];
  /**
   * @default false
   * @hidden
   */
  shift?: TableHandleRowRootElementProps["shift"];
  /**
   * @default true
   * @hidden
   */
  hide?: TableHandleRowRootElementProps["hide"];
  /**
   * The strategy to use for positioning
   *
   * @default "absolute"
   */
  strategy?: TableHandleRowRootElementProps["strategy"];
  /**
   * Options to activate auto-update listeners
   *
   * @see https://floating-ui.com/docs/autoUpdate
   *
   * @default true
   */
  autoUpdate?: TableHandleRowRootElementProps["autoUpdate"];
  /**
   * The distance between the reference and floating element.
   *
   * @default 6
   */
  offset?: TableHandleRowRootElementProps["offset"];
  /**
   * Whether the floating element can overlap the reference element to keep it
   * in view.
   *
   * @default false
   */
  overlap?: TableHandleRowRootElementProps["overlap"];
  /**
   * Whether to constrain the floating element's width and height to not exceed
   * the viewport.
   *
   * @default false
   */
  fitViewport?: TableHandleRowRootElementProps["fitViewport"];
  /**
   * Whether to constrain the floating element's width so that it matches the
   * reference element.
   *
   * @default false
   */
  sameWidth?: TableHandleRowRootElementProps["sameWidth"];
  /**
   * Whether to constrain the floating element's height so that it matches the
   * reference element.
   *
   * @default false
   */
  sameHeight?: TableHandleRowRootElementProps["sameHeight"];
  /**
   * Whether to improve positioning for inline reference elements that span over
   * multiple lines.
   *
   * @default false
   */
  inline?: TableHandleRowRootElementProps["inline"];
  /**
   * Describes the clipping element(s) or area that overflow will be checked relative to.
   * Please see https://floating-ui.com/docs/detectoverflow#boundary for more information.
   *
   * @default 'clippingAncestors'
   */
  boundary?: TableHandleRowRootElementProps["boundary"];
  /**
   * Describes the root boundary that the element will be checked for overflow relative to.
   * Please see https://floating-ui.com/docs/detectoverflow#rootboundary for more information.
   *
   * @default 'viewport'
   */
  rootBoundary?: TableHandleRowRootElementProps["rootBoundary"];
  /**
   * Describes the virtual padding around the boundary to check for overflow.
   * Please see https://floating-ui.com/docs/detectoverflow#padding for more information.
   *
   * @default 4
   */
  overflowPadding?: TableHandleRowRootElementProps["overflowPadding"];
  /**
   * The element that will be used to check for overflow. Please see
   * https://floating-ui.com/docs/detectoverflow#elementcontext for more
   * information.
   *
   * @default 'floating'
   */
  elementContext?: TableHandleRowRootElementProps["elementContext"];
  /**
   * Whether to check the alternate elementContext's boundary. Please see
   * https://floating-ui.com/docs/detectoverflow#altboundary for more
   * information.
   *
   * @default false
   */
  altBoundary?: TableHandleRowRootElementProps["altBoundary"];
  children?: Snippet;
  [key: string]: unknown;
}

/**
 * A Svelte component that renders an `prosekit-table-handle-row-root` custom element.
 *
 * @public
 */
export const TableHandleRowRoot: Component<TableHandleRowRootProps> =
  TableHandleRowRootComponent as unknown as Component<TableHandleRowRootProps>;
