<!-- This file is auto-generated by the "@aria-ui/cli" tool. Do not edit this file directly. -->

<script lang="js">
  import { registerTableHandlePopoverPositionerElement } from '@prosekit/web/table-handle'
  registerTableHandlePopoverPositionerElement()

  let { altBoundary: p0, autoUpdate: p1, boundary: p2, elementContext: p3, fitViewport: p4, flip: p5, hide: p6, hoist: p7, inline: p8, offset: p9, overflowPadding: p10, overlap: p11, placement: p12, rootBoundary: p13, sameHeight: p14, sameWidth: p15, shift: p16, strategy: p17, children = undefined, ...restProps } = $props()
  let element

  $effect.pre(() => {
    if (!element) return

    Object.assign(element, { altBoundary: p0, autoUpdate: p1, boundary: p2, elementContext: p3, fitViewport: p4, flip: p5, hide: p6, hoist: p7, inline: p8, offset: p9, overflowPadding: p10, overlap: p11, placement: p12, rootBoundary: p13, sameHeight: p14, sameWidth: p15, shift: p16, strategy: p17 })
  })
</script>

<prosekit-table-handle-popover-positioner {...restProps} bind:this={element}>{@render children?.()}</prosekit-table-handle-popover-positioner>
