<!-- This file is auto-generated by the "@aria-ui/cli" tool. Do not edit this file directly. -->

<script lang="ts">
  import { registerTableHandleColumnPopupElement } from '@prosekit/web/table-handle'
  registerTableHandleColumnPopupElement()

  let { children = undefined, ...restProps } = $props()
</script>

<prosekit-table-handle-column-popup {...restProps}>{@render children?.()}</prosekit-table-handle-column-popup>
