// This file is auto-generated by "@aria-ui/cli". Do not edit this file directly.

import type { TableHandleRootElement, TableHandleRootProps as TableHandleRootElementProps } from '@prosekit/web/table-handle';
import type { Component, Snippet } from 'svelte';
import type { HTMLAttributes } from 'svelte/elements';

import TableHandleRootComponent from './table-handle-root.gen.svelte';

/**
 * Props for the {@link TableHandleRoot} Svelte component.
 *
 * @public
 */
export interface TableHandleRootProps {
  /**
   * The ProseKit editor instance.
   *
   * @default null
   * @hidden
   */
  editor?: TableHandleRootElementProps['editor'];
  children?: Snippet;
}

/**
 * A Svelte component that renders an `prosekit-table-handle-root` custom element.
 *
 * @public
 */
export const TableHandleRoot: Component<TableHandleRootProps & HTMLAttributes<TableHandleRootElement>> = TableHandleRootComponent as Component<TableHandleRootProps & HTMLAttributes<TableHandleRootElement>>;
