/**
 * This file is auto-generated by the "@aria-ui/cli" tool. Do not edit this file directly.
 */

import type { TableHandleDragPreviewProps as TableHandleDragPreviewElementProps } from '@prosekit/web/table-handle';
import type { Component, Snippet } from 'svelte';

import TableHandleDragPreviewComponent from './table-handle-drag-preview.gen.svelte';

/**
 * Props for the {@link TableHandleDragPreview} Svelte component.
 *
 * @public
 */
export interface TableHandleDragPreviewProps {
  /**
   * @default null
   * @hidden
   */
  editor?: TableHandleDragPreviewElementProps['editor'];
  children?: Snippet;
  [key: string]: unknown;
}

/**
 * A Svelte component that renders an `prosekit-table-handle-drag-preview` custom element.
 *
 * @public
 */
export const TableHandleDragPreview: Component<TableHandleDragPreviewProps> = TableHandleDragPreviewComponent as unknown as Component<TableHandleDragPreviewProps>;
