<script lang="ts">
  // This file is auto-generated by "@aria-ui/cli". Do not edit this file directly.
  import { registerTableHandleRowPopupElement } from '@prosekit/web/table-handle'
  registerTableHandleRowPopupElement()

  let { children = undefined, ...restProps } = $props()
</script>

<prosekit-table-handle-row-popup {...restProps}>{@render children?.()}</prosekit-table-handle-row-popup>
