<!-- This file is auto-generated by the "@aria-ui/cli" tool. Do not edit this file directly. -->

<script lang="js">
  import { registerTableHandlePopoverItemElement } from '@prosekit/web/table-handle'
  registerTableHandlePopoverItemElement()

  let { disabled: p0, value: p1, onItemSelect: p2, children = undefined, ...restProps } = $props()

  const attachment = (element) => {
    if (!element) return

    const abortController = new AbortController()
    const abortSignal = abortController.signal

    if (p0 !== undefined) { element.disabled = p0 }

    if (p1 !== undefined) { element.value = p1 }

    if (p2 !== undefined) { element.addEventListener('itemSelect', p2, { signal: abortSignal }) }

    return () => {
      abortController.abort()
    }
  }
</script>

<prosekit-table-handle-popover-item {...restProps} {@attach attachment}>{@render children?.()}</prosekit-table-handle-popover-item>
