// This file is auto-generated by "@aria-ui/cli". Do not edit this file directly.

import type { TableHandleDragPreviewElement, TableHandleDragPreviewProps as TableHandleDragPreviewElementProps } from '@prosekit/web/table-handle';
import type { Component, Snippet } from 'svelte';
import type { HTMLAttributes } from 'svelte/elements';

import TableHandleDragPreviewComponent from './table-handle-drag-preview.gen.svelte';

/**
 * Props for the {@link TableHandleDragPreview} Svelte component.
 *
 * @public
 */
export interface TableHandleDragPreviewProps {
  /**
   * @default null
   * @hidden
   */
  editor?: TableHandleDragPreviewElementProps['editor'];
  children?: Snippet;
}

/**
 * A Svelte component that renders an `prosekit-table-handle-drag-preview` custom element.
 *
 * @public
 */
export const TableHandleDragPreview: Component<TableHandleDragPreviewProps & HTMLAttributes<TableHandleDragPreviewElement>> = TableHandleDragPreviewComponent as Component<TableHandleDragPreviewProps & HTMLAttributes<TableHandleDragPreviewElement>>;
