/**
 * This file is auto-generated by the "@aria-ui/cli" tool. Do not edit this file directly.
 */

import type { TableHandleRowTriggerProps as TableHandleRowTriggerElementProps } from "@prosekit/web/table-handle";
import type { Component, Snippet } from "svelte";

import TableHandleRowTriggerComponent from "./table-handle-row-trigger.gen.svelte";

/**
 * Props for the {@link TableHandleRowTrigger} Svelte component.
 *
 * @public
 */
export interface TableHandleRowTriggerProps {
  /**
   * @default null
   * @hidden
   */
  editor?: TableHandleRowTriggerElementProps["editor"];
  children?: Snippet;
  [key: string]: unknown;
}

/**
 * A Svelte component that renders an `prosekit-table-handle-row-trigger` custom element.
 *
 * @public
 */
export const TableHandleRowTrigger: Component<TableHandleRowTriggerProps> =
  TableHandleRowTriggerComponent as unknown as Component<TableHandleRowTriggerProps>;
