/**
 * This file is auto-generated by the "@aria-ui/cli" tool. Do not edit this file directly.
 */

import type { TableHandleColumnRootProps as TableHandleColumnRootElementProps } from "@prosekit/web/table-handle";
import type { Component, Snippet } from "svelte";

import TableHandleColumnRootComponent from "./table-handle-column-root.gen.svelte";

/**
 * Props for the {@link TableHandleColumnRoot} Svelte component.
 *
 * @public
 */
export interface TableHandleColumnRootProps {
  /**
   * The ProseKit editor instance.
   *
   * @default null
   * @hidden
   */
  editor?: TableHandleColumnRootElementProps["editor"];
  /**
   * The placement of the popover, relative to the hovered table cell.
   *
   * @default "top"
   */
  placement?: TableHandleColumnRootElementProps["placement"];
  /**
   * Whether to use the browser [Popover API](https://developer.mozilla.org/en-US/docs/Web/API/Popover_API)
   * to place the floating element on top of other page content.
   *
   * @default false
   */
  hoist?: TableHandleColumnRootElementProps["hoist"];
  /**
   * @default false
   * @hidden
   */
  flip?: TableHandleColumnRootElementProps["flip"];
  /**
   * @default false
   * @hidden
   */
  shift?: TableHandleColumnRootElementProps["shift"];
  /**
   * @default true
   * @hidden
   */
  hide?: TableHandleColumnRootElementProps["hide"];
  /**
   * The strategy to use for positioning
   *
   * @default "absolute"
   */
  strategy?: TableHandleColumnRootElementProps["strategy"];
  /**
   * Options to activate auto-update listeners
   *
   * @see https://floating-ui.com/docs/autoUpdate
   *
   * @default true
   */
  autoUpdate?: TableHandleColumnRootElementProps["autoUpdate"];
  /**
   * The distance between the reference and floating element.
   *
   * @default 6
   */
  offset?: TableHandleColumnRootElementProps["offset"];
  /**
   * Whether the floating element can overlap the reference element to keep it
   * in view.
   *
   * @default false
   */
  overlap?: TableHandleColumnRootElementProps["overlap"];
  /**
   * Whether to constrain the floating element's width and height to not exceed
   * the viewport.
   *
   * @default false
   */
  fitViewport?: TableHandleColumnRootElementProps["fitViewport"];
  /**
   * Whether to constrain the floating element's width so that it matches the
   * reference element.
   *
   * @default false
   */
  sameWidth?: TableHandleColumnRootElementProps["sameWidth"];
  /**
   * Whether to constrain the floating element's height so that it matches the
   * reference element.
   *
   * @default false
   */
  sameHeight?: TableHandleColumnRootElementProps["sameHeight"];
  /**
   * Whether to improve positioning for inline reference elements that span over
   * multiple lines.
   *
   * @default false
   */
  inline?: TableHandleColumnRootElementProps["inline"];
  /**
   * Describes the clipping element(s) or area that overflow will be checked relative to.
   * Please see https://floating-ui.com/docs/detectoverflow#boundary for more information.
   *
   * @default 'clippingAncestors'
   */
  boundary?: TableHandleColumnRootElementProps["boundary"];
  /**
   * Describes the root boundary that the element will be checked for overflow relative to.
   * Please see https://floating-ui.com/docs/detectoverflow#rootboundary for more information.
   *
   * @default 'viewport'
   */
  rootBoundary?: TableHandleColumnRootElementProps["rootBoundary"];
  /**
   * Describes the virtual padding around the boundary to check for overflow.
   * Please see https://floating-ui.com/docs/detectoverflow#padding for more information.
   *
   * @default 4
   */
  overflowPadding?: TableHandleColumnRootElementProps["overflowPadding"];
  /**
   * The element that will be used to check for overflow. Please see
   * https://floating-ui.com/docs/detectoverflow#elementcontext for more
   * information.
   *
   * @default 'floating'
   */
  elementContext?: TableHandleColumnRootElementProps["elementContext"];
  /**
   * Whether to check the alternate elementContext's boundary. Please see
   * https://floating-ui.com/docs/detectoverflow#altboundary for more
   * information.
   *
   * @default false
   */
  altBoundary?: TableHandleColumnRootElementProps["altBoundary"];
  children?: Snippet;
  [key: string]: unknown;
}

/**
 * A Svelte component that renders an `prosekit-table-handle-column-root` custom element.
 *
 * @public
 */
export const TableHandleColumnRoot: Component<TableHandleColumnRootProps> =
  TableHandleColumnRootComponent as unknown as Component<TableHandleColumnRootProps>;
