/**
 * This file is auto-generated by the "@aria-ui/cli" tool. Do not edit this file directly.
 */

import type {
  TableHandlePopoverItemEvents,
  TableHandlePopoverItemProps as TableHandlePopoverItemElementProps,
} from "@prosekit/web/table-handle";
import type { Component, Snippet } from "svelte";

import TableHandlePopoverItemComponent from "./table-handle-popover-item.gen.svelte";

/**
 * Props for the {@link TableHandlePopoverItem} Svelte component.
 *
 * @public
 */
export interface TableHandlePopoverItemProps {
  /** @default "" */
  value?: TableHandlePopoverItemElementProps["value"];
  /** @default false */
  disabled?: TableHandlePopoverItemElementProps["disabled"];
  /** */
  onItemSelect?: (event: TableHandlePopoverItemEvents["itemSelect"]) => void;
  children?: Snippet;
  [key: string]: unknown;
}

/**
 * A Svelte component that renders an `prosekit-table-handle-popover-item` custom element.
 *
 * @public
 */
export const TableHandlePopoverItem: Component<TableHandlePopoverItemProps> =
  TableHandlePopoverItemComponent as unknown as Component<TableHandlePopoverItemProps>;

export type { TableHandlePopoverItemEvents };
export { TableHandlePopoverItemSelectEvent } from "@prosekit/web/table-handle";
