// This file is auto-generated by "@aria-ui/cli". Do not edit this file directly.

import { registerAutocompleteEmptyElement, type AutocompleteEmptyElement } from '@prosekit/web/autocomplete';
import type { Component, JSX } from 'solid-js';
import h from 'solid-js/h';

/** Props for the {@link AutocompleteEmpty} Solid component. */
export interface AutocompleteEmptyProps {}

/** A Solid component that renders an `prosekit-autocomplete-empty` custom element. */
export const AutocompleteEmpty: Component<AutocompleteEmptyProps & JSX.HTMLAttributes<AutocompleteEmptyElement>> = (props): any => {
  registerAutocompleteEmptyElement();

  const restProps = props;

  return () => h('prosekit-autocomplete-empty', restProps);
};
