// This file is generated from update-website-pages.ts
import { lazy } from 'react'

export const loaders = {
  'block-handle': lazy(() => import('prosekit-registry/react/examples/block-handle').then((m) => ({ default: m.ExampleEditor }))),
  'blockquote': lazy(() => import('prosekit-registry/react/examples/blockquote').then((m) => ({ default: m.ExampleEditor }))),
  'bold': lazy(() => import('prosekit-registry/react/examples/bold').then((m) => ({ default: m.ExampleEditor }))),
  'change-tracking': lazy(() => import('prosekit-registry/react/examples/change-tracking').then((m) => ({ default: m.ExampleEditor }))),
  'code': lazy(() => import('prosekit-registry/react/examples/code').then((m) => ({ default: m.ExampleEditor }))),
  'code-block': lazy(() => import('prosekit-registry/react/examples/code-block').then((m) => ({ default: m.ExampleEditor }))),
  'code-block-themes': lazy(() => import('prosekit-registry/react/examples/code-block-themes').then((m) => ({ default: m.ExampleEditor }))),
  'drop-cursor': lazy(() => import('prosekit-registry/react/examples/drop-cursor').then((m) => ({ default: m.ExampleEditor }))),
  'emoji-rules': lazy(() => import('prosekit-registry/react/examples/emoji-rules').then((m) => ({ default: m.ExampleEditor }))),
  'full': lazy(() => import('prosekit-registry/react/examples/full').then((m) => ({ default: m.ExampleEditor }))),
  'gap-cursor': lazy(() => import('prosekit-registry/react/examples/gap-cursor').then((m) => ({ default: m.ExampleEditor }))),
  'hard-break': lazy(() => import('prosekit-registry/react/examples/hard-break').then((m) => ({ default: m.ExampleEditor }))),
  'heading': lazy(() => import('prosekit-registry/react/examples/heading').then((m) => ({ default: m.ExampleEditor }))),
  'horizontal-rule': lazy(() => import('prosekit-registry/react/examples/horizontal-rule').then((m) => ({ default: m.ExampleEditor }))),
  'image-view': lazy(() => import('prosekit-registry/react/examples/image-view').then((m) => ({ default: m.ExampleEditor }))),
  'inline-menu': lazy(() => import('prosekit-registry/react/examples/inline-menu').then((m) => ({ default: m.ExampleEditor }))),
  'italic': lazy(() => import('prosekit-registry/react/examples/italic').then((m) => ({ default: m.ExampleEditor }))),
  'keymap': lazy(() => import('prosekit-registry/react/examples/keymap').then((m) => ({ default: m.ExampleEditor }))),
  'link': lazy(() => import('prosekit-registry/react/examples/link').then((m) => ({ default: m.ExampleEditor }))),
  'link-mark-view': lazy(() => import('prosekit-registry/react/examples/link-mark-view').then((m) => ({ default: m.ExampleEditor }))),
  'list': lazy(() => import('prosekit-registry/react/examples/list').then((m) => ({ default: m.ExampleEditor }))),
  'list-custom-checkbox': lazy(() => import('prosekit-registry/react/examples/list-custom-checkbox').then((m) => ({ default: m.ExampleEditor }))),
  'loro': lazy(() => import('prosekit-registry/react/examples/loro').then((m) => ({ default: m.ExampleEditor }))),
  'mark-rule': lazy(() => import('prosekit-registry/react/examples/mark-rule').then((m) => ({ default: m.ExampleEditor }))),
  'minimal': lazy(() => import('prosekit-registry/react/examples/minimal').then((m) => ({ default: m.ExampleEditor }))),
  'placeholder': lazy(() => import('prosekit-registry/react/examples/placeholder').then((m) => ({ default: m.ExampleEditor }))),
  'readonly': lazy(() => import('prosekit-registry/react/examples/readonly').then((m) => ({ default: m.ExampleEditor }))),
  'save-html': lazy(() => import('prosekit-registry/react/examples/save-html').then((m) => ({ default: m.ExampleEditor }))),
  'save-json': lazy(() => import('prosekit-registry/react/examples/save-json').then((m) => ({ default: m.ExampleEditor }))),
  'save-markdown': lazy(() => import('prosekit-registry/react/examples/save-markdown').then((m) => ({ default: m.ExampleEditor }))),
  'search': lazy(() => import('prosekit-registry/react/examples/search').then((m) => ({ default: m.ExampleEditor }))),
  'slash-menu': lazy(() => import('prosekit-registry/react/examples/slash-menu').then((m) => ({ default: m.ExampleEditor }))),
  'strike': lazy(() => import('prosekit-registry/react/examples/strike').then((m) => ({ default: m.ExampleEditor }))),
  'table': lazy(() => import('prosekit-registry/react/examples/table').then((m) => ({ default: m.ExampleEditor }))),
  'text-align': lazy(() => import('prosekit-registry/react/examples/text-align').then((m) => ({ default: m.ExampleEditor }))),
  'text-color': lazy(() => import('prosekit-registry/react/examples/text-color').then((m) => ({ default: m.ExampleEditor }))),
  'toolbar': lazy(() => import('prosekit-registry/react/examples/toolbar').then((m) => ({ default: m.ExampleEditor }))),
  'typography': lazy(() => import('prosekit-registry/react/examples/typography').then((m) => ({ default: m.ExampleEditor }))),
  'underline': lazy(() => import('prosekit-registry/react/examples/underline').then((m) => ({ default: m.ExampleEditor }))),
  'unmount': lazy(() => import('prosekit-registry/react/examples/unmount').then((m) => ({ default: m.ExampleEditor }))),
  'user-menu': lazy(() => import('prosekit-registry/react/examples/user-menu').then((m) => ({ default: m.ExampleEditor }))),
  'user-menu-dynamic': lazy(() => import('prosekit-registry/react/examples/user-menu-dynamic').then((m) => ({ default: m.ExampleEditor }))),
  'word-counter': lazy(() => import('prosekit-registry/react/examples/word-counter').then((m) => ({ default: m.ExampleEditor }))),
  'yjs': lazy(() => import('prosekit-registry/react/examples/yjs').then((m) => ({ default: m.ExampleEditor }))),
}
