/**
 * This file is auto-generated by the "@aria-ui/cli" tool. Do not edit this file directly.
 */

import {
  defineComponent,
  h,
  type DefineSetupFnComponent,
  type HTMLAttributes,
} from "vue";
import {
  registerTooltipRootElement,
  type TooltipRootEvents,
  type TooltipRootProps as TooltipRootElementProps,
  TooltipRootPropsDeclaration,
} from "@prosekit/web/tooltip";

/**
 * Props for the {@link TooltipRoot} Vue component.
 *
 * @public
 */
export interface TooltipRootProps {
  /**
   * Whether the overlay is initially open.
   * @default false
   */
  defaultOpen?: TooltipRootElementProps["defaultOpen"];
  /**
   * Whether the overlay is currently open.
   * @default null
   */
  open?: TooltipRootElementProps["open"];
  /**
   * Whether the component should ignore user interaction.
   * @default false
   */
  disabled?: TooltipRootElementProps["disabled"];
  /** Emitted when the tooltip is opened or closed. */
  onOpenChange?: (event: TooltipRootEvents["openChange"]) => void;
}

/**
 * A Vue component that renders an `prosekit-tooltip-root` custom element.
 *
 * @public
 */
export const TooltipRoot: DefineSetupFnComponent<
  TooltipRootProps & HTMLAttributes
> = /* @__PURE__ */ defineComponent<TooltipRootProps & HTMLAttributes>(
  (props, { slots }) => {
    registerTooltipRootElement();
    const _eventHandlers: Record<string, Function> = {};
    let _abortController: AbortController | undefined;

    const _ref = (element: HTMLElement | null | undefined) => {
      _abortController?.abort();
      _abortController = undefined;

      if (!element) {
        return;
      }

      _abortController = new AbortController();
      const abortSignal = _abortController.signal;

      element.addEventListener(
        "openChange",
        (event) => {
          _eventHandlers["onOpenChange"]?.(event);
        },
        { signal: abortSignal },
      );
    };

    return () => {
      const _props: Record<string, unknown> = {};
      for (const [key, value] of Object.entries(props)) {
        switch (key) {
          case "defaultOpen":
          case "disabled":
          case "open":
            _props["." + key] = value;
            break;
          case "onOpenChange":
            _eventHandlers[key] = value as Function;
            break;
          default:
            _props[key] = value;
        }
      }

      _props["ref"] = _ref;
      return h("prosekit-tooltip-root", _props, slots.default?.());
    };
  },
  {
    props: {
      defaultOpen: { default: TooltipRootPropsDeclaration.defaultOpen.default },
      disabled: { default: TooltipRootPropsDeclaration.disabled.default },
      open: { default: TooltipRootPropsDeclaration.open.default },
      onOpenChange: { type: Function },
    } as Record<string, unknown>,
  },
);

export type { TooltipRootEvents };
export { OpenChangeEvent } from "@prosekit/web/tooltip";
