/**
 * This file is auto-generated by the "@aria-ui/cli" tool. Do not edit this file directly.
 */

import { ReactWrapper } from "@aria-ui-v2/integrations/react";
import {
  createElement,
  forwardRef,
  type ForwardedRef,
  type ForwardRefExoticComponent,
  type HTMLAttributes,
  type RefAttributes,
} from "react";
import {
  registerInlinePopoverElement,
  type InlinePopoverElement,
  type InlinePopoverProps as InlinePopoverElementProps,
  type InlinePopoverEvents,
} from "@prosekit/web/inline-popover";
import { useEditorContext } from "../../contexts/editor-context.ts";

const propNames: string[] = [
  "altBoundary",
  "autoUpdate",
  "boundary",
  "defaultOpen",
  "dismissOnEscape",
  "editor",
  "elementContext",
  "fitViewport",
  "flip",
  "hide",
  "hoist",
  "inline",
  "offset",
  "open",
  "overflowPadding",
  "overlap",
  "placement",
  "rootBoundary",
  "sameHeight",
  "sameWidth",
  "shift",
  "strategy",
];
const eventNameMap: Record<string, string> = { onOpenChange: "openChange" };

/**
 * Props for the {@link InlinePopover} React component.
 *
 * @public
 */
export interface InlinePopoverProps extends HTMLAttributes<InlinePopoverElement> {
  /**
   * The ProseKit editor instance.
   *
   * @default null
   * @hidden
   */
  editor?: InlinePopoverElementProps["editor"];
  /**
   * Whether the popover is open by default when some inline content is
   * selected.
   *
   * When `defaultOpen` is true, the popover will open or close based on the
   * inline selection. When `defaultOpen` is false, the popover will never be
   * opened unless the `open` prop is true.
   *
   * @default true
   */
  defaultOpen?: InlinePopoverElementProps["defaultOpen"];
  /**
   * Whether the popover is open.
   *
   * Notice that the popover will be always hidden if the inline selection is
   * empty.
   *
   * @default false
   */
  open?: InlinePopoverElementProps["open"];
  /**
   * Whether the inline popover should be dismissed when the editor receives an
   * Escape key press.
   *
   * @default true
   */
  dismissOnEscape?: InlinePopoverElementProps["dismissOnEscape"];
  /** @default "top" */
  placement?: InlinePopoverElementProps["placement"];
  /** @default 12 */
  offset?: InlinePopoverElementProps["offset"];
  /** @default true */
  hide?: InlinePopoverElementProps["hide"];
  /** @default true */
  overlap?: InlinePopoverElementProps["overlap"];
  /** @default true */
  inline?: InlinePopoverElementProps["inline"];
  /** @default 8 */
  overflowPadding?: InlinePopoverElementProps["overflowPadding"];
  /**
   * The strategy to use for positioning
   *
   * @default "absolute"
   */
  strategy?: InlinePopoverElementProps["strategy"];
  /**
   * Options to activate auto-update listeners
   *
   * @see https://floating-ui.com/docs/autoUpdate
   *
   * @default true
   */
  autoUpdate?: InlinePopoverElementProps["autoUpdate"];
  /**
   * Whether to use the browser Popover API to place the floating element on
   * top of other page content.
   *
   * @default true
   */
  hoist?: InlinePopoverElementProps["hoist"];
  /**
   * Whether to flip the `placement` in order to keep it in view when the
   * preferred placement(s) will overflow the clipping boundary. You can also
   * provide an array of placements to try sequentially if the preferred
   * `placement` does not fit.
   *
   * @default true
   */
  flip?: InlinePopoverElementProps["flip"];
  /**
   * Whether the floating element should shift to keep it in view.
   *
   * @default true
   */
  shift?: InlinePopoverElementProps["shift"];
  /**
   * Whether to constrain the floating element's width and height to not exceed
   * the viewport.
   *
   * @default false
   */
  fitViewport?: InlinePopoverElementProps["fitViewport"];
  /**
   * Whether to constrain the floating element's width so that it matches the
   * reference element.
   *
   * @default false
   */
  sameWidth?: InlinePopoverElementProps["sameWidth"];
  /**
   * Whether to constrain the floating element's height so that it matches the
   * reference element.
   *
   * @default false
   */
  sameHeight?: InlinePopoverElementProps["sameHeight"];
  /**
   * Describes the clipping element(s) or area that overflow will be checked relative to.
   * Please see https://floating-ui.com/docs/detectoverflow#boundary for more information.
   *
   * @default 'clippingAncestors'
   */
  boundary?: InlinePopoverElementProps["boundary"];
  /**
   * Describes the root boundary that the element will be checked for overflow relative to.
   * Please see https://floating-ui.com/docs/detectoverflow#rootboundary for more information.
   *
   * @default 'viewport'
   */
  rootBoundary?: InlinePopoverElementProps["rootBoundary"];
  /**
   * The element that will be used to check for overflow. Please see
   * https://floating-ui.com/docs/detectoverflow#elementcontext for more
   * information.
   *
   * @default 'floating'
   */
  elementContext?: InlinePopoverElementProps["elementContext"];
  /**
   * Whether to check the alternate elementContext's boundary. Please see
   * https://floating-ui.com/docs/detectoverflow#altboundary for more
   * information.
   *
   * @default false
   */
  altBoundary?: InlinePopoverElementProps["altBoundary"];
  /** Fired when the open state changes. */
  onOpenChange?: (event: InlinePopoverEvents["openChange"]) => void;
}

function InlinePopoverComponent(
  props: InlinePopoverProps,
  forwardedRef: ForwardedRef<InlinePopoverElement>,
) {
  registerInlinePopoverElement();
  const componentProps: InlinePopoverProps = { ...props };
  const editorContext = useEditorContext();
  if (componentProps.editor == null && editorContext != null) {
    componentProps.editor = editorContext;
  }

  return createElement(ReactWrapper, {
    as: "prosekit-inline-popover",
    propNames,
    eventNameMap,
    props: componentProps,
    forwardedRef,
  });
}

/**
 * A React component that renders an `prosekit-inline-popover` custom element.
 *
 * @public
 */
export const InlinePopover: ForwardRefExoticComponent<
  InlinePopoverProps & RefAttributes<InlinePopoverElement>
> = /* @__PURE__ */ forwardRef(InlinePopoverComponent);

export type { InlinePopoverEvents };
export { OpenChangeEvent } from "@prosekit/web/inline-popover";
