// This file is auto-generated by "@aria-ui/cli". Do not edit this file directly.

import type { ResizableHandleElement, ResizableHandleProps as ResizableHandleElementProps } from '@prosekit/web/resizable';
import type { Component, Snippet } from 'svelte';
import type { HTMLAttributes } from 'svelte/elements';

import ResizableHandleComponent from './resizable-handle.gen.svelte';

/** Props for the {@link ResizableHandle} Svelte component. */
export interface ResizableHandleProps {
  /**
   * The position of the handle.
   *
   * @default "bottom-right"
   */
  position?: ResizableHandleElementProps['position'];
  children?: Snippet;
}

/** A Svelte component that renders an `prosekit-resizable-handle` custom element. */
export const ResizableHandle: Component<ResizableHandleProps & HTMLAttributes<ResizableHandleElement>> = ResizableHandleComponent as Component<ResizableHandleProps & HTMLAttributes<ResizableHandleElement>>;
