// This file is generated from update-loader.ts
import { lazy } from 'preact/compat'
import { sleep } from '@ocavue/utils'

export const loaders = {
  'block-handle': lazy(() => import('./examples/block-handle').then(async (m) => {await sleep(300); return m}).then((m) => ({ default: m.ExampleEditor }))),
  'blockquote': lazy(() => import('./examples/blockquote').then(async (m) => {await sleep(300); return m}).then((m) => ({ default: m.ExampleEditor }))),
  'bold': lazy(() => import('./examples/bold').then(async (m) => {await sleep(300); return m}).then((m) => ({ default: m.ExampleEditor }))),
  'change-tracking': lazy(() => import('./examples/change-tracking').then(async (m) => {await sleep(300); return m}).then((m) => ({ default: m.ExampleEditor }))),
  'code': lazy(() => import('./examples/code').then(async (m) => {await sleep(300); return m}).then((m) => ({ default: m.ExampleEditor }))),
  'code-block': lazy(() => import('./examples/code-block').then(async (m) => {await sleep(300); return m}).then((m) => ({ default: m.ExampleEditor }))),
  'code-block-themes': lazy(() => import('./examples/code-block-themes').then(async (m) => {await sleep(300); return m}).then((m) => ({ default: m.ExampleEditor }))),
  'drop-cursor': lazy(() => import('./examples/drop-cursor').then(async (m) => {await sleep(300); return m}).then((m) => ({ default: m.ExampleEditor }))),
  'emoji-rules': lazy(() => import('./examples/emoji-rules').then(async (m) => {await sleep(300); return m}).then((m) => ({ default: m.ExampleEditor }))),
  'full': lazy(() => import('./examples/full').then(async (m) => {await sleep(300); return m}).then((m) => ({ default: m.ExampleEditor }))),
  'gap-cursor': lazy(() => import('./examples/gap-cursor').then(async (m) => {await sleep(300); return m}).then((m) => ({ default: m.ExampleEditor }))),
  'hard-break': lazy(() => import('./examples/hard-break').then(async (m) => {await sleep(300); return m}).then((m) => ({ default: m.ExampleEditor }))),
  'heading': lazy(() => import('./examples/heading').then(async (m) => {await sleep(300); return m}).then((m) => ({ default: m.ExampleEditor }))),
  'horizontal-rule': lazy(() => import('./examples/horizontal-rule').then(async (m) => {await sleep(300); return m}).then((m) => ({ default: m.ExampleEditor }))),
  'image-view': lazy(() => import('./examples/image-view').then(async (m) => {await sleep(300); return m}).then((m) => ({ default: m.ExampleEditor }))),
  'inline-menu': lazy(() => import('./examples/inline-menu').then(async (m) => {await sleep(300); return m}).then((m) => ({ default: m.ExampleEditor }))),
  'italic': lazy(() => import('./examples/italic').then(async (m) => {await sleep(300); return m}).then((m) => ({ default: m.ExampleEditor }))),
  'keymap': lazy(() => import('./examples/keymap').then(async (m) => {await sleep(300); return m}).then((m) => ({ default: m.ExampleEditor }))),
  'link': lazy(() => import('./examples/link').then(async (m) => {await sleep(300); return m}).then((m) => ({ default: m.ExampleEditor }))),
  'link-mark-view': lazy(() => import('./examples/link-mark-view').then(async (m) => {await sleep(300); return m}).then((m) => ({ default: m.ExampleEditor }))),
  'list': lazy(() => import('./examples/list').then(async (m) => {await sleep(300); return m}).then((m) => ({ default: m.ExampleEditor }))),
  'list-custom-checkbox': lazy(() => import('./examples/list-custom-checkbox').then(async (m) => {await sleep(300); return m}).then((m) => ({ default: m.ExampleEditor }))),
  'loro': lazy(() => import('./examples/loro').then(async (m) => {await sleep(300); return m}).then((m) => ({ default: m.ExampleEditor }))),
  'mark-rule': lazy(() => import('./examples/mark-rule').then(async (m) => {await sleep(300); return m}).then((m) => ({ default: m.ExampleEditor }))),
  'minimal': lazy(() => import('./examples/minimal').then(async (m) => {await sleep(300); return m}).then((m) => ({ default: m.ExampleEditor }))),
  'placeholder': lazy(() => import('./examples/placeholder').then(async (m) => {await sleep(300); return m}).then((m) => ({ default: m.ExampleEditor }))),
  'readonly': lazy(() => import('./examples/readonly').then(async (m) => {await sleep(300); return m}).then((m) => ({ default: m.ExampleEditor }))),
  'rtl': lazy(() => import('./examples/rtl').then(async (m) => {await sleep(300); return m}).then((m) => ({ default: m.ExampleEditor }))),
  'save-html': lazy(() => import('./examples/save-html').then(async (m) => {await sleep(300); return m}).then((m) => ({ default: m.ExampleEditor }))),
  'save-json': lazy(() => import('./examples/save-json').then(async (m) => {await sleep(300); return m}).then((m) => ({ default: m.ExampleEditor }))),
  'save-markdown': lazy(() => import('./examples/save-markdown').then(async (m) => {await sleep(300); return m}).then((m) => ({ default: m.ExampleEditor }))),
  'search': lazy(() => import('./examples/search').then(async (m) => {await sleep(300); return m}).then((m) => ({ default: m.ExampleEditor }))),
  'slash-menu': lazy(() => import('./examples/slash-menu').then(async (m) => {await sleep(300); return m}).then((m) => ({ default: m.ExampleEditor }))),
  'strike': lazy(() => import('./examples/strike').then(async (m) => {await sleep(300); return m}).then((m) => ({ default: m.ExampleEditor }))),
  'table': lazy(() => import('./examples/table').then(async (m) => {await sleep(300); return m}).then((m) => ({ default: m.ExampleEditor }))),
  'text-align': lazy(() => import('./examples/text-align').then(async (m) => {await sleep(300); return m}).then((m) => ({ default: m.ExampleEditor }))),
  'text-color': lazy(() => import('./examples/text-color').then(async (m) => {await sleep(300); return m}).then((m) => ({ default: m.ExampleEditor }))),
  'toolbar': lazy(() => import('./examples/toolbar').then(async (m) => {await sleep(300); return m}).then((m) => ({ default: m.ExampleEditor }))),
  'typography': lazy(() => import('./examples/typography').then(async (m) => {await sleep(300); return m}).then((m) => ({ default: m.ExampleEditor }))),
  'underline': lazy(() => import('./examples/underline').then(async (m) => {await sleep(300); return m}).then((m) => ({ default: m.ExampleEditor }))),
  'unmount': lazy(() => import('./examples/unmount').then(async (m) => {await sleep(300); return m}).then((m) => ({ default: m.ExampleEditor }))),
  'user-menu': lazy(() => import('./examples/user-menu').then(async (m) => {await sleep(300); return m}).then((m) => ({ default: m.ExampleEditor }))),
  'user-menu-dynamic': lazy(() => import('./examples/user-menu-dynamic').then(async (m) => {await sleep(300); return m}).then((m) => ({ default: m.ExampleEditor }))),
  'word-counter': lazy(() => import('./examples/word-counter').then(async (m) => {await sleep(300); return m}).then((m) => ({ default: m.ExampleEditor }))),
  'yjs': lazy(() => import('./examples/yjs').then(async (m) => {await sleep(300); return m}).then((m) => ({ default: m.ExampleEditor }))),
}
