/**
 * This file is auto-generated by the "@aria-ui/cli" tool. Do not edit this file directly.
 */

import {
  defineComponent,
  h,
  type DefineSetupFnComponent,
  type HTMLAttributes,
} from "vue";
import {
  registerTableHandleDragPreviewElement,
  type TableHandleDragPreviewProps as TableHandleDragPreviewElementProps,
  TableHandleDragPreviewPropsDeclaration,
} from "@prosekit/web/table-handle";
import { useEditorContext } from "../../injection/editor-context.ts";

/**
 * Props for the {@link TableHandleDragPreview} Vue component.
 *
 * @public
 */
export interface TableHandleDragPreviewProps {
  /**
   * @default null
   * @hidden
   */
  editor?: TableHandleDragPreviewElementProps["editor"];
}

/**
 * A Vue component that renders an `prosekit-table-handle-drag-preview` custom element.
 *
 * @public
 */
export const TableHandleDragPreview: DefineSetupFnComponent<
  TableHandleDragPreviewProps & HTMLAttributes
> = /* @__PURE__ */ defineComponent<
  TableHandleDragPreviewProps & HTMLAttributes
>(
  (props, { slots }) => {
    registerTableHandleDragPreviewElement();
    const p0Fallback = useEditorContext();

    return () => {
      const _props: Record<string, unknown> = {};
      for (const [key, value] of Object.entries(props)) {
        switch (key) {
          case "editor":
            _props["." + key] = value;
            break;
          default:
            _props[key] = value;
        }
      }

      if (_props[".editor"] == null && p0Fallback != null) {
        _props[".editor"] = p0Fallback;
      }
      return h("prosekit-table-handle-drag-preview", _props, slots.default?.());
    };
  },
  {
    props: {
      editor: {
        default: TableHandleDragPreviewPropsDeclaration.editor.default,
      },
    } as Record<string, unknown>,
  },
);
