/**
 * This file is auto-generated by the "@aria-ui/cli" tool. Do not edit this file directly.
 */

import {
  defineComponent,
  h,
  type DefineSetupFnComponent,
  type HTMLAttributes,
} from "vue";
import {
  registerTableHandleDropIndicatorElement,
  type TableHandleDropIndicatorProps as TableHandleDropIndicatorElementProps,
  TableHandleDropIndicatorPropsDeclaration,
} from "@prosekit/web/table-handle";
import { useEditorContext } from "../../injection/editor-context.ts";

/**
 * Props for the {@link TableHandleDropIndicator} Vue component.
 *
 * @public
 */
export interface TableHandleDropIndicatorProps {
  /**
   * @default null
   * @hidden
   */
  editor?: TableHandleDropIndicatorElementProps["editor"];
}

/**
 * A Vue component that renders an `prosekit-table-handle-drop-indicator` custom element.
 *
 * @public
 */
export const TableHandleDropIndicator: DefineSetupFnComponent<
  TableHandleDropIndicatorProps & HTMLAttributes
> = /* @__PURE__ */ defineComponent<
  TableHandleDropIndicatorProps & HTMLAttributes
>(
  (props, { slots }) => {
    registerTableHandleDropIndicatorElement();
    const p0Fallback = useEditorContext();

    return () => {
      const _props: Record<string, unknown> = {};
      for (const [key, value] of Object.entries(props)) {
        switch (key) {
          case "editor":
            _props["." + key] = value;
            break;
          default:
            _props[key] = value;
        }
      }

      if (_props[".editor"] == null && p0Fallback != null) {
        _props[".editor"] = p0Fallback;
      }
      return h(
        "prosekit-table-handle-drop-indicator",
        _props,
        slots.default?.(),
      );
    };
  },
  {
    props: {
      editor: {
        default: TableHandleDropIndicatorPropsDeclaration.editor.default,
      },
    } as Record<string, unknown>,
  },
);
