/**
 * This file is auto-generated by the "@aria-ui/cli" tool. Do not edit this file directly.
 */

import { registerTableHandleRowMenuTriggerElement, type TableHandleRowMenuTriggerProps as TableHandleRowMenuTriggerElementProps } from '@prosekit/web/table-handle';
import { defineComponent, h, type DefineSetupFnComponent, type HTMLAttributes, shallowRef, computed, watchEffect } from 'vue';

import { useEditorContext } from '../../injection/editor-context.ts';

/**
 * Props for the {@link TableHandleRowMenuTrigger} Vue component.
 *
 * @public
 */
export interface TableHandleRowMenuTriggerProps {
  /**
   * @default null
   * @hidden
   */
  editor?: TableHandleRowMenuTriggerElementProps['editor'];
}

/**
 * A Vue component that renders an `prosekit-table-handle-row-menu-trigger` custom element.
 *
 * @public
 */
export const TableHandleRowMenuTrigger: DefineSetupFnComponent<TableHandleRowMenuTriggerProps & HTMLAttributes> = /* @__PURE__ */ defineComponent<TableHandleRowMenuTriggerProps & HTMLAttributes>(
  (props, { slots }) => {
    registerTableHandleRowMenuTriggerElement();

    const elementRef = shallowRef<HTMLElement | null>(null);

    const p0Fallback = useEditorContext();

    const splittedProps = computed(() => {
      const { editor: p0, ...restProps } = props;
      return [[p0], restProps] as const;
    });

    watchEffect(() => {
      const element = elementRef.value;
      if (!element) return;

      const [p0] = splittedProps.value[0];

      Object.assign(element, { editor: p0 ?? p0Fallback });
    });

    return () => {
      const restProps = splittedProps.value[1];
      return h('prosekit-table-handle-row-menu-trigger', { ...restProps, ref: elementRef }, slots.default?.());
    };
  },
  { props: ['editor'] },
);
