/**
 * This file is auto-generated by the "@aria-ui/cli" tool. Do not edit this file directly.
 */

import {
  defineComponent,
  h,
  type DefineSetupFnComponent,
  type HTMLAttributes,
} from "vue";
import {
  registerTableHandleColumnTriggerElement,
  type TableHandleColumnTriggerProps as TableHandleColumnTriggerElementProps,
  TableHandleColumnTriggerPropsDeclaration,
} from "@prosekit/web/table-handle";
import { useEditorContext } from "../../injection/editor-context.ts";

/**
 * Props for the {@link TableHandleColumnTrigger} Vue component.
 *
 * @public
 */
export interface TableHandleColumnTriggerProps {
  /**
   * @default null
   * @hidden
   */
  editor?: TableHandleColumnTriggerElementProps["editor"];
}

/**
 * A Vue component that renders an `prosekit-table-handle-column-trigger` custom element.
 *
 * @public
 */
export const TableHandleColumnTrigger: DefineSetupFnComponent<
  TableHandleColumnTriggerProps & HTMLAttributes
> = /* @__PURE__ */ defineComponent<
  TableHandleColumnTriggerProps & HTMLAttributes
>(
  (props, { slots }) => {
    registerTableHandleColumnTriggerElement();
    const p0Fallback = useEditorContext();

    return () => {
      const _props: Record<string, unknown> = {};
      for (const [key, value] of Object.entries(props)) {
        switch (key) {
          case "editor":
            _props["." + key] = value;
            break;
          default:
            _props[key] = value;
        }
      }

      if (_props[".editor"] == null && p0Fallback != null) {
        _props[".editor"] = p0Fallback;
      }
      return h(
        "prosekit-table-handle-column-trigger",
        _props,
        slots.default?.(),
      );
    };
  },
  {
    props: {
      editor: {
        default: TableHandleColumnTriggerPropsDeclaration.editor.default,
      },
    } as Record<string, unknown>,
  },
);
