// This file is auto-generated by "@aria-ui/cli". Do not edit this file directly.

import { registerTableHandleRootElement, type TableHandleRootProps as TableHandleRootElementProps } from '@prosekit/web/table-handle';
import { defineComponent, h, type DefineSetupFnComponent, type HTMLAttributes, shallowRef, computed, watchEffect } from 'vue';

import { useEditorContext } from '../../injection/editor-context.ts';

/** Props for the {@link TableHandleRoot} Vue component. */
export interface TableHandleRootProps {
  /**
   * The ProseKit editor instance.
   *
   * @default null
   * @hidden
   */
  editor?: TableHandleRootElementProps['editor'];
}

/** A Vue component that renders an `prosekit-table-handle-root` custom element. */
export const TableHandleRoot: DefineSetupFnComponent<TableHandleRootProps & HTMLAttributes> = /* @__PURE__ */ defineComponent<TableHandleRootProps & HTMLAttributes>(
  (props, { slots }) => {
    registerTableHandleRootElement();

    const elementRef = shallowRef<HTMLElement | null>(null);

    const p0Fallback = useEditorContext();

    const splittedProps = computed(() => {
      const { editor: p0, ...restProps } = props;
      return [[p0], restProps] as const;
    });

    watchEffect(() => {
      const element = elementRef.value;
      if (!element) return;

      const [p0] = splittedProps.value[0];

      Object.assign(element, { editor: p0 ?? p0Fallback });
    });

    return () => {
      const restProps = splittedProps.value[1];
      return h('prosekit-table-handle-root', { ...restProps, ref: elementRef }, slots.default?.());
    };
  },
  { props: ['editor'] },
);
