// This file is auto-generated by "@aria-ui/cli". Do not edit this file directly.

import { registerTableHandleColumnMenuRootElement, type TableHandleColumnMenuRootProps as TableHandleColumnMenuRootElementProps } from '@prosekit/web/table-handle';
import { defineComponent, h, type DefineSetupFnComponent, type HTMLAttributes, shallowRef, computed, watchEffect } from 'vue';

/** Props for the {@link TableHandleColumnMenuRoot} Vue component. */
export interface TableHandleColumnMenuRootProps {
  /**
   * Whether the overlay is initially open.
   * @default false
   */
  defaultOpen?: TableHandleColumnMenuRootElementProps['defaultOpen'];
  /**
   * Whether the overlay is currently open.
   * @default null
   */
  open?: TableHandleColumnMenuRootElementProps['open'];
  /**
   * Whether the component should ignore user interaction.
   * @default false
   */
  disabled?: TableHandleColumnMenuRootElementProps['disabled'];
}

/** A Vue component that renders an `prosekit-table-handle-column-menu-root` custom element. */
export const TableHandleColumnMenuRoot: DefineSetupFnComponent<TableHandleColumnMenuRootProps & HTMLAttributes> = /* @__PURE__ */ defineComponent<TableHandleColumnMenuRootProps & HTMLAttributes>(
  (props, { slots }) => {
    registerTableHandleColumnMenuRootElement();

    const elementRef = shallowRef<HTMLElement | null>(null);

    const splittedProps = computed(() => {
      const { defaultOpen: p0, disabled: p1, open: p2, ...restProps } = props;
      return [[p0, p1, p2], restProps] as const;
    });

    watchEffect(() => {
      const element = elementRef.value;
      if (!element) return;

      const [p0, p1, p2] = splittedProps.value[0];

      Object.assign(element, { defaultOpen: p0, disabled: p1, open: p2 });
    });

    return () => {
      const restProps = splittedProps.value[1];
      return h('prosekit-table-handle-column-menu-root', { ...restProps, ref: elementRef }, slots.default?.());
    };
  },
  { props: ['defaultOpen', 'disabled', 'open'] },
);
