/**
 * This file is auto-generated by the "@aria-ui/cli" tool. Do not edit this file directly.
 */

import {
  defineComponent,
  h,
  type DefineSetupFnComponent,
  type HTMLAttributes,
} from "vue";
import {
  registerTableHandleRootElement,
  type TableHandleRootProps as TableHandleRootElementProps,
  TableHandleRootPropsDeclaration,
} from "@prosekit/web/table-handle";
import { useEditorContext } from "../../injection/editor-context.ts";

/**
 * Props for the {@link TableHandleRoot} Vue component.
 *
 * @public
 */
export interface TableHandleRootProps {
  /**
   * The ProseKit editor instance.
   *
   * @default null
   * @hidden
   */
  editor?: TableHandleRootElementProps["editor"];
}

/**
 * A Vue component that renders an `prosekit-table-handle-root` custom element.
 *
 * @public
 */
export const TableHandleRoot: DefineSetupFnComponent<
  TableHandleRootProps & HTMLAttributes
> = /* @__PURE__ */ defineComponent<TableHandleRootProps & HTMLAttributes>(
  (props, { slots }) => {
    registerTableHandleRootElement();
    const editorContext = useEditorContext();

    return () => {
      const _props: Record<string, unknown> = {};
      for (const [key, value] of Object.entries(props)) {
        switch (key) {
          case "editor":
            _props["." + key] = value;
            break;
          default:
            _props[key] = value;
        }
      }

      if (_props[".editor"] == null && editorContext != null) {
        _props[".editor"] = editorContext;
      }
      return h("prosekit-table-handle-root", _props, slots.default?.());
    };
  },
  {
    props: {
      editor: { default: TableHandleRootPropsDeclaration.editor.default },
    } as Record<string, unknown>,
  },
);
