// This file is auto-generated by "@aria-ui/cli". Do not edit this file directly.

import { registerMenuSubmenuTriggerElement, type MenuSubmenuTriggerElement } from '@prosekit/web/menu';
import { createElement, forwardRef, useCallback, useRef, type ForwardedRef, type ForwardRefExoticComponent, type HTMLAttributes, type RefAttributes } from 'react';

/**
 * Props for the {@link MenuSubmenuTrigger} React component.
 *
 * @public
 */
export interface MenuSubmenuTriggerProps {}

function MenuSubmenuTriggerComponent(props: MenuSubmenuTriggerProps, forwardedRef: ForwardedRef<MenuSubmenuTriggerElement>) {
  registerMenuSubmenuTriggerElement();

  const elementRef = useRef<MenuSubmenuTriggerElement>(null);

  const { ...restProps } = props;

  const mergedRef = useCallback(
    (element: MenuSubmenuTriggerElement | null) => {
      elementRef.current = element;
      if (typeof forwardedRef === 'function') {
        forwardedRef(element);
      } else if (forwardedRef) {
        forwardedRef.current = element;
      }
    },
    [forwardedRef],
  );

  return createElement('prosekit-menu-submenu-trigger', { ...restProps, ref: mergedRef, suppressHydrationWarning: true });
}

/**
 * A React component that renders an `prosekit-menu-submenu-trigger` custom element.
 *
 * @public
 */
export const MenuSubmenuTrigger: ForwardRefExoticComponent<MenuSubmenuTriggerProps & HTMLAttributes<MenuSubmenuTriggerElement> & RefAttributes<MenuSubmenuTriggerElement>> = /* @__PURE__ */ forwardRef(MenuSubmenuTriggerComponent);
