/**
 * This file is auto-generated by the "@aria-ui/cli" tool. Do not edit this file directly.
 */

import {
  createElement,
  forwardRef,
  useCallback,
  useRef,
  type ForwardedRef,
  type ForwardRefExoticComponent,
  type HTMLAttributes,
  type RefAttributes,
  useLayoutEffect,
} from "react";
import {
  registerMenuItemElement,
  type MenuItemElement,
  type MenuItemProps as MenuItemElementProps,
} from "@prosekit/web/menu";

/**
 * Props for the {@link MenuItem} React component.
 *
 * @public
 */
export interface MenuItemProps extends HTMLAttributes<MenuItemElement> {
  /**
   * The unique value for this menu item.
   *
   * @default ""
   */
  value?: MenuItemElementProps["value"];
  /**
   * Whether this menu item is disabled.
   *
   * @default false
   */
  disabled?: MenuItemElementProps["disabled"];
}

function MenuItemComponent(
  props: MenuItemProps,
  forwardedRef: ForwardedRef<MenuItemElement>,
) {
  registerMenuItemElement();

  const elementRef = useRef<MenuItemElement>(null);

  const { disabled: p0, value: p1, ...restProps } = props;

  useLayoutEffect(() => {
    const element = elementRef.current as Record<string, unknown> | null;
    if (!element) return;
    Object.assign(element, { disabled: p0, value: p1 });
  });

  const mergedRef = useCallback((element: MenuItemElement | null) => {
    elementRef.current = element;
    if (typeof forwardedRef === "function") {
      forwardedRef(element);
    } else if (forwardedRef) {
      forwardedRef.current = element;
    }
  }, []);

  return createElement("prosekit-menu-item", {
    ...restProps,
    ref: mergedRef,
    suppressHydrationWarning: true,
  });
}

/**
 * A React component that renders an `prosekit-menu-item` custom element.
 *
 * @public
 */
export const MenuItem: ForwardRefExoticComponent<
  MenuItemProps & RefAttributes<MenuItemElement>
> = /* @__PURE__ */ forwardRef(MenuItemComponent);
