export { defineHeading, type HeadingExtension } from './heading'
export { defineHeadingCommands, type HeadingCommandsExtension } from './heading-commands'
export { defineHeadingInputRule } from './heading-input-rule'
export { defineHeadingKeymap } from './heading-keymap'
export { defineHeadingSpec, type HeadingSpecExtension } from './heading-spec'
export type { HeadingAttrs } from './heading-types'
