import fs from 'node:fs/promises'
import path from 'node:path'

import YAML from 'js-yaml'
import JSON5 from 'json5'

import { removePath, writeJson, writeText } from './file-utils'

/**
 * Virtual file with lazy read and staged mutations.
 */
export class VirtualFile {
  public distContent: string | null = null
  public content: string | null = null
  public deleted = false
  public updated = false

  constructor(
    private readonly rootDir: string,
    public readonly path: string,
  ) {}

  /**
   * Checks if the file is generated by convention.
   */
  get isGenerated(): boolean {
    return path.parse(this.path).name.endsWith('.gen')
  }

  /**
   * Lazily reads the file from disk.
   */
  async read(): Promise<string> {
    if (this.content === null) {
      this.distContent = await fs.readFile(this.getAbsPath(), 'utf8')
      this.content = this.distContent
    }
    if (this.content === null) {
      throw new Error(`Failed to read ${this.path}`)
    }
    return this.content
  }

  /**
   * Reads and parses the file as JSON.
   */
  async readJSON<T = unknown>(): Promise<T> {
    const text = await this.read()
    const parsed: unknown = JSON5.parse(text)
    return parsed as T
  }

  /**
   * Reads and parses the file as YAML.
   */
  async readYAML<T = unknown>(): Promise<T> {
    const text = await this.read()
    const parsed = YAML.load(text)
    return parsed as T
  }

  /**
   * Marks the file as deleted.
   */
  delete(): void {
    this.deleted = true
    this.updated = true
    this.content = null
  }

  /**
   * Replaces the cached content with raw text.
   */
  update(content: string): void {
    this.content = content
    this.deleted = false
    this.updated = true
  }

  /**
   * Serializes and stores JSON data.
   */
  updateJSON(json: unknown): void {
    this.update(JSON.stringify(json, null, 2) + '\n')
  }

  /**
   * Serializes and stores YAML data.
   */
  updateYAML(yaml: unknown, options?: YAML.DumpOptions): void {
    this.update(YAML.dump(yaml, options))
  }

  /**
   * Writes staged changes to disk.
   */
  async commit(): Promise<boolean> {
    const absPath = this.getAbsPath()

    if (this.deleted) {
      return await removePath(absPath)
    }
    if (!this.updated) {
      return false
    }
    if (this.content === null) {
      throw new Error(`Unable to write ${absPath}: no content provided`)
    }
    if (absPath.endsWith('.json')) {
      return await writeJson(absPath, JSON5.parse(this.content))
    }
    return await writeText(absPath, this.content)
  }

  /**
   * Resolves the absolute file path.
   */
  private getAbsPath() {
    return path.join(this.rootDir, this.path)
  }
}
