/**
 * This file is auto-generated by the "@aria-ui/cli" tool. Do not edit this file directly.
 */

import { ReactWrapper } from "@aria-ui-v2/integrations/react";
import {
  createElement,
  forwardRef,
  type ForwardedRef,
  type ForwardRefExoticComponent,
  type HTMLAttributes,
  type RefAttributes,
} from "react";
import {
  registerTableHandlePopoverPopupElement,
  type TableHandlePopoverPopupElement,
  type TableHandlePopoverPopupProps as TableHandlePopoverPopupElementProps,
} from "@prosekit/web/table-handle";

const propNames: string[] = ["eventTarget"];
const eventNameMap: Record<string, string> = {};

/**
 * Props for the {@link TableHandlePopoverPopup} React component.
 *
 * @public
 */
export interface TableHandlePopoverPopupProps extends HTMLAttributes<TableHandlePopoverPopupElement> {
  /**
   * By default, the popup element will listen for keydown events.
   * You can pass a different element to listen for keydown events.
   *
   * @default null
   */
  eventTarget?: TableHandlePopoverPopupElementProps["eventTarget"];
}

function TableHandlePopoverPopupComponent(
  props: TableHandlePopoverPopupProps,
  forwardedRef: ForwardedRef<TableHandlePopoverPopupElement>,
) {
  registerTableHandlePopoverPopupElement();
  return createElement(ReactWrapper, {
    as: "prosekit-table-handle-popover-popup",
    propNames,
    eventNameMap,
    props,
    forwardedRef,
  });
}

/**
 * A React component that renders an `prosekit-table-handle-popover-popup` custom element.
 *
 * @public
 */
export const TableHandlePopoverPopup: ForwardRefExoticComponent<
  TableHandlePopoverPopupProps & RefAttributes<TableHandlePopoverPopupElement>
> = /* @__PURE__ */ forwardRef(TableHandlePopoverPopupComponent);
