/**
 * This file is auto-generated by the "@aria-ui/cli" tool. Do not edit this file directly.
 */

import {
  registerTableHandlePopoverPopupElement,
  type TableHandlePopoverPopupElement,
  type TableHandlePopoverPopupProps as TableHandlePopoverPopupElementProps,
} from "@prosekit/web/table-handle";
import {
  createElement,
  forwardRef,
  useCallback,
  useRef,
  type ForwardedRef,
  type ForwardRefExoticComponent,
  type HTMLAttributes,
  type RefAttributes,
  useLayoutEffect,
} from "react";

/**
 * Props for the {@link TableHandlePopoverPopup} React component.
 *
 * @public
 */
export interface TableHandlePopoverPopupProps extends HTMLAttributes<TableHandlePopoverPopupElement> {
  /**
   * By default, the popup element will listen for keydown events.
   * You can pass a different element to listen for keydown events.
   *
   * @default null
   */
  eventTarget?: TableHandlePopoverPopupElementProps["eventTarget"];
}

function TableHandlePopoverPopupComponent(
  props: TableHandlePopoverPopupProps,
  forwardedRef: ForwardedRef<TableHandlePopoverPopupElement>,
) {
  registerTableHandlePopoverPopupElement();

  const elementRef = useRef<TableHandlePopoverPopupElement>(null);

  const { eventTarget: p0, ...restProps } = props;

  useLayoutEffect(() => {
    const element = elementRef.current as Record<string, unknown> | null;
    if (!element) return;
    Object.assign(element, { eventTarget: p0 });
  });

  const mergedRef = useCallback(
    (element: TableHandlePopoverPopupElement | null) => {
      elementRef.current = element;
      if (typeof forwardedRef === "function") {
        forwardedRef(element);
      } else if (forwardedRef) {
        forwardedRef.current = element;
      }
    },
    [],
  );

  return createElement("prosekit-table-handle-popover-popup", {
    ...restProps,
    ref: mergedRef,
    suppressHydrationWarning: true,
  });
}

/**
 * A React component that renders an `prosekit-table-handle-popover-popup` custom element.
 *
 * @public
 */
export const TableHandlePopoverPopup: ForwardRefExoticComponent<
  TableHandlePopoverPopupProps & RefAttributes<TableHandlePopoverPopupElement>
> = /* @__PURE__ */ forwardRef(TableHandlePopoverPopupComponent);
