/**
 * This file is auto-generated by the "@aria-ui/cli" tool. Do not edit this file directly.
 */

import { ReactWrapper } from "@aria-ui-v2/integrations/react";
import {
  createElement,
  forwardRef,
  type ForwardedRef,
  type ForwardRefExoticComponent,
  type HTMLAttributes,
  type RefAttributes,
} from "react";
import {
  registerTableHandleDropIndicatorElement,
  type TableHandleDropIndicatorElement,
  type TableHandleDropIndicatorProps as TableHandleDropIndicatorElementProps,
} from "@prosekit/web/table-handle";
import { useEditorContext } from "../../contexts/editor-context.ts";

const propNames: string[] = ["editor"];
const eventNameMap: Record<string, string> = {};

/**
 * Props for the {@link TableHandleDropIndicator} React component.
 *
 * @public
 */
export interface TableHandleDropIndicatorProps extends HTMLAttributes<TableHandleDropIndicatorElement> {
  /**
   * @default null
   * @hidden
   */
  editor?: TableHandleDropIndicatorElementProps["editor"];
}

function TableHandleDropIndicatorComponent(
  props: TableHandleDropIndicatorProps,
  forwardedRef: ForwardedRef<TableHandleDropIndicatorElement>,
) {
  registerTableHandleDropIndicatorElement();
  const componentProps: TableHandleDropIndicatorProps = { ...props };
  const editorContext = useEditorContext();
  if (componentProps.editor == null && editorContext != null) {
    componentProps.editor = editorContext;
  }

  return createElement(ReactWrapper, {
    as: "prosekit-table-handle-drop-indicator",
    propNames,
    eventNameMap,
    props: componentProps,
    forwardedRef,
  });
}

/**
 * A React component that renders an `prosekit-table-handle-drop-indicator` custom element.
 *
 * @public
 */
export const TableHandleDropIndicator: ForwardRefExoticComponent<
  TableHandleDropIndicatorProps & RefAttributes<TableHandleDropIndicatorElement>
> = /* @__PURE__ */ forwardRef(TableHandleDropIndicatorComponent);
