/**
 * This file is auto-generated by the "@aria-ui/cli" tool. Do not edit this file directly.
 */

import {
  createElement,
  forwardRef,
  useCallback,
  useRef,
  type ForwardedRef,
  type ForwardRefExoticComponent,
  type HTMLAttributes,
  type RefAttributes,
  useLayoutEffect,
} from "react";
import {
  registerTableHandleRowTriggerElement,
  type TableHandleRowTriggerElement,
  type TableHandleRowTriggerProps as TableHandleRowTriggerElementProps,
} from "@prosekit/web/table-handle";
import { useEditorContext } from "../../contexts/editor-context.ts";

/**
 * Props for the {@link TableHandleRowTrigger} React component.
 *
 * @public
 */
export interface TableHandleRowTriggerProps extends HTMLAttributes<TableHandleRowTriggerElement> {
  /**
   * @default null
   * @hidden
   */
  editor?: TableHandleRowTriggerElementProps["editor"];
}

function TableHandleRowTriggerComponent(
  props: TableHandleRowTriggerProps,
  forwardedRef: ForwardedRef<TableHandleRowTriggerElement>,
) {
  registerTableHandleRowTriggerElement();

  const elementRef = useRef<TableHandleRowTriggerElement>(null);

  const p0Fallback = useEditorContext();

  const { editor: p0, ...restProps } = props;

  useLayoutEffect(() => {
    const element = elementRef.current as Record<string, unknown> | null;
    if (!element) return;
    Object.assign(element, { editor: p0 ?? p0Fallback });
  });

  const mergedRef = useCallback(
    (element: TableHandleRowTriggerElement | null) => {
      elementRef.current = element;
      if (typeof forwardedRef === "function") {
        forwardedRef(element);
      } else if (forwardedRef) {
        forwardedRef.current = element;
      }
    },
    [forwardedRef],
  );

  return createElement("prosekit-table-handle-row-trigger", {
    ...restProps,
    ref: mergedRef,
    suppressHydrationWarning: true,
  });
}

/**
 * A React component that renders an `prosekit-table-handle-row-trigger` custom element.
 *
 * @public
 */
export const TableHandleRowTrigger: ForwardRefExoticComponent<
  TableHandleRowTriggerProps & RefAttributes<TableHandleRowTriggerElement>
> = /* @__PURE__ */ forwardRef(TableHandleRowTriggerComponent);
