// This file is auto-generated by "@aria-ui/cli". Do not edit this file directly.

import { registerMenuRootElement, type MenuRootElement, type MenuRootEvents, type MenuRootProps as MenuRootElementProps } from '@prosekit/web/menu';
import { createEffect, createSignal, mergeProps, splitProps } from 'solid-js';
import type { Component, JSX } from 'solid-js';
import h from 'solid-js/h';

/** Props for the {@link MenuRoot} Solid component. */
export interface MenuRootProps {
  /**
   * Whether the overlay is initially open.
   * @default false
   */
  defaultOpen?: MenuRootElementProps['defaultOpen'];
  /**
   * Whether the overlay is currently open.
   * @default null
   */
  open?: MenuRootElementProps['open'];
  /**
   * Whether the component should ignore user interaction.
   * @default false
   */
  disabled?: MenuRootElementProps['disabled'];
  /** Emitted when the menu is opened or closed. */
  onOpenChange?: (event: MenuRootEvents['openChange']) => void;
}

/** A Solid component that renders an `prosekit-menu-root` custom element. */
export const MenuRoot: Component<MenuRootProps & JSX.HTMLAttributes<MenuRootElement>> = (props): any => {
  registerMenuRootElement();

  const [getElement, setElement] = createSignal<MenuRootElement | null>(null);
  const handlers: Array<((event: any) => void) | undefined> = [];

  const [elementProps, eventHandlers, restProps] = splitProps(props, ['defaultOpen', 'disabled', 'open'], ['onOpenChange']);

  createEffect(() => {
    const element = getElement();
    if (!element) return;

    Object.assign(element, { defaultOpen: elementProps.defaultOpen, disabled: elementProps.disabled, open: elementProps.open });

    handlers.length = 0;
    handlers.push(eventHandlers.onOpenChange);
  });

  createEffect(() => {
    const element = getElement();
    if (!element) return;

    const ac = new AbortController();
    for (const [index, eventName] of ['openChange'].entries()) {
      element.addEventListener(
        eventName,
        (event) => {
          handlers[index]?.(event);
        },
        { signal: ac.signal },
      );
    }
    return () => ac.abort();
  });

  return () =>
    h(
      'prosekit-menu-root',
      mergeProps(restProps, {
        ref: (el: MenuRootElement | null) => {
          setElement(el);
        },
      }),
    );
};
