/**
 * This file is auto-generated by the "@aria-ui/cli" tool. Do not edit this file directly.
 */

import { registerMenuSubmenuTriggerElement, type MenuSubmenuTriggerElement } from '@prosekit/web/menu';
import type { Component, JSX } from 'solid-js';
import h from 'solid-js/h';

/**
 * Props for the {@link MenuSubmenuTrigger} Solid component.
 *
 * @public
 */
export interface MenuSubmenuTriggerProps extends JSX.HTMLAttributes<MenuSubmenuTriggerElement> {}

/**
 * A Solid component that renders an `prosekit-menu-submenu-trigger` custom element.
 *
 * @public
 */
export const MenuSubmenuTrigger: Component<MenuSubmenuTriggerProps> = (props): any => {
  registerMenuSubmenuTriggerElement();

  const restProps = props;

  return () => h('prosekit-menu-submenu-trigger', restProps);
};
