/**
 * This file is auto-generated by the "@aria-ui/cli" tool. Do not edit this file directly.
 */

import { registerMenuSubmenuRootElement, type MenuSubmenuRootElement } from '@prosekit/web/menu';
import type { Component, JSX } from 'solid-js';
import h from 'solid-js/h';

/**
 * Props for the {@link MenuSubmenuRoot} Solid component.
 *
 * @public
 */
export interface MenuSubmenuRootProps extends JSX.HTMLAttributes<MenuSubmenuRootElement> {}

/**
 * A Solid component that renders an `prosekit-menu-submenu-root` custom element.
 *
 * @public
 */
export const MenuSubmenuRoot: Component<MenuSubmenuRootProps> = (props): any => {
  registerMenuSubmenuRootElement();

  const restProps = props;

  return () => h('prosekit-menu-submenu-root', restProps);
};
