// This file is auto-generated by "@aria-ui/cli". Do not edit this file directly.

import { registerMenuSubmenuTriggerElement, type MenuSubmenuTriggerElement, type MenuSubmenuTriggerProps as MenuSubmenuTriggerElementProps } from '@prosekit/web/menu';
import { createEffect, createSignal, mergeProps, splitProps } from 'solid-js';
import type { Component, JSX } from 'solid-js';
import h from 'solid-js/h';

/** Props for the {@link MenuSubmenuTrigger} Solid component. */
export interface MenuSubmenuTriggerProps {
  /**
   * The unique value for this submenu trigger in the parent menu.
   *
   * @default ""
   */
  value?: MenuSubmenuTriggerElementProps['value'];
  /**
   * Whether this submenu trigger is disabled.
   *
   * @default false
   */
  disabled?: MenuSubmenuTriggerElementProps['disabled'];
}

/** A Solid component that renders an `prosekit-menu-submenu-trigger` custom element. */
export const MenuSubmenuTrigger: Component<MenuSubmenuTriggerProps & JSX.HTMLAttributes<MenuSubmenuTriggerElement>> = (props): any => {
  registerMenuSubmenuTriggerElement();

  const [getElement, setElement] = createSignal<MenuSubmenuTriggerElement | null>(null);

  const [elementProps, restProps] = splitProps(props, ['disabled', 'value']);

  createEffect(() => {
    const element = getElement();
    if (!element) return;

    Object.assign(element, { disabled: elementProps.disabled, value: elementProps.value });
  });

  return () =>
    h(
      'prosekit-menu-submenu-trigger',
      mergeProps(restProps, {
        ref: (el: MenuSubmenuTriggerElement | null) => {
          setElement(el);
        },
      }),
    );
};
