/**
 * This file is auto-generated by the "@aria-ui/cli" tool. Do not edit this file directly.
 */

import { registerMenuItemElement, type MenuItemElement, type MenuItemEvents, type MenuItemProps as MenuItemElementProps } from '@prosekit/web/menu';
import { createEffect, createSignal, mergeProps, splitProps } from 'solid-js';
import type { Component, JSX } from 'solid-js';
import h from 'solid-js/h';

/**
 * Props for the {@link MenuItem} Solid component.
 *
 * @public
 */
export interface MenuItemProps {
  /**
   * The unique value for this menu item.
   *
   * @default ""
   */
  value?: MenuItemElementProps['value'];
  /**
   * Whether this menu item is disabled.
   *
   * @default false
   */
  disabled?: MenuItemElementProps['disabled'];
  /**
   * Whether to close the menu when the item is pressed.
   *
   * @default true
   */
  closeOnSelect?: MenuItemElementProps['closeOnSelect'];
  /** Emitted when the the item is selected. */
  onSelect?: (event: MenuItemEvents['select']) => void;
}

/**
 * A Solid component that renders an `prosekit-menu-item` custom element.
 *
 * @public
 */
export const MenuItem: Component<MenuItemProps & JSX.HTMLAttributes<MenuItemElement>> = (props): any => {
  registerMenuItemElement();

  const [getElement, setElement] = createSignal<MenuItemElement | null>(null);
  const handlers: Array<((event: any) => void) | undefined> = [];

  const [elementProps, eventHandlers, restProps] = splitProps(props, ['closeOnSelect', 'disabled', 'value'], ['onSelect']);

  createEffect(() => {
    const element = getElement();
    if (!element) return;

    Object.assign(element, { closeOnSelect: elementProps.closeOnSelect, disabled: elementProps.disabled, value: elementProps.value });

    handlers.length = 0;
    handlers.push(eventHandlers.onSelect);
  });

  createEffect(() => {
    const element = getElement();
    if (!element) return;

    const ac = new AbortController();
    for (const [index, eventName] of ['select'].entries()) {
      element.addEventListener(
        eventName,
        (event) => {
          handlers[index]?.(event);
        },
        { signal: ac.signal },
      );
    }
    return () => ac.abort();
  });

  return () =>
    h(
      'prosekit-menu-item',
      mergeProps(restProps, {
        ref: (el: MenuItemElement | null) => {
          setElement(el);
        },
      }),
    );
};
