/**
 * This file is auto-generated by the "@aria-ui/cli" tool. Do not edit this file directly.
 */

import { registerMenuTriggerElement, type MenuTriggerElement, type MenuTriggerEvents, type MenuTriggerProps as MenuTriggerElementProps } from '@prosekit/web/menu';
import { createEffect, createSignal, mergeProps, splitProps } from 'solid-js';
import type { Component, JSX } from 'solid-js';
import h from 'solid-js/h';

/**
 * Props for the {@link MenuTrigger} Solid component.
 *
 * @public
 */
export interface MenuTriggerProps extends JSX.HTMLAttributes<MenuTriggerElement> {
  /**
   * Whether the component should ignore user interaction.
   *
   * @default false
   */
  disabled?: MenuTriggerElementProps['disabled'];
  /** Emitted when the menu is opened or closed. */
  onOpenChange?: (event: MenuTriggerEvents['openChange']) => void;
}

/**
 * A Solid component that renders an `prosekit-menu-trigger` custom element.
 *
 * @public
 */
export const MenuTrigger: Component<MenuTriggerProps> = (props): any => {
  registerMenuTriggerElement();

  const [getElement, setElement] = createSignal<MenuTriggerElement | null>(null);
  const handlers: Array<((event: any) => void) | undefined> = [];

  const [elementProps, eventHandlers, restProps] = splitProps(props, ['disabled'], ['onOpenChange']);

  createEffect(() => {
    const element = getElement();
    if (!element) return;

    Object.assign(element, { disabled: elementProps.disabled });

    handlers.length = 0;
    handlers.push(eventHandlers.onOpenChange);
  });

  createEffect(() => {
    const element = getElement();
    if (!element) return;

    const ac = new AbortController();
    for (const [index, eventName] of ['openChange'].entries()) {
      element.addEventListener(
        eventName,
        (event) => {
          handlers[index]?.(event);
        },
        { signal: ac.signal },
      );
    }
    return () => ac.abort();
  });

  return () =>
    h(
      'prosekit-menu-trigger',
      mergeProps(restProps, {
        ref: (el: MenuTriggerElement | null) => {
          setElement(el);
        },
      }),
    );
};

export type { MenuTriggerEvents };
