<script lang="ts">
  // This file is auto-generated by "@aria-ui/cli". Do not edit this file directly.
  import { registerMenuSubmenuTriggerElement } from '@prosekit/web/menu'
  import type { MenuSubmenuTriggerElement } from '@prosekit/web/menu'
  registerMenuSubmenuTriggerElement()

  let { disabled: p0, value: p1, children = undefined, ...restProps } = $props()
  let element: MenuSubmenuTriggerElement | undefined

  $effect(() => {
    if (!element) return

    Object.assign(element, { disabled: p0, value: p1 })
  })
</script>

<prosekit-menu-submenu-trigger {...restProps} bind:this={element}>{@render children?.()}</prosekit-menu-submenu-trigger>
