<!-- This file is auto-generated by the "@aria-ui/cli" tool. Do not edit this file directly. -->

<script lang="js">
  import { registerMenuPopupElement } from '@prosekit/web/menu'
  registerMenuPopupElement()

  let { eventTarget: p0, children = undefined, ...restProps } = $props()
  let element

  $effect(() => {
    if (!element) return

    Object.assign(element, { eventTarget: p0 })
  })
</script>

<prosekit-menu-popup {...restProps} bind:this={element}>{@render children?.()}</prosekit-menu-popup>
