// This file is auto-generated by "@aria-ui/cli". Do not edit this file directly.

import type { MenuPopupElement, MenuPopupProps as MenuPopupElementProps } from '@prosekit/web/menu';
import type { Component, Snippet } from 'svelte';
import type { HTMLAttributes } from 'svelte/elements';

import MenuPopupComponent from './menu-popup.gen.svelte';

/**
 * Props for the {@link MenuPopup} Svelte component.
 *
 * @public
 */
export interface MenuPopupProps {
  /**
   * By default, the MenuPopup element will listen for keydown events.
   * You can pass a different element to listen for keydown events.
   *
   * @default null
   */
  eventTarget?: MenuPopupElementProps['eventTarget'];
  children?: Snippet;
}

/**
 * A Svelte component that renders an `prosekit-menu-popup` custom element.
 *
 * @public
 */
export const MenuPopup: Component<MenuPopupProps & HTMLAttributes<MenuPopupElement>> = MenuPopupComponent as Component<MenuPopupProps & HTMLAttributes<MenuPopupElement>>;
