<!-- This file is auto-generated by the "@aria-ui/cli" tool. Do not edit this file directly. -->

<script lang="ts">
  import { registerMenuTriggerElement } from '@prosekit/web/menu'
  import type { MenuTriggerElement } from '@prosekit/web/menu'
  registerMenuTriggerElement()

  let { disabled: p0, onOpenChange: e0, children = undefined, ...restProps } = $props()
  let element: MenuTriggerElement | undefined
  const handlers: EventListener[] = []

  $effect(() => {
    if (!element) return

    Object.assign(element, { disabled: p0 })

    handlers.length = 0
    handlers.push(e0)
  })

  $effect(() => {
    if (!element) return

    const ac = new AbortController()
    for (const [index, eventName] of ["openChange"].entries()) {
      element.addEventListener(eventName, (event) => handlers[index]?.(event), { signal: ac.signal })
    }
    return () => ac.abort()
  })
</script>

<prosekit-menu-trigger {...restProps} bind:this={element}>{@render children?.()}</prosekit-menu-trigger>
