// This file is auto-generated by "@aria-ui/cli". Do not edit this file directly.

import type { MenuSubmenuRootElement } from '@prosekit/web/menu';
import type { Component, Snippet } from 'svelte';
import type { HTMLAttributes } from 'svelte/elements';

import MenuSubmenuRootComponent from './menu-submenu-root.gen.svelte';

/** Props for the {@link MenuSubmenuRoot} Svelte component. */
export interface MenuSubmenuRootProps {
  children?: Snippet;
}

/** A Svelte component that renders an `prosekit-menu-submenu-root` custom element. */
export const MenuSubmenuRoot: Component<MenuSubmenuRootProps & HTMLAttributes<MenuSubmenuRootElement>> = MenuSubmenuRootComponent as Component<MenuSubmenuRootProps & HTMLAttributes<MenuSubmenuRootElement>>;
