<!-- This file is auto-generated by the "@aria-ui/cli" tool. Do not edit this file directly. -->

<script lang="js">
  import { registerMenuItemElement } from '@prosekit/web/menu'
  registerMenuItemElement()

  let { disabled: p0, value: p1, onSelect: e0, children = undefined, ...restProps } = $props()
  let element
  const handlers = []

  $effect(() => {
    if (!element) return

    Object.assign(element, { disabled: p0, value: p1 })

    handlers.length = 0
    handlers.push(e0)
  })

  $effect(() => {
    if (!element) return

    const ac = new AbortController()
    for (const [index, eventName] of ["select"].entries()) {
      element.addEventListener(eventName, (event) => handlers[index]?.(event), { signal: ac.signal })
    }
    return () => ac.abort()
  })
</script>

<prosekit-menu-item {...restProps} bind:this={element}>{@render children?.()}</prosekit-menu-item>
