// This file is auto-generated by "@aria-ui/cli". Do not edit this file directly.

import type { MenuSubmenuTriggerElement, MenuSubmenuTriggerProps as MenuSubmenuTriggerElementProps } from '@prosekit/web/menu';
import type { Component, Snippet } from 'svelte';
import type { HTMLAttributes } from 'svelte/elements';

import MenuSubmenuTriggerComponent from './menu-submenu-trigger.gen.svelte';

/** Props for the {@link MenuSubmenuTrigger} Svelte component. */
export interface MenuSubmenuTriggerProps {
  /**
   * The unique value for this submenu trigger in the parent menu.
   *
   * @default ""
   */
  value?: MenuSubmenuTriggerElementProps['value'];
  /**
   * Whether this submenu trigger is disabled.
   *
   * @default false
   */
  disabled?: MenuSubmenuTriggerElementProps['disabled'];
  children?: Snippet;
}

/** A Svelte component that renders an `prosekit-menu-submenu-trigger` custom element. */
export const MenuSubmenuTrigger: Component<MenuSubmenuTriggerProps & HTMLAttributes<MenuSubmenuTriggerElement>> = MenuSubmenuTriggerComponent as Component<MenuSubmenuTriggerProps & HTMLAttributes<MenuSubmenuTriggerElement>>;
