/**
 * This file is auto-generated by the "@aria-ui/cli" tool. Do not edit this file directly.
 */

import MenuItemComponent from "./menu-item.gen.svelte";
import {
  type MenuItemEvents,
  type MenuItemProps as MenuItemElementProps,
} from "@prosekit/web/menu";
import type { Component, Snippet } from "svelte";

/**
 * Props for the {@link MenuItem} Svelte component.
 *
 * @public
 */
export interface MenuItemProps {
  /**
   * The unique value for this menu item.
   *
   * @default ""
   */
  value?: MenuItemElementProps["value"];
  /**
   * Whether this menu item is disabled.
   *
   * @default false
   */
  disabled?: MenuItemElementProps["disabled"];
  /** Fired when the item is selected. */
  onSelect?: (event: MenuItemEvents["select"]) => void;
  children?: Snippet;
  [key: string]: unknown;
}

/**
 * A Svelte component that renders an `prosekit-menu-item` custom element.
 *
 * @public
 */
export const MenuItem: Component<MenuItemProps> =
  MenuItemComponent as unknown as Component<MenuItemProps>;

export type { MenuItemEvents };
export { MenuItemSelectEvent } from "@prosekit/web/menu";
