<!-- This file is auto-generated by the "@aria-ui/cli" tool. Do not edit this file directly. -->

<script lang="ts">
  import { registerMenuSubmenuRootElement } from '@prosekit/web/menu'
  registerMenuSubmenuRootElement()

  let { children = undefined, ...restProps } = $props()
</script>

<prosekit-menu-submenu-root {...restProps}>{@render children?.()}</prosekit-menu-submenu-root>
