<script lang="ts">
  // This file is auto-generated by "@aria-ui/cli". Do not edit this file directly.
  import { registerMenuPopupElement } from '@prosekit/web/menu'
  import type { MenuPopupElement } from '@prosekit/web/menu'
  registerMenuPopupElement()

  let { eventTarget: p0, children = undefined, ...restProps } = $props()
  let element: MenuPopupElement | undefined

  $effect(() => {
    if (!element) return

    Object.assign(element, { eventTarget: p0 })
  })
</script>

<prosekit-menu-popup {...restProps} bind:this={element}>{@render children?.()}</prosekit-menu-popup>
