<!-- This file is auto-generated by the "@aria-ui/cli" tool. Do not edit this file directly. -->

<script lang="ts">
  import { registerMenuItemElement } from '@prosekit/web/menu'
  import type { MenuItemElement } from '@prosekit/web/menu'
  registerMenuItemElement()

  let { closeOnSelect: p0, disabled: p1, value: p2, onSelect: e0, children = undefined, ...restProps } = $props()
  let element: MenuItemElement | undefined
  const handlers: EventListener[] = []

  $effect(() => {
    if (!element) return

    Object.assign(element, { closeOnSelect: p0, disabled: p1, value: p2 })

    handlers.length = 0
    handlers.push(e0)
  })

  $effect(() => {
    if (!element) return

    const ac = new AbortController()
    for (const [index, eventName] of ["select"].entries()) {
      element.addEventListener(eventName, (event) => handlers[index]?.(event), { signal: ac.signal })
    }
    return () => ac.abort()
  })
</script>

<prosekit-menu-item {...restProps} bind:this={element}>{@render children?.()}</prosekit-menu-item>
