<script lang="ts">
  // This file is auto-generated by "@aria-ui/cli". Do not edit this file directly.
  import { registerMenuRootElement } from '@prosekit/web/menu'
  import type { MenuRootElement } from '@prosekit/web/menu'
  registerMenuRootElement()

  let { defaultOpen: p0, disabled: p1, open: p2, onOpenChange: e0, children = undefined, ...restProps } = $props()
  let element: MenuRootElement | undefined
  const handlers: EventListener[] = []

  $effect(() => {
    if (!element) return

    Object.assign(element, { defaultOpen: p0, disabled: p1, open: p2 })

    handlers.length = 0
    handlers.push(e0)
  })

  $effect(() => {
    if (!element) return

    const ac = new AbortController()
    for (const [index, eventName] of ["openChange"].entries()) {
      element.addEventListener(eventName, (event) => handlers[index]?.(event), { signal: ac.signal })
    }
    return () => ac.abort()
  })
</script>

<prosekit-menu-root {...restProps} bind:this={element}>{@render children?.()}</prosekit-menu-root>
