// This file is auto-generated by "@aria-ui/cli". Do not edit this file directly.

import type { MenuRootElement, MenuRootEvents } from '@prosekit/web/menu';
import type { Component, Snippet } from 'svelte';
import type { HTMLAttributes } from 'svelte/elements';

import MenuRootComponent from './menu-root.gen.svelte';

/**
 * Props for the {@link MenuRoot} Svelte component.
 *
 * @public
 */
export interface MenuRootProps {
  /** Emitted when the menu is opened or closed. */
  onOpenChange?: (event: MenuRootEvents['openChange']) => void;
  children?: Snippet;
}

/**
 * A Svelte component that renders an `prosekit-menu-root` custom element.
 *
 * @public
 */
export const MenuRoot: Component<MenuRootProps & HTMLAttributes<MenuRootElement>> = MenuRootComponent as Component<MenuRootProps & HTMLAttributes<MenuRootElement>>;
