/**
 * This file is auto-generated by the "@aria-ui/cli" tool. Do not edit this file directly.
 */

import {
  registerDropIndicatorElement,
  type DropIndicatorElement,
  type DropIndicatorProps as DropIndicatorElementProps,
} from "@prosekit/web/drop-indicator";
import { mergeProps, splitProps } from "solid-js";
import type { Component, JSX } from "solid-js";
import h from "solid-js/h";
import { useEditorContext } from "../../contexts/editor-context.ts";

/**
 * Props for the {@link DropIndicator} Solid component.
 *
 * @public
 */
export interface DropIndicatorProps extends JSX.HTMLAttributes<DropIndicatorElement> {
  /**
   * The ProseKit editor instance.
   *
   * @default null
   * @hidden
   */
  editor?: DropIndicatorElementProps["editor"];
  /**
   * The line width in pixels.
   *
   * @default 2
   */
  width?: DropIndicatorElementProps["width"];
}

/**
 * A Solid component that renders an `prosekit-drop-indicator` custom element.
 *
 * @public
 */
export const DropIndicator: Component<DropIndicatorProps> = (props): any => {
  registerDropIndicatorElement();

  const [elementProps, restProps] = splitProps(props, ["editor", "width"]);

  const editorContext = useEditorContext();

  return h(
    "prosekit-drop-indicator",
    mergeProps(restProps, {
      "prop:editor": () => elementProps.editor ?? editorContext,
      "prop:width": () => elementProps.width,
    }),
  );
};
