/**
 * This file is auto-generated by the "@aria-ui/cli" tool. Do not edit this file directly.
 */

import {
  registerTableHandleRowTriggerElement,
  type TableHandleRowTriggerElement,
  type TableHandleRowTriggerProps as TableHandleRowTriggerElementProps,
} from "@prosekit/web/table-handle";
import { mergeProps, splitProps } from "solid-js";
import type { Component, JSX } from "solid-js";
import h from "solid-js/h";
import { useEditorContext } from "../../contexts/editor-context.ts";

/**
 * Props for the {@link TableHandleRowTrigger} Solid component.
 *
 * @public
 */
export interface TableHandleRowTriggerProps extends JSX.HTMLAttributes<TableHandleRowTriggerElement> {
  /**
   * @default null
   * @hidden
   */
  editor?: TableHandleRowTriggerElementProps["editor"];
}

/**
 * A Solid component that renders an `prosekit-table-handle-row-trigger` custom element.
 *
 * @public
 */
export const TableHandleRowTrigger: Component<TableHandleRowTriggerProps> = (
  props,
): any => {
  registerTableHandleRowTriggerElement();

  const [elementProps, restProps] = splitProps(props, ["editor"]);

  const editorContext = useEditorContext();

  return h(
    "prosekit-table-handle-row-trigger",
    mergeProps(restProps, {
      "prop:editor": () => elementProps.editor ?? editorContext,
    }),
  );
};
