/**
 * This file is auto-generated by the "@aria-ui/cli" tool. Do not edit this file directly.
 */

import {
  registerTableHandlePopoverItemElement,
  type TableHandlePopoverItemElement,
  type TableHandlePopoverItemEvents,
  type TableHandlePopoverItemProps as TableHandlePopoverItemElementProps,
} from "@prosekit/web/table-handle";
import { mergeProps, splitProps } from "solid-js";
import type { Component, JSX } from "solid-js";
import h from "solid-js/h";

/**
 * Props for the {@link TableHandlePopoverItem} Solid component.
 *
 * @public
 */
export interface TableHandlePopoverItemProps extends JSX.HTMLAttributes<TableHandlePopoverItemElement> {
  /** @default "" */
  value?: TableHandlePopoverItemElementProps["value"];
  /** @default false */
  disabled?: TableHandlePopoverItemElementProps["disabled"];
  /** */
  onItemSelect?: (event: TableHandlePopoverItemEvents["itemSelect"]) => void;
}

/**
 * A Solid component that renders an `prosekit-table-handle-popover-item` custom element.
 *
 * @public
 */
export const TableHandlePopoverItem: Component<TableHandlePopoverItemProps> = (
  props,
): any => {
  registerTableHandlePopoverItemElement();

  const [elementProps, eventHandlers, restProps] = splitProps(
    props,
    ["disabled", "value"],
    ["onItemSelect"],
  );

  return h(
    "prosekit-table-handle-popover-item",
    mergeProps(restProps, {
      "prop:disabled": () => elementProps.disabled,
      "prop:value": () => elementProps.value,
      "on:itemSelect": (event: TableHandlePopoverItemEvents["itemSelect"]) =>
        eventHandlers.onItemSelect?.(event),
    }),
  );
};

export type { TableHandlePopoverItemEvents };
export { TableHandlePopoverItemSelectEvent } from "@prosekit/web/table-handle";
