// This file is auto-generated by "@aria-ui/cli". Do not edit this file directly.

import { registerTableHandleRowMenuTriggerElement, type TableHandleRowMenuTriggerElement, type TableHandleRowMenuTriggerProps as TableHandleRowMenuTriggerElementProps } from '@prosekit/web/table-handle';
import { createEffect, createSignal, mergeProps, splitProps } from 'solid-js';
import type { Component, JSX } from 'solid-js';
import h from 'solid-js/h';

import { useEditorContext } from '../../contexts/editor-context.ts';

/**
 * Props for the {@link TableHandleRowMenuTrigger} Solid component.
 *
 * @public
 */
export interface TableHandleRowMenuTriggerProps {
  /**
   * @default null
   * @hidden
   */
  editor?: TableHandleRowMenuTriggerElementProps['editor'];
}

/**
 * A Solid component that renders an `prosekit-table-handle-row-menu-trigger` custom element.
 *
 * @public
 */
export const TableHandleRowMenuTrigger: Component<TableHandleRowMenuTriggerProps & JSX.HTMLAttributes<TableHandleRowMenuTriggerElement>> = (props): any => {
  registerTableHandleRowMenuTriggerElement();

  const [getElement, setElement] = createSignal<TableHandleRowMenuTriggerElement | null>(null);

  const [elementProps, restProps] = splitProps(props, ['editor']);

  const p0Fallback = useEditorContext();

  createEffect(() => {
    const element = getElement();
    if (!element) return;

    Object.assign(element, { editor: elementProps.editor ?? p0Fallback });
  });

  return () =>
    h(
      'prosekit-table-handle-row-menu-trigger',
      mergeProps(restProps, {
        ref: (el: TableHandleRowMenuTriggerElement | null) => {
          setElement(el);
        },
      }),
    );
};
