// This file is auto-generated by "@aria-ui/cli". Do not edit this file directly.

import { registerTableHandleColumnMenuRootElement, type TableHandleColumnMenuRootElement, type TableHandleColumnMenuRootProps as TableHandleColumnMenuRootElementProps } from '@prosekit/web/table-handle';
import { createEffect, createSignal, mergeProps, splitProps } from 'solid-js';
import type { Component, JSX } from 'solid-js';
import h from 'solid-js/h';

/** Props for the {@link TableHandleColumnMenuRoot} Solid component. */
export interface TableHandleColumnMenuRootProps {
  /**
   * Whether the overlay is initially open.
   * @default false
   */
  defaultOpen?: TableHandleColumnMenuRootElementProps['defaultOpen'];
  /**
   * Whether the overlay is currently open.
   * @default null
   */
  open?: TableHandleColumnMenuRootElementProps['open'];
  /**
   * Whether the component should ignore user interaction.
   * @default false
   */
  disabled?: TableHandleColumnMenuRootElementProps['disabled'];
}

/** A Solid component that renders an `prosekit-table-handle-column-menu-root` custom element. */
export const TableHandleColumnMenuRoot: Component<TableHandleColumnMenuRootProps & JSX.HTMLAttributes<TableHandleColumnMenuRootElement>> = (props): any => {
  registerTableHandleColumnMenuRootElement();

  const [getElement, setElement] = createSignal<TableHandleColumnMenuRootElement | null>(null);

  const [elementProps, restProps] = splitProps(props, ['defaultOpen', 'disabled', 'open']);

  createEffect(() => {
    const element = getElement();
    if (!element) return;

    Object.assign(element, { defaultOpen: elementProps.defaultOpen, disabled: elementProps.disabled, open: elementProps.open });
  });

  return () =>
    h(
      'prosekit-table-handle-column-menu-root',
      mergeProps(restProps, {
        ref: (el: TableHandleColumnMenuRootElement | null) => {
          setElement(el);
        },
      }),
    );
};
