// This file is auto-generated by "@aria-ui/cli". Do not edit this file directly.

import { registerTableHandleColumnMenuTriggerElement, type TableHandleColumnMenuTriggerElement, type TableHandleColumnMenuTriggerProps as TableHandleColumnMenuTriggerElementProps } from '@prosekit/web/table-handle';
import { createEffect, createSignal, mergeProps, splitProps } from 'solid-js';
import type { Component, JSX } from 'solid-js';
import h from 'solid-js/h';

import { useEditorContext } from '../../contexts/editor-context.ts';

/**
 * Props for the {@link TableHandleColumnMenuTrigger} Solid component.
 *
 * @public
 */
export interface TableHandleColumnMenuTriggerProps {
  /**
   * @default null
   * @hidden
   */
  editor?: TableHandleColumnMenuTriggerElementProps['editor'];
}

/**
 * A Solid component that renders an `prosekit-table-handle-column-menu-trigger` custom element.
 *
 * @public
 */
export const TableHandleColumnMenuTrigger: Component<TableHandleColumnMenuTriggerProps & JSX.HTMLAttributes<TableHandleColumnMenuTriggerElement>> = (props): any => {
  registerTableHandleColumnMenuTriggerElement();

  const [getElement, setElement] = createSignal<TableHandleColumnMenuTriggerElement | null>(null);

  const [elementProps, restProps] = splitProps(props, ['editor']);

  const p0Fallback = useEditorContext();

  createEffect(() => {
    const element = getElement();
    if (!element) return;

    Object.assign(element, { editor: elementProps.editor ?? p0Fallback });
  });

  return () =>
    h(
      'prosekit-table-handle-column-menu-trigger',
      mergeProps(restProps, {
        ref: (el: TableHandleColumnMenuTriggerElement | null) => {
          setElement(el);
        },
      }),
    );
};
