/**
 * This file is auto-generated by the "@aria-ui/cli" tool. Do not edit this file directly.
 */

import {
  registerTableHandleRootElement,
  type TableHandleRootElement,
  type TableHandleRootProps as TableHandleRootElementProps,
} from "@prosekit/web/table-handle";
import { mergeProps, splitProps } from "solid-js";
import type { Component, JSX } from "solid-js";
import h from "solid-js/h";
import { useEditorContext } from "../../contexts/editor-context.ts";

/**
 * Props for the {@link TableHandleRoot} Solid component.
 *
 * @public
 */
export interface TableHandleRootProps extends JSX.HTMLAttributes<TableHandleRootElement> {
  /**
   * The ProseKit editor instance.
   *
   * @default null
   * @hidden
   */
  editor?: TableHandleRootElementProps["editor"];
}

/**
 * A Solid component that renders an `prosekit-table-handle-root` custom element.
 *
 * @public
 */
export const TableHandleRoot: Component<TableHandleRootProps> = (
  props,
): any => {
  registerTableHandleRootElement();

  const [elementProps, restProps] = splitProps(props, ["editor"]);

  const editorContext = useEditorContext();

  return h(
    "prosekit-table-handle-root",
    mergeProps(restProps, {
      "prop:editor": () => elementProps.editor ?? editorContext,
    }),
  );
};
