/**
 * This file is auto-generated by the "@aria-ui/cli" tool. Do not edit this file directly.
 */

import { registerTableHandleRowPopupElement, type TableHandleRowPopupElement } from '@prosekit/web/table-handle';
import type { Component, JSX } from 'solid-js';
import h from 'solid-js/h';

/**
 * Props for the {@link TableHandleRowPopup} Solid component.
 *
 * @public
 */
export interface TableHandleRowPopupProps extends JSX.HTMLAttributes<TableHandleRowPopupElement> {}

/**
 * A Solid component that renders an `prosekit-table-handle-row-popup` custom element.
 *
 * @public
 */
export const TableHandleRowPopup: Component<TableHandleRowPopupProps> = (props): any => {
  registerTableHandleRowPopupElement();

  const restProps = props;

  return () => h('prosekit-table-handle-row-popup', restProps);
};
