import fs from 'node:fs/promises'
import path from 'node:path'

import { uneval } from 'devalue'
import prettier from 'prettier'
import { IndentationText, Project, VariableDeclarationKind, type SourceFile } from 'ts-morph'

import { logger } from './logger'
import type { ComponentInfo } from './parse'

export type Framework = 'react' | 'preact' | 'solid' | 'vue' | 'svelte'

export const FRAMEWORKS: Framework[] = ['react', 'preact', 'solid', 'vue', 'svelte']

export interface GenerateOptions {
  prefix: string
  importSource: string
  framework: Framework
  wrapperExtensions?: WrapperExtension[]
}

export interface WrapperMatchContext {
  framework: Framework
  component: ComponentInfo
  importSource: string
}

export interface WrapperApplyContext extends WrapperMatchContext {
  getPropVariable(propName: string): string
  addImport(moduleSpecifier: string, namedImports: string[]): void
  addSetupStatement(statement: string): void
  setRenderPropsExpression(expression: string): void
  setReactPropOverride(propName: string, expression: string): void
  addSvelteScriptStatement(statement: string): void
}

export interface WrapperExtension {
  name: string
  match?: (context: WrapperMatchContext) => boolean
  apply(context: WrapperApplyContext): void
}

export interface FrameworkHookResolver {
  importSource: string
  importName: string
  callExpression?: string
}

export interface PropFallbackExtensionOptions {
  prop: string
  match?: (context: WrapperMatchContext) => boolean
  frameworks: Partial<Record<Framework, FrameworkHookResolver>>
}

type ComponentMeta = {
  componentName: string
  kebabName: string
  tagName: string
  props: ComponentInfo['props']
  events: ComponentInfo['events']
  hasProps: boolean
  hasEvents: boolean
  eventHandlers: Array<{
    eventName: string
    handlerName: string
  }>
}

type PropsInterfaceOptions = {
  sourceFile: SourceFile
  component: ComponentInfo
  name: string
  docs: string[]
  extendsTypes?: string[]
  propsTypeName?: string
  eventsTypeName?: string
  includeChildren?: boolean
}

type ElementTypeImportOrder = 'props-first' | 'events-first'

type SourceImportOptions = {
  sourceFile: SourceFile
  component: ComponentInfo
  importSource: string
  order: ElementTypeImportOrder
  includeRegister: boolean
  includeElementType: boolean
  includePropsDeclaration?: boolean
}

type WrapperImport = {
  moduleSpecifier: string
  namedImports: string[]
}

type WrapperExtensionSlots = {
  imports: WrapperImport[]
  setupStatements: string[]
  renderPropsExpression?: string
  reactPropOverrides: Record<string, string>
  svelteScriptStatements: string[]
}

async function formatWithPrettier(filePath: string, contents: string): Promise<string> {
  const options = (await prettier.resolveConfig(filePath)) ?? {}
  return await prettier.format(contents, {
    ...options,
    filepath: filePath,
  })
}

const GENERATED_HEADER_TS = `/**
 * This file is auto-generated by the "@aria-ui/cli" tool. Do not edit this file directly.
 */

`

const GENERATED_HEADER_SVELTE = `<!-- This file is auto-generated by the "@aria-ui/cli" tool. Do not edit this file directly. -->

`

async function writeFormattedFile(filePath: string, contents: string): Promise<void> {
  const header = filePath.endsWith('.svelte') ? GENERATED_HEADER_SVELTE : GENERATED_HEADER_TS
  const withHeader = header + contents
  const finalContents = filePath.endsWith('.ts')
    ? await formatWithPrettier(filePath, withHeader)
    : withHeader
  await fs.writeFile(filePath, finalContents)
  logger.info(`Generated ${filePath}`)
}

async function writeSourceFile(
  project: Project,
  filePath: string,
  generate: (sourceFile: SourceFile) => void,
): Promise<void> {
  const sourceFile = project.createSourceFile(filePath, '', {
    overwrite: true,
  })
  generate(sourceFile)
  await writeFormattedFile(filePath, sourceFile.getFullText())
}

export function propFallback(options: PropFallbackExtensionOptions): WrapperExtension {
  if (options.prop.length === 0) {
    throw new Error('propFallback requires a non-empty prop name')
  }

  return {
    name: `propFallback:${options.prop}`,
    match(context) {
      const hasProp = context.component.props.some((prop) => prop.name === options.prop)
      return hasProp && (options.match?.(context) ?? true)
    },
    apply(context) {
      const resolver = options.frameworks[context.framework]
      if (!resolver) {
        return
      }

      const callExpression = resolver.callExpression ?? `${resolver.importName}()`
      const fallbackVar = `${context.getPropVariable(options.prop)}Fallback`

      context.addImport(resolver.importSource, [resolver.importName])

      switch (context.framework) {
        case 'react':
        case 'preact':
        case 'vue':
        case 'solid':
          context.addSetupStatement(`const ${fallbackVar} = ${callExpression};`)
          context.setReactPropOverride(options.prop, `?? ${fallbackVar}`)
          break

        case 'svelte':
          context.addSvelteScriptStatement(`const ${fallbackVar} = ${callExpression}`)
          context.setReactPropOverride(options.prop, `?? ${fallbackVar}`)
          break
      }
    },
  }
}

export async function generateFiles(
  components: ComponentInfo[],
  outputDir: string,
  options: GenerateOptions,
): Promise<void> {
  await fs.mkdir(outputDir, { recursive: true })

  const project = new Project({
    manipulationSettings: {
      indentationText: IndentationText.TwoSpaces,
      useTrailingCommas: true,
    },
  })

  for (const component of components) {
    const fileName = getComponentFileName(component)
    const filePath = path.join(outputDir, fileName)

    switch (options.framework) {
      case 'react':
        await writeSourceFile(project, filePath, (sourceFile) => generateReactComponentFile(sourceFile, component, options))
        break
      case 'preact':
        await writeSourceFile(project, filePath, (sourceFile) => generatePreactComponentFile(sourceFile, component, options))
        break
      case 'solid':
        await writeSourceFile(project, filePath, (sourceFile) => generateSolidComponentFile(sourceFile, component, options))
        break
      case 'vue':
        await writeSourceFile(project, filePath, (sourceFile) => generateVueComponentFile(sourceFile, component, options))
        break
      case 'svelte': {
        await writeSourceFile(project, filePath, (sourceFile) => generateSvelteComponentFile(sourceFile, component, options))
        const svelteFileName = getSvelteComponentFileName(component)
        const svelteComponentPath = path.join(outputDir, svelteFileName)
        const svelteContents = generateSvelteComponentSvelteFile(component, options)
        await writeFormattedFile(svelteComponentPath, svelteContents)
        break
      }
    }
  }

  // Generate index.gen.ts barrel file
  const indexPath = path.join(outputDir, 'index.gen.ts')
  const indexContents = generateIndexFile(components)
  await writeFormattedFile(indexPath, indexContents)
}

function getWrapperExtensionSlots(
  component: ComponentInfo,
  options: GenerateOptions,
): WrapperExtensionSlots {
  const slots: WrapperExtensionSlots = {
    imports: [],
    setupStatements: [],
    reactPropOverrides: {},
    svelteScriptStatements: [],
  }

  const extensions = options.wrapperExtensions ?? []
  if (extensions.length === 0) {
    return slots
  }

  // Pre-compute sorted prop variable names for extensions
  const sortedProps = [...component.props].sort((a, b) => a.name.localeCompare(b.name))
  const propVariableMap = new Map<string, string>()
  for (const [index, prop] of sortedProps.entries()) {
    propVariableMap.set(prop.name, `p${index}`)
  }

  const matchContext: WrapperMatchContext = {
    framework: options.framework,
    component,
    importSource: options.importSource,
  }

  const applyContext: WrapperApplyContext = {
    ...matchContext,
    getPropVariable(propName) {
      const variable = propVariableMap.get(propName)
      if (!variable) {
        throw new Error(`Unknown prop: ${propName}`)
      }
      return variable
    },
    addImport(moduleSpecifier, namedImports) {
      if (namedImports.length === 0) {
        return
      }

      const existingImport = slots.imports.find((item) => item.moduleSpecifier === moduleSpecifier)
      if (existingImport) {
        for (const namedImport of namedImports) {
          if (!existingImport.namedImports.includes(namedImport)) {
            existingImport.namedImports.push(namedImport)
          }
        }
        return
      }

      slots.imports.push({
        moduleSpecifier,
        namedImports: [...namedImports],
      })
    },
    addSetupStatement(statement) {
      if (!slots.setupStatements.includes(statement)) {
        slots.setupStatements.push(statement)
      }
    },
    setRenderPropsExpression(expression) {
      slots.renderPropsExpression = expression
    },
    setReactPropOverride(propName, expression) {
      slots.reactPropOverrides[propName] = expression
    },
    addSvelteScriptStatement(statement) {
      if (!slots.svelteScriptStatements.includes(statement)) {
        slots.svelteScriptStatements.push(statement)
      }
    },
  }

  for (const extension of extensions) {
    if (extension.match?.(matchContext) === false) {
      continue
    }
    extension.apply(applyContext)
  }

  return slots
}

function addWrapperImports(sourceFile: SourceFile, imports: WrapperImport[]): void {
  for (const item of imports) {
    sourceFile.addImportDeclaration({
      moduleSpecifier: item.moduleSpecifier,
      namedImports: item.namedImports,
    })
  }
}

function indentBlock(contents: string, size: number): string {
  const indentation = ' '.repeat(size)
  return contents
    .split('\n')
    .map((line) => (line.length > 0 ? `${indentation}${line}` : line))
    .join('\n')
}

function joinStatements(statements: string[], separator = '\n\n'): string {
  return statements.join(separator)
}

function generateReactComponentFile(
  sourceFile: SourceFile,
  component: ComponentInfo,
  options: GenerateOptions,
): void {
  const slots = getWrapperExtensionSlots(component, options)
  const {
    componentName,
    tagName,
    hasEvents,
    hasProps,
    props,
    eventHandlers,
  } = getComponentMeta(component, options.prefix)

  const reactImports: (string | { name: string; isTypeOnly: true })[] = [
    'createElement',
    'forwardRef',
    'useCallback',
    'useRef',
    { name: 'ForwardedRef', isTypeOnly: true },
    { name: 'ForwardRefExoticComponent', isTypeOnly: true },
    { name: 'HTMLAttributes', isTypeOnly: true },
    { name: 'RefAttributes', isTypeOnly: true },
  ]
  if (hasProps || hasEvents) {
    reactImports.push('useLayoutEffect')
  }

  sourceFile.addImportDeclaration({
    moduleSpecifier: 'react',
    namedImports: reactImports,
  })

  const { propsTypeName, eventsTypeName } = addSourceFileImports({
    sourceFile,
    component,
    importSource: options.importSource,
    order: 'props-first',
    includeRegister: true,
    includeElementType: true,
  })
  addWrapperImports(sourceFile, slots.imports)

  addPropsInterface({
    sourceFile,
    component,
    name: `${componentName}Props`,
    docs: [`Props for the {@link ${componentName}} React component.\n\n@public`],
    extendsTypes: [`HTMLAttributes<${componentName}Element>`],
    propsTypeName: hasProps ? propsTypeName : undefined,
    eventsTypeName: hasEvents ? eventsTypeName : undefined,
  })

  // Build destructure entries
  const destructureEntries = [
    ...props.map((p, i) => `${p.name}: p${i}`),
    ...eventHandlers.map((h, i) => `${h.handlerName}: e${i}`),
  ]

  // Build Object.assign entries with possible overrides from extensions
  const propAssignEntries = props.map((p, i) => {
    const override = slots.reactPropOverrides[p.name]
    return override ? `${p.name}: p${i} ${override}` : `${p.name}: p${i}`
  })

  const handlersList = eventHandlers.map((_, i) => `e${i}`)
  const eventNamesList = eventHandlers.map((h) => JSON.stringify(h.eventName))

  const setupStatements = slots.setupStatements.length > 0
    ? `\n  ${slots.setupStatements.join('\n  ')}\n`
    : ''

  const handlersRefDecl = hasEvents
    ? `\n  const handlersRef = useRef<Array<((event: Event) => void) | undefined>>([])`
    : ''

  const handlersRefUpdate = hasEvents
    ? `\n    handlersRef.current = [${handlersList.join(', ')}] as Array<((event: Event) => void) | undefined>`
    : ''

  let mountEffect = ''
  if (hasEvents) {
    mountEffect = `
  useLayoutEffect(() => {
    const element = elementRef.current
    if (!element) return
    const ac = new AbortController()
    for (const [index, eventName] of [${eventNamesList.join(', ')}].entries()) {
      element.addEventListener(eventName, (event: Event) => { handlersRef.current[index]?.(event) }, { signal: ac.signal })
    }
    return () => ac.abort()
  }, [])
`
  }

  const destructureLine = destructureEntries.length > 0
    ? `const { ${destructureEntries.join(', ')}, ...restProps } = props`
    : `const { ...restProps } = props`

  let propsEffect = ''
  if (hasProps || hasEvents) {
    const assignLine = hasProps ? `\n    Object.assign(element, { ${propAssignEntries.join(', ')} })` : ''
    propsEffect = `
  useLayoutEffect(() => {
    const element = elementRef.current as Record<string, unknown> | null
    if (!element) return${assignLine}${handlersRefUpdate}
  })
`
  }

  const functionBody = `
  register${componentName}Element()

  const elementRef = useRef<${componentName}Element>(null)${handlersRefDecl}
${setupStatements}
  ${destructureLine}
${propsEffect}${mountEffect}
  const mergedRef = useCallback((element: ${componentName}Element | null) => {
    elementRef.current = element
    if (typeof forwardedRef === 'function') { forwardedRef(element) }
    else if (forwardedRef) { forwardedRef.current = element }
  }, [])

  return createElement('${tagName}', { ...restProps, ref: mergedRef, suppressHydrationWarning: true })
`

  sourceFile.addStatements(`\nfunction ${componentName}Component(
  props: ${componentName}Props,
  forwardedRef: ForwardedRef<${componentName}Element>,
) {${functionBody}}`)

  sourceFile.addVariableStatement({
    isExported: true,
    declarationKind: VariableDeclarationKind.Const,
    docs: [`A React component that renders an \`${tagName}\` custom element.\n\n@public`],
    declarations: [
      {
        name: componentName,
        type: `ForwardRefExoticComponent<${componentName}Props & RefAttributes<${componentName}Element>>`,
        initializer: `/* @__PURE__ */ forwardRef(${componentName}Component)`,
      },
    ],
  })

  addEventTypeReExports(sourceFile, component, options.importSource)
}

function generatePreactComponentFile(
  sourceFile: SourceFile,
  component: ComponentInfo,
  options: GenerateOptions,
): void {
  const slots = getWrapperExtensionSlots(component, options)
  const {
    componentName,
    tagName,
    hasEvents,
    hasProps,
    props,
    eventHandlers,
  } = getComponentMeta(component, options.prefix)

  const preactImports: (string | { name: string; isTypeOnly: true })[] = [
    'createElement',
    { name: 'HTMLAttributes', isTypeOnly: true },
    { name: 'Ref', isTypeOnly: true },
  ]

  sourceFile.addImportDeclaration({
    moduleSpecifier: 'preact',
    namedImports: preactImports,
  })

  const preactCompatImports: (string | { name: string; isTypeOnly: true })[] = [
    'forwardRef',
    { name: 'ForwardRefExoticComponent', isTypeOnly: true },
    { name: 'RefAttributes', isTypeOnly: true },
  ]

  sourceFile.addImportDeclaration({
    moduleSpecifier: 'preact/compat',
    namedImports: preactCompatImports,
  })

  const preactHooksImports: string[] = ['useCallback', 'useRef']
  if (hasProps || hasEvents) {
    preactHooksImports.push('useLayoutEffect')
  }

  sourceFile.addImportDeclaration({
    moduleSpecifier: 'preact/hooks',
    namedImports: preactHooksImports,
  })

  const { propsTypeName, eventsTypeName } = addSourceFileImports({
    sourceFile,
    component,
    importSource: options.importSource,
    order: 'props-first',
    includeRegister: true,
    includeElementType: true,
  })
  addWrapperImports(sourceFile, slots.imports)

  addPropsInterface({
    sourceFile,
    component,
    name: `${componentName}Props`,
    docs: [`Props for the {@link ${componentName}} Preact component.\n\n@public`],
    extendsTypes: [`HTMLAttributes<${componentName}Element>`],
    propsTypeName: hasProps ? propsTypeName : undefined,
    eventsTypeName: hasEvents ? eventsTypeName : undefined,
  })

  // Same inline pattern as React
  const destructureEntries = [
    ...props.map((p, i) => `${p.name}: p${i}`),
    ...eventHandlers.map((h, i) => `${h.handlerName}: e${i}`),
  ]

  const propAssignEntries = props.map((p, i) => {
    const override = slots.reactPropOverrides[p.name]
    return override ? `${p.name}: p${i} ${override}` : `${p.name}: p${i}`
  })

  const handlersList = eventHandlers.map((_, i) => `e${i}`)
  const eventNamesList = eventHandlers.map((h) => JSON.stringify(h.eventName))

  const setupStatements = slots.setupStatements.length > 0
    ? `\n  ${slots.setupStatements.join('\n  ')}\n`
    : ''

  const handlersRefDecl = hasEvents
    ? `\n  const handlersRef = useRef<Array<((event: Event) => void) | undefined>>([])`
    : ''

  const handlersRefUpdate = hasEvents
    ? `\n    handlersRef.current = [${handlersList.join(', ')}] as Array<((event: Event) => void) | undefined>`
    : ''

  let mountEffect = ''
  if (hasEvents) {
    mountEffect = `
  useLayoutEffect(() => {
    const element = elementRef.current
    if (!element) return
    const ac = new AbortController()
    for (const [index, eventName] of [${eventNamesList.join(', ')}].entries()) {
      element.addEventListener(eventName, (event: Event) => { handlersRef.current[index]?.(event) }, { signal: ac.signal })
    }
    return () => ac.abort()
  }, [])
`
  }

  const destructureLine = destructureEntries.length > 0
    ? `const { ${destructureEntries.join(', ')}, ...restProps } = props`
    : `const { ...restProps } = props`

  let propsEffect = ''
  if (hasProps || hasEvents) {
    const assignLine = hasProps ? `\n    Object.assign(element, { ${propAssignEntries.join(', ')} })` : ''
    propsEffect = `
  useLayoutEffect(() => {
    const element = elementRef.current as Record<string, unknown> | null
    if (!element) return${assignLine}${handlersRefUpdate}
  })
`
  }

  const functionBody = `
  register${componentName}Element()

  const elementRef = useRef<${componentName}Element>(null)${handlersRefDecl}
${setupStatements}
  ${destructureLine}
${propsEffect}${mountEffect}
  const mergedRef = useCallback((element: ${componentName}Element | null) => {
    elementRef.current = element
    if (typeof forwardedRef === 'function') { forwardedRef(element) }
    else if (forwardedRef) { forwardedRef.current = element }
  }, [])

  return createElement('${tagName}', { ...restProps, ref: mergedRef, suppressHydrationWarning: true })
`

  sourceFile.addStatements(`\nfunction ${componentName}Component(
  props: ${componentName}Props,
  forwardedRef: Ref<${componentName}Element>,
) {${functionBody}}`)

  sourceFile.addVariableStatement({
    isExported: true,
    declarationKind: VariableDeclarationKind.Const,
    docs: [`A Preact component that renders an \`${tagName}\` custom element.\n\n@public`],
    declarations: [
      {
        name: componentName,
        type: `ForwardRefExoticComponent<${componentName}Props & RefAttributes<${componentName}Element>>`,
        initializer: `/* @__PURE__ */ forwardRef(${componentName}Component)`,
      },
    ],
  })

  addEventTypeReExports(sourceFile, component, options.importSource)
}

function generateSolidComponentFile(
  sourceFile: SourceFile,
  component: ComponentInfo,
  options: GenerateOptions,
): void {
  const slots = getWrapperExtensionSlots(component, options)
  const {
    componentName,
    tagName,
    hasEvents,
    hasProps,
    props,
    eventHandlers,
  } = getComponentMeta(component, options.prefix)

  const { propsTypeName, eventsTypeName } = addSourceFileImports({
    sourceFile,
    component,
    importSource: options.importSource,
    order: 'events-first',
    includeRegister: true,
    includeElementType: true,
  })

  const needsSplitProps = hasProps || hasEvents

  const solidImports: string[] = []
  if (needsSplitProps) {
    solidImports.push('createEffect', 'createSignal', 'mergeProps', 'splitProps')
  }

  if (solidImports.length > 0) {
    sourceFile.addImportDeclaration({
      moduleSpecifier: 'solid-js',
      namedImports: solidImports,
    })
  }

  sourceFile.addImportDeclaration({
    moduleSpecifier: 'solid-js',
    namedImports: ['Component', 'JSX'],
    isTypeOnly: true,
  })

  sourceFile.addImportDeclaration({
    moduleSpecifier: 'solid-js/h',
    defaultImport: 'h',
  })
  addWrapperImports(sourceFile, slots.imports)

  addPropsInterface({
    sourceFile,
    component,
    name: `${componentName}Props`,
    docs: [`Props for the {@link ${componentName}} Solid component.\n\n@public`],
    extendsTypes: [`JSX.HTMLAttributes<${componentName}Element>`],
    propsTypeName: hasProps ? propsTypeName : undefined,
    eventsTypeName: hasEvents ? eventsTypeName : undefined,
  })

  const propNames = props.map((prop) => prop.name)
  const eventHandlerNames = eventHandlers.map((handler) => handler.handlerName)
  const splitPropsArgs = [
    ...(propNames.length > 0 ? [uneval(propNames)] : []),
    ...(eventHandlerNames.length > 0 ? [uneval(eventHandlerNames)] : []),
  ]
  const splitPropsTargets = [
    ...(propNames.length > 0 ? ['elementProps'] : []),
    ...(eventHandlerNames.length > 0 ? ['eventHandlers'] : []),
    'restProps',
  ]
  const splitPropsStatement = splitPropsArgs.length > 0
    ? `const [ ${splitPropsTargets.join(', ')} ] = splitProps(props, ${splitPropsArgs.join(', ')})`
    : 'const restProps = props'

  // Build component body
  const bodyLines: string[] = []
  bodyLines.push(`register${componentName}Element()`)

  if (needsSplitProps) {
    bodyLines.push('')
    bodyLines.push(`const [getElement, setElement] = createSignal<${componentName}Element | null>(null)`)

    if (hasEvents) {
      bodyLines.push('const handlers: Array<((event: any) => void) | undefined> = []')
    }

    bodyLines.push('')
    bodyLines.push(splitPropsStatement)

    // Extension setup statements
    const setupStatements = joinStatements(slots.setupStatements)
    if (setupStatements.length > 0) {
      bodyLines.push('')
      bodyLines.push(setupStatements)
    }

    // First createEffect: props + handlers
    bodyLines.push('')
    bodyLines.push('createEffect(() => {')
    bodyLines.push('  const element = getElement()')
    bodyLines.push('  if (!element) return')

    if (hasProps) {
      const propAssignEntries = props.map((prop) => {
        const override = slots.reactPropOverrides[prop.name]
        return override
          ? `  ${prop.name}: elementProps.${prop.name} ${override}`
          : `  ${prop.name}: elementProps.${prop.name}`
      })
      bodyLines.push('')
      bodyLines.push(`  Object.assign(element, {`)
      bodyLines.push(propAssignEntries.join(',\n'))
      bodyLines.push(`  })`)
    }

    if (hasEvents) {
      bodyLines.push('')
      bodyLines.push('  handlers.length = 0')
      for (const handler of eventHandlers) {
        bodyLines.push(`  handlers.push(eventHandlers.${handler.handlerName})`)
      }
    }

    bodyLines.push('})')

    // Second createEffect: event listeners
    if (hasEvents) {
      const eventNames = eventHandlers.map((h) => `'${h.eventName}'`)

      bodyLines.push('')
      bodyLines.push('createEffect(() => {')
      bodyLines.push('  const element = getElement()')
      bodyLines.push('  if (!element) return')
      bodyLines.push('')
      bodyLines.push('  const ac = new AbortController()')
      bodyLines.push(`  for (const [index, eventName] of [${eventNames.join(', ')}].entries()) {`)
      bodyLines.push('    element.addEventListener(eventName, (event) => {')
      bodyLines.push('      handlers[index]?.(event)')
      bodyLines.push('    }, { signal: ac.signal })')
      bodyLines.push('  }')
      bodyLines.push('  return () => ac.abort()')
      bodyLines.push('})')
    }

    // Return h() with ref
    bodyLines.push('')
    bodyLines.push('')
    bodyLines.push(`return h(`)
    bodyLines.push(`  '${tagName}',`)
    bodyLines.push(`  mergeProps(restProps, {`)
    bodyLines.push(`    ref: (el: ${componentName}Element | null  ) => {`)
    bodyLines.push(`      setElement(el)`)
    bodyLines.push(`    },`)
    bodyLines.push(`  }),`)
    bodyLines.push(`)`)
  } else {
    // No props or events: simple passthrough
    bodyLines.push('')
    bodyLines.push('const restProps = props')
    bodyLines.push('')
    bodyLines.push(`return h('${tagName}', restProps)`)
  }

  const componentInitializer = `(props): any => {
${bodyLines.join('\n')}
}`

  sourceFile.addVariableStatement({
    isExported: true,
    declarationKind: VariableDeclarationKind.Const,
    docs: [`A Solid component that renders an \`${tagName}\` custom element.\n\n@public`],
    declarations: [
      {
        name: componentName,
        type: `Component<${componentName}Props>`,
        initializer: componentInitializer,
      },
    ],
  })

  addEventTypeReExports(sourceFile, component, options.importSource)
}

function generateVueComponentFile(
  sourceFile: SourceFile,
  component: ComponentInfo,
  options: GenerateOptions,
): void {
  const slots = getWrapperExtensionSlots(component, options)
  const {
    componentName,
    tagName,
    hasEvents,
    hasProps,
    props,
    eventHandlers,
  } = getComponentMeta(component, options.prefix)

  const needsReactiveSetup = hasProps || hasEvents

  const vueImports: (string | { name: string; isTypeOnly: true })[] = [
    'defineComponent',
    'h',
    { name: 'DefineSetupFnComponent', isTypeOnly: true },
    { name: 'HTMLAttributes', isTypeOnly: true },
  ]
  if (needsReactiveSetup) {
    vueImports.push('shallowRef', 'computed', 'watchEffect')
  }

  sourceFile.addImportDeclaration({
    moduleSpecifier: 'vue',
    namedImports: vueImports,
  })

  const { propsTypeName, eventsTypeName } = addSourceFileImports({
    sourceFile,
    component,
    importSource: options.importSource,
    order: 'events-first',
    includeRegister: true,
    includeElementType: false,
  })
  addWrapperImports(sourceFile, slots.imports)

  addPropsInterface({
    sourceFile,
    component,
    name: `${componentName}Props`,
    docs: [`Props for the {@link ${componentName}} Vue component.\n\n@public`],
    propsTypeName: hasProps ? propsTypeName : undefined,
    eventsTypeName: hasEvents ? eventsTypeName : undefined,
  })

  const propBindings = props.map((prop, index) => ({
    name: prop.name,
    variableName: `p${index}`,
  }))
  const eventBindings = eventHandlers.map((handler, index) => ({
    eventName: handler.eventName,
    handlerName: handler.handlerName,
    variableName: `e${index}`,
  }))

  // Props option: simple array of prop/event handler names
  const allDeclaredNames = [
    ...propBindings.map((b) => JSON.stringify(b.name)),
    ...eventBindings.map((b) => JSON.stringify(b.handlerName)),
  ]
  const propsOption = allDeclaredNames.length > 0
    ? `[${allDeclaredNames.join(', ')}]`
    : '[]'

  // Build component body
  const bodyLines: string[] = []
  bodyLines.push(`  register${componentName}Element()`)

  if (needsReactiveSetup) {
    bodyLines.push('')
    bodyLines.push('  const elementRef = shallowRef<HTMLElement | null>(null)')

    // Extension setup statements
    const setupStatements = joinStatements(slots.setupStatements)
    if (setupStatements.length > 0) {
      bodyLines.push('')
      bodyLines.push(indentBlock(setupStatements, 2))
    }

    // Computed splittedProps
    const destructureEntries = [
      ...propBindings.map((b) => `${b.name}: ${b.variableName}`),
      ...eventBindings.map((b) => `${b.handlerName}: ${b.variableName}`),
    ]
    const allVariables = [
      ...propBindings.map((b) => b.variableName),
      ...eventBindings.map((b) => b.variableName),
    ]

    bodyLines.push('')
    bodyLines.push(`  const splittedProps = computed(() => {`)
    bodyLines.push(`    const { ${destructureEntries.join(', ')}, ...restProps } = props`)
    bodyLines.push(`    return [`)
    bodyLines.push(`      [${allVariables.join(', ')}],`)
    bodyLines.push(`      restProps,`)
    bodyLines.push(`    ] as const`)
    bodyLines.push(`  })`)

    if (hasEvents) {
      bodyLines.push('')
      bodyLines.push('  const handlers: (Function | undefined)[] = []')
    }

    // First watchEffect: props + handlers
    bodyLines.push('')
    bodyLines.push('  watchEffect(() => {')
    bodyLines.push('    const element = elementRef.value')
    bodyLines.push('    if (!element) return')
    bodyLines.push('')
    bodyLines.push(`    const [${allVariables.join(', ')}] = splittedProps.value[0]`)

    if (hasProps) {
      const propAssignEntries = propBindings.map((b) => {
        const override = slots.reactPropOverrides[b.name]
        return override ? `${b.name}: ${b.variableName} ${override}` : `${b.name}: ${b.variableName}`
      })
      bodyLines.push('')
      bodyLines.push(`    Object.assign(element, { ${propAssignEntries.join(', ')} })`)
    }

    if (hasEvents) {
      bodyLines.push('')
      bodyLines.push('    handlers.length = 0')
      for (const binding of eventBindings) {
        bodyLines.push(`    handlers.push(${binding.variableName})`)
      }
    }

    bodyLines.push('  })')

    // Second watchEffect: event listeners
    if (hasEvents) {
      const eventNames = eventBindings.map((b) => JSON.stringify(b.eventName))

      bodyLines.push('')
      bodyLines.push('  watchEffect(() => {')
      bodyLines.push('    const element = elementRef.value')
      bodyLines.push('    if (!element) return')
      bodyLines.push('')
      bodyLines.push('    const ac = new AbortController()')
      bodyLines.push(`    for (const [index, eventName] of [${eventNames.join(', ')}].entries()) {`)
      bodyLines.push('      element.addEventListener(eventName, (event: Event) => { handlers[index]?.(event) }, { signal: ac.signal })')
      bodyLines.push('    }')
      bodyLines.push('    return () => ac.abort()')
      bodyLines.push('  })')
    }

    // Return render function
    bodyLines.push('')
    bodyLines.push('  return () => {')
    bodyLines.push('    const restProps = splittedProps.value[1]')
    bodyLines.push(`    return h('${tagName}', { ...restProps, ref: elementRef }, slots.default?.())`)
    bodyLines.push('  }')
  } else {
    // No props or events: simple passthrough
    bodyLines.push('')
    bodyLines.push('  return () => {')
    bodyLines.push(`    const _props = { ...props }`)
    bodyLines.push(`    return h('${tagName}', _props, slots.default?.())`)
    bodyLines.push('  }')
  }

  const componentInitializer = `/* @__PURE__ */ defineComponent<${componentName}Props & HTMLAttributes>(
(props, { slots }) => {
${bodyLines.join('\n')}
},
{ props: ${propsOption} },
)`

  sourceFile.addVariableStatement({
    isExported: true,
    declarationKind: VariableDeclarationKind.Const,
    docs: [`A Vue component that renders an \`${tagName}\` custom element.\n\n@public`],
    declarations: [
      {
        name: componentName,
        type: `DefineSetupFnComponent<${componentName}Props & HTMLAttributes>`,
        initializer: componentInitializer,
      },
    ],
  })

  addEventTypeReExports(sourceFile, component, options.importSource)
}

function generateSvelteComponentFile(
  sourceFile: SourceFile,
  component: ComponentInfo,
  options: GenerateOptions,
): void {
  const { componentName, kebabName, tagName, hasEvents, hasProps } = getComponentMeta(component, options.prefix)

  sourceFile.addImportDeclaration({
    moduleSpecifier: `./${kebabName}.gen.svelte`,
    defaultImport: `${componentName}Component`,
  })

  const { propsTypeName, eventsTypeName } = addSourceFileImports({
    sourceFile,
    component,
    importSource: options.importSource,
    order: 'events-first',
    includeRegister: false,
    includeElementType: false,
  })

  sourceFile.addImportDeclaration({
    moduleSpecifier: 'svelte',
    isTypeOnly: true,
    namedImports: ['Component', 'Snippet'],
  })

  addPropsInterface({
    sourceFile,
    component,
    name: `${componentName}Props`,
    docs: [`Props for the {@link ${componentName}} Svelte component.\n\n@public`],
    propsTypeName: hasProps ? propsTypeName : undefined,
    eventsTypeName: hasEvents ? eventsTypeName : undefined,
    includeChildren: true,
  })

  sourceFile.addVariableStatement({
    isExported: true,
    declarationKind: VariableDeclarationKind.Const,
    docs: [`A Svelte component that renders an \`${tagName}\` custom element.\n\n@public`],
    declarations: [
      {
        name: componentName,
        type: `Component<${componentName}Props>`,
        initializer: `${componentName}Component as unknown as Component<${componentName}Props>`,
      },
    ],
  })

  addEventTypeReExports(sourceFile, component, options.importSource)
}

function generateSvelteComponentSvelteFile(component: ComponentInfo, options: GenerateOptions): string {
  const slots = getWrapperExtensionSlots(component, options)
  const { componentName, tagName, props, eventHandlers } = getComponentMeta(component, options.prefix)
  const propBindings = props.map((prop, index) => ({
    name: prop.name,
    variableName: `p${index}`,
  }))
  const eventBindings = eventHandlers.map((handler, index) => ({
    eventName: handler.eventName,
    handlerName: handler.handlerName,
    variableName: `e${index}`,
  }))
  const destructureEntries = [
    ...propBindings.map((binding) => `${binding.name}: ${binding.variableName}`),
    ...eventBindings.map((binding) => `${binding.handlerName}: ${binding.variableName}`),
    'children = undefined',
    '...restProps',
  ]
  const destructureProps = `  let { ${destructureEntries.join(', ')} } = $props()`
  const extensionImports = slots.imports.map(
    (item) => `  import { ${item.namedImports.join(', ')} } from '${item.moduleSpecifier}'`,
  )
  const scriptStatements = slots.svelteScriptStatements.map((statement) => indentBlock(statement, 2))

  const hasProps = propBindings.length > 0
  const hasEvents = eventBindings.length > 0
  const needsElement = hasProps || hasEvents

  const propsEffectLines: string[] = []
  if (needsElement) {
    propsEffectLines.push('  $effect(() => {')
    propsEffectLines.push('    if (!element) return')

    if (hasProps) {
      const entries = propBindings.map((b) => {
        const override = slots.reactPropOverrides[b.name]
        return override ? `${b.name}: ${b.variableName} ${override}` : `${b.name}: ${b.variableName}`
      })
      propsEffectLines.push('')
      propsEffectLines.push(`    Object.assign(element, { ${entries.join(', ')} })`)
    }

    if (hasEvents) {
      propsEffectLines.push('')
      propsEffectLines.push('    handlers.length = 0')
      for (const binding of eventBindings) {
        propsEffectLines.push(`    handlers.push(${binding.variableName})`)
      }
    }

    propsEffectLines.push('  })')
  }

  const eventEffectLines: string[] = []
  if (hasEvents) {
    const eventNames = eventBindings.map((b) => JSON.stringify(b.eventName))
    eventEffectLines.push('  $effect(() => {')
    eventEffectLines.push('    if (!element) return')
    eventEffectLines.push('')
    eventEffectLines.push('    const ac = new AbortController()')
    eventEffectLines.push(`    for (const [index, eventName] of [${eventNames.join(', ')}].entries()) {`)
    eventEffectLines.push('      element.addEventListener(eventName, (event) => handlers[index]?.(event), { signal: ac.signal })')
    eventEffectLines.push('    }')
    eventEffectLines.push('    return () => ac.abort()')
    eventEffectLines.push('  })')
  }

  // Build script block
  const scriptLines: string[] = [
    `<script lang="js">`,
    `  import { register${componentName}Element } from '${options.importSource}'`,
    ...extensionImports,
    `  register${componentName}Element()`,
    '',
    destructureProps,
  ]

  if (needsElement) {
    scriptLines.push('  let element')
  }
  if (hasEvents) {
    scriptLines.push('  const handlers = []')
  }

  if (scriptStatements.length > 0) {
    scriptLines.push('', ...scriptStatements)
  }

  if (propsEffectLines.length > 0) {
    scriptLines.push('', ...propsEffectLines)
  }
  if (eventEffectLines.length > 0) {
    scriptLines.push('', ...eventEffectLines)
  }

  scriptLines.push('</script>')

  // Build template
  const bindThis = needsElement ? ' bind:this={element}' : ''
  const openingTag = `<${tagName} {...restProps}${bindThis}`

  return `${scriptLines.join('\n')}

${openingTag}>{@render children?.()}</${tagName}>
`
}

function getComponentMeta(component: ComponentInfo, prefix: string): ComponentMeta {
  const componentName = component.name
  const kebabName = toKebabCase(componentName)
  const props = [...component.props].sort((a, b) => a.name.localeCompare(b.name))
  const events = [...component.events].sort((a, b) => a.name.localeCompare(b.name))
  return {
    componentName,
    kebabName,
    tagName: `${prefix}-${kebabName}`,
    props,
    events,
    hasProps: props.length > 0,
    hasEvents: events.length > 0,
    eventHandlers: events.map((event) => {
      const handlerName = toEventHandlerName(event.name)
      return {
        eventName: event.name,
        handlerName,
      }
    }),
  }
}

function addSourceFileImports(
  options: SourceImportOptions,
): { propsTypeName: string; eventsTypeName: string } {
  const {
    sourceFile,
    component,
    importSource,
    order,
    includeRegister,
    includeElementType,
    includePropsDeclaration,
  } = options
  const componentName = component.name
  const propsTypeName = `${componentName}ElementProps`
  const eventsTypeName = `${componentName}Events`

  const namedImports: Array<{ name: string; alias?: string; isTypeOnly?: boolean }> = []

  if (includeRegister) {
    namedImports.push({ name: `register${componentName}Element` })
  }

  if (includeElementType) {
    namedImports.push({ name: `${componentName}Element`, isTypeOnly: true })
  }

  const propsImport = component.props.length > 0
    ? { name: `${componentName}Props`, alias: propsTypeName, isTypeOnly: true }
    : null
  const eventsImport = component.events.length > 0
    ? { name: `${componentName}Events`, isTypeOnly: true }
    : null

  if (order === 'props-first') {
    if (propsImport) namedImports.push(propsImport)
    if (eventsImport) namedImports.push(eventsImport)
  } else {
    if (eventsImport) namedImports.push(eventsImport)
    if (propsImport) namedImports.push(propsImport)
  }

  if (includePropsDeclaration && component.props.length > 0) {
    namedImports.push({ name: `${componentName}PropsDeclaration` })
  }

  if (namedImports.length > 0) {
    sourceFile.addImportDeclaration({
      moduleSpecifier: importSource,
      namedImports,
    })
  }

  return { propsTypeName, eventsTypeName }
}

function addPropsInterface(options: PropsInterfaceOptions): void {
  const {
    sourceFile,
    component,
    name,
    docs,
    extendsTypes,
    propsTypeName,
    eventsTypeName,
    includeChildren,
  } = options
  const propsInterface = sourceFile.addInterface({
    name,
    isExported: true,
    extends: extendsTypes,
    docs,
  })

  if (propsTypeName) {
    for (const prop of component.props) {
      propsInterface.addProperty({
        name: prop.name,
        type: `${propsTypeName}['${prop.name}']`,
        hasQuestionToken: true,
        docs: [prop.comment],
      })
    }
  }

  if (eventsTypeName) {
    for (const event of component.events) {
      const eventHandlerName = toEventHandlerName(event.name)
      propsInterface.addProperty({
        name: eventHandlerName,
        type: `(event: ${eventsTypeName}['${event.name}']) => void`,
        hasQuestionToken: true,
        docs: [event.comment],
      })
    }
  }

  if (includeChildren) {
    propsInterface.addProperty({
      name: 'children',
      type: 'Snippet',
      hasQuestionToken: true,
    })
    // TODO: is there any way that we can add correct HTML element props without using "unknonwn"?
    propsInterface.addIndexSignature({
      keyName: 'key',
      keyType: 'string',
      returnType: 'unknown',
    })
  }
}

function generateIndexFile(components: ComponentInfo[]): string {
  const lines: string[] = []
  const exportedEventTypes = new Set<string>()

  for (const component of components) {
    const fileName = getComponentFileName(component)
    const componentName = component.name
    const exports = [componentName, `type ${componentName}Props`]

    if (component.events.length > 0) {
      exports.push(`type ${componentName}Events`)
    }

    for (const event of component.events) {
      if (event.typeName && !exportedEventTypes.has(event.typeName)) {
        exportedEventTypes.add(event.typeName)
        exports.push(event.typeName)
      }
    }

    lines.push(
      `export { ${exports.join(', ')} } from './${fileName}'`,
    )
  }
  return lines.join('\n\n') + '\n'
}

function addEventTypeReExports(
  sourceFile: SourceFile,
  component: ComponentInfo,
  importSource: string,
): void {
  if (component.events.length === 0) return

  // Re-export the events interface type (e.g., PopoverRootEvents)
  const eventsTypeName = `${component.name}Events`
  sourceFile.addExportDeclaration({
    isTypeOnly: true,
    namedExports: [eventsTypeName],
  })

  // Re-export event classes (e.g., OpenChangeEvent)
  const eventTypeNames = getUniqueEventTypeNames(component)
  if (eventTypeNames.length > 0) {
    sourceFile.addExportDeclaration({
      moduleSpecifier: importSource,
      namedExports: eventTypeNames,
    })
  }
}

function getUniqueEventTypeNames(component: ComponentInfo): string[] {
  const seen = new Set<string>()
  for (const event of component.events) {
    if (event.typeName) {
      seen.add(event.typeName)
    }
  }
  return [...seen].sort()
}

function getComponentFileName(component: ComponentInfo): string {
  return `${toKebabCase(component.name)}.gen.ts`
}

function getSvelteComponentFileName(component: ComponentInfo): string {
  return `${toKebabCase(component.name)}.gen.svelte`
}

function toEventHandlerName(eventName: string): string {
  return `on${eventName.charAt(0).toUpperCase()}${eventName.slice(1)}`
}

function toKebabCase(str: string): string {
  return str.replaceAll(/([a-z])([A-Z])/g, '$1-$2').toLowerCase()
}
