import fs from 'node:fs/promises'
import path from 'node:path'

import { uneval } from 'devalue'
import prettier from 'prettier'
import { IndentationText, Project, VariableDeclarationKind, type SourceFile } from 'ts-morph'

import { logger } from './logger'
import type { ComponentInfo } from './parse'

export type Framework = 'react' | 'preact' | 'solid' | 'vue' | 'svelte'

export const FRAMEWORKS: Framework[] = ['react', 'preact', 'solid', 'vue', 'svelte']

export interface GenerateOptions {
  prefix: string
  importSource: string
  framework: Framework
  wrapperExtensions?: WrapperExtension[]
}

export interface WrapperMatchContext {
  framework: Framework
  component: ComponentInfo
  importSource: string
}

export interface WrapperApplyContext extends WrapperMatchContext {
  addImport(moduleSpecifier: string, namedImports: string[]): void
  addSetupStatement(statement: string): void
  setRenderPropsExpression(expression: string): void
  setSolidPropOverride(propName: string, expression: string): void
  addVuePostBuildPropsStatement(statement: string): void
  addSvelteScriptStatement(statement: string): void
  setSveltePropExpression(propName: string, expression: string): void
}

export interface WrapperExtension {
  name: string
  match?: (context: WrapperMatchContext) => boolean
  apply(context: WrapperApplyContext): void
}

export interface FrameworkHookResolver {
  importSource: string
  importName: string
  callExpression?: string
}

export interface PropFallbackExtensionOptions {
  prop: string
  match?: (context: WrapperMatchContext) => boolean
  frameworks: Partial<Record<Framework, FrameworkHookResolver>>
}

type ComponentMeta = {
  componentName: string
  kebabName: string
  tagName: string
  props: ComponentInfo['props']
  events: ComponentInfo['events']
  hasProps: boolean
  hasEvents: boolean
  eventHandlers: Array<{
    eventName: string
    handlerName: string
  }>
}

type PropsInterfaceOptions = {
  sourceFile: SourceFile
  component: ComponentInfo
  name: string
  docs: string[]
  extendsTypes?: string[]
  propsTypeName?: string
  eventsTypeName?: string
  includeChildren?: boolean
}

type ElementTypeImportOrder = 'props-first' | 'events-first'

type SourceImportOptions = {
  sourceFile: SourceFile
  component: ComponentInfo
  importSource: string
  order: ElementTypeImportOrder
  includeRegister: boolean
  includeElementType: boolean
  includePropsDeclaration?: boolean
}

type WrapperImport = {
  moduleSpecifier: string
  namedImports: string[]
}

type WrapperExtensionSlots = {
  imports: WrapperImport[]
  setupStatements: string[]
  renderPropsExpression?: string
  solidPropOverrides: Record<string, string>
  vuePostBuildPropsStatements: string[]
  svelteScriptStatements: string[]
  sveltePropExpressions: Record<string, string>
}

async function formatWithPrettier(filePath: string, contents: string): Promise<string> {
  const options = (await prettier.resolveConfig(filePath)) ?? {}
  return await prettier.format(contents, {
    ...options,
    filepath: filePath,
  })
}

const GENERATED_HEADER_TS = `/**
 * This file is auto-generated by the "@aria-ui/cli" tool. Do not edit this file directly.
 */

`

const GENERATED_HEADER_SVELTE = `<!-- This file is auto-generated by the "@aria-ui/cli" tool. Do not edit this file directly. -->

`

async function writeFormattedFile(filePath: string, contents: string): Promise<void> {
  const header = filePath.endsWith('.svelte') ? GENERATED_HEADER_SVELTE : GENERATED_HEADER_TS
  const withHeader = header + contents
  const finalContents = filePath.endsWith('.ts')
    ? await formatWithPrettier(filePath, withHeader)
    : withHeader
  await fs.writeFile(filePath, finalContents)
  logger.info(`Generated ${filePath}`)
}

async function writeSourceFile(
  project: Project,
  filePath: string,
  generate: (sourceFile: SourceFile) => void,
): Promise<void> {
  const sourceFile = project.createSourceFile(filePath, '', {
    overwrite: true,
  })
  generate(sourceFile)
  await writeFormattedFile(filePath, sourceFile.getFullText())
}

export function propFallback(options: PropFallbackExtensionOptions): WrapperExtension {
  if (options.prop.length === 0) {
    throw new Error('propFallback requires a non-empty prop name')
  }

  return {
    name: `propFallback:${options.prop}`,
    match(context) {
      const hasProp = context.component.props.some((prop) => prop.name === options.prop)
      return hasProp && (options.match?.(context) ?? true)
    },
    apply(context) {
      const resolver = options.frameworks[context.framework]
      if (!resolver) {
        return
      }

      const callExpression = resolver.callExpression ?? `${resolver.importName}()`
      const contextVariableName = `${options.prop}Context`

      context.addImport(resolver.importSource, [resolver.importName])

      switch (context.framework) {
        case 'react':
        case 'preact':
          context.addSetupStatement(`const componentProps: ${context.component.name}Props = { ...props };`)
          context.addSetupStatement(`const ${contextVariableName} = ${callExpression};`)
          context.addSetupStatement(
            `if (componentProps.${options.prop} == null && ${contextVariableName} != null) {
  componentProps.${options.prop} = ${contextVariableName};
}`,
          )
          context.setRenderPropsExpression('componentProps')
          break

        case 'solid':
          context.addSetupStatement(`const ${contextVariableName} = ${callExpression};`)
          context.setSolidPropOverride(
            options.prop,
            `() => elementProps.${options.prop} ?? ${contextVariableName}`,
          )
          break

        case 'vue':
          context.addSetupStatement(`const ${contextVariableName} = ${callExpression};`)
          context.addVuePostBuildPropsStatement(
            `if (_props['.${options.prop}'] == null && ${contextVariableName} != null) {
  _props['.${options.prop}'] = ${contextVariableName};
}`,
          )
          break

        case 'svelte':
          context.addSvelteScriptStatement(`const ${contextVariableName} = ${callExpression}`)
          context.setSveltePropExpression(
            options.prop,
            `propValue ?? ${contextVariableName} ?? propValue`,
          )
          break
      }
    },
  }
}

export async function generateFiles(
  components: ComponentInfo[],
  outputDir: string,
  options: GenerateOptions,
): Promise<void> {
  await fs.mkdir(outputDir, { recursive: true })

  const project = new Project({
    manipulationSettings: {
      indentationText: IndentationText.TwoSpaces,
      useTrailingCommas: true,
    },
  })

  for (const component of components) {
    const fileName = getComponentFileName(component)
    const filePath = path.join(outputDir, fileName)

    switch (options.framework) {
      case 'react':
        await writeSourceFile(project, filePath, (sourceFile) => generateReactComponentFile(sourceFile, component, options))
        break
      case 'preact':
        await writeSourceFile(project, filePath, (sourceFile) => generatePreactComponentFile(sourceFile, component, options))
        break
      case 'solid':
        await writeSourceFile(project, filePath, (sourceFile) => generateSolidComponentFile(sourceFile, component, options))
        break
      case 'vue':
        await writeSourceFile(project, filePath, (sourceFile) => generateVueComponentFile(sourceFile, component, options))
        break
      case 'svelte': {
        await writeSourceFile(project, filePath, (sourceFile) => generateSvelteComponentFile(sourceFile, component, options))
        const svelteFileName = getSvelteComponentFileName(component)
        const svelteComponentPath = path.join(outputDir, svelteFileName)
        const svelteContents = generateSvelteComponentSvelteFile(component, options)
        await writeFormattedFile(svelteComponentPath, svelteContents)
        break
      }
    }
  }

  // Generate index.gen.ts barrel file
  const indexPath = path.join(outputDir, 'index.gen.ts')
  const indexContents = generateIndexFile(components)
  await writeFormattedFile(indexPath, indexContents)
}

function getWrapperExtensionSlots(
  component: ComponentInfo,
  options: GenerateOptions,
): WrapperExtensionSlots {
  const slots: WrapperExtensionSlots = {
    imports: [],
    setupStatements: [],
    solidPropOverrides: {},
    vuePostBuildPropsStatements: [],
    svelteScriptStatements: [],
    sveltePropExpressions: {},
  }

  const extensions = options.wrapperExtensions ?? []
  if (extensions.length === 0) {
    return slots
  }

  const matchContext: WrapperMatchContext = {
    framework: options.framework,
    component,
    importSource: options.importSource,
  }

  const applyContext: WrapperApplyContext = {
    ...matchContext,
    addImport(moduleSpecifier, namedImports) {
      if (namedImports.length === 0) {
        return
      }

      const existingImport = slots.imports.find((item) => item.moduleSpecifier === moduleSpecifier)
      if (existingImport) {
        for (const namedImport of namedImports) {
          if (!existingImport.namedImports.includes(namedImport)) {
            existingImport.namedImports.push(namedImport)
          }
        }
        return
      }

      slots.imports.push({
        moduleSpecifier,
        namedImports: [...namedImports],
      })
    },
    addSetupStatement(statement) {
      if (!slots.setupStatements.includes(statement)) {
        slots.setupStatements.push(statement)
      }
    },
    setRenderPropsExpression(expression) {
      slots.renderPropsExpression = expression
    },
    setSolidPropOverride(propName, expression) {
      slots.solidPropOverrides[propName] = expression
    },
    addVuePostBuildPropsStatement(statement) {
      if (!slots.vuePostBuildPropsStatements.includes(statement)) {
        slots.vuePostBuildPropsStatements.push(statement)
      }
    },
    addSvelteScriptStatement(statement) {
      if (!slots.svelteScriptStatements.includes(statement)) {
        slots.svelteScriptStatements.push(statement)
      }
    },
    setSveltePropExpression(propName, expression) {
      slots.sveltePropExpressions[propName] = expression
    },
  }

  for (const extension of extensions) {
    if (extension.match?.(matchContext) === false) {
      continue
    }
    extension.apply(applyContext)
  }

  return slots
}

function addWrapperImports(sourceFile: SourceFile, imports: WrapperImport[]): void {
  for (const item of imports) {
    sourceFile.addImportDeclaration({
      moduleSpecifier: item.moduleSpecifier,
      namedImports: item.namedImports,
    })
  }
}

function indentBlock(contents: string, size: number): string {
  const indentation = ' '.repeat(size)
  return contents
    .split('\n')
    .map((line) => (line.length > 0 ? `${indentation}${line}` : line))
    .join('\n')
}

function joinStatements(statements: string[], separator = '\n\n'): string {
  return statements.join(separator)
}

function generateReactComponentFile(
  sourceFile: SourceFile,
  component: ComponentInfo,
  options: GenerateOptions,
): void {
  const slots = getWrapperExtensionSlots(component, options)
  const {
    componentName,
    tagName,
    hasEvents,
    hasProps,
    props,
    eventHandlers,
  } = getComponentMeta(component, options.prefix)

  sourceFile.addImportDeclaration({
    moduleSpecifier: '@aria-ui-v2/integrations/react',
    namedImports: ['ReactWrapper'],
  })

  sourceFile.addImportDeclaration({
    moduleSpecifier: 'react',
    namedImports: [
      'createElement',
      'forwardRef',
      { name: 'ForwardedRef', isTypeOnly: true },
      { name: 'ForwardRefExoticComponent', isTypeOnly: true },
      { name: 'HTMLAttributes', isTypeOnly: true },
      { name: 'RefAttributes', isTypeOnly: true },
    ],
  })

  const { propsTypeName, eventsTypeName } = addSourceFileImports({
    sourceFile,
    component,
    importSource: options.importSource,
    order: 'props-first',
    includeRegister: true,
    includeElementType: true,
  })
  addWrapperImports(sourceFile, slots.imports)

  addPropNamesVariable(sourceFile, uneval(props.map((prop) => prop.name)))
  addEventNameMapVariable(
    sourceFile,
    uneval(Object.fromEntries(eventHandlers.map((h) => [h.handlerName, h.eventName]))),
  )

  addPropsInterface({
    sourceFile,
    component,
    name: `${componentName}Props`,
    docs: [`Props for the {@link ${componentName}} React component.\n\n@public`],
    extendsTypes: [`HTMLAttributes<${componentName}Element>`],
    propsTypeName: hasProps ? propsTypeName : undefined,
    eventsTypeName: hasEvents ? eventsTypeName : undefined,
  })

  const renderPropsExpression = slots.renderPropsExpression ?? 'props'
  const wrapperPropsArgument = renderPropsExpression === 'props'
    ? 'props'
    : `props: ${renderPropsExpression}`
  const statements = [
    `register${componentName}Element();`,
    ...slots.setupStatements,
    `return createElement(ReactWrapper, { as: '${tagName}', propNames, eventNameMap, ${wrapperPropsArgument}, forwardedRef });`,
  ]

  sourceFile.addFunction({
    name: `${componentName}Component`,
    parameters: [
      { name: 'props', type: `${componentName}Props` },
      { name: 'forwardedRef', type: `ForwardedRef<${componentName}Element>` },
    ],
    statements,
  })

  sourceFile.addVariableStatement({
    isExported: true,
    declarationKind: VariableDeclarationKind.Const,
    docs: [`A React component that renders an \`${tagName}\` custom element.\n\n@public`],
    declarations: [
      {
        name: componentName,
        type: `ForwardRefExoticComponent<${componentName}Props & RefAttributes<${componentName}Element>>`,
        initializer: `/* @__PURE__ */ forwardRef(${componentName}Component)`,
      },
    ],
  })

  addEventTypeReExports(sourceFile, component, options.importSource)
}

function generatePreactComponentFile(
  sourceFile: SourceFile,
  component: ComponentInfo,
  options: GenerateOptions,
): void {
  const slots = getWrapperExtensionSlots(component, options)
  const {
    componentName,
    tagName,
    hasEvents,
    hasProps,
    props,
    eventHandlers,
  } = getComponentMeta(component, options.prefix)

  sourceFile.addImportDeclaration({
    moduleSpecifier: '@aria-ui-v2/integrations/preact',
    namedImports: ['PreactWrapper'],
  })

  sourceFile.addImportDeclaration({
    moduleSpecifier: 'preact',
    namedImports: [
      'createElement',
      { name: 'HTMLAttributes', isTypeOnly: true },
      { name: 'Ref', isTypeOnly: true },
    ],
  })

  sourceFile.addImportDeclaration({
    moduleSpecifier: 'preact/compat',
    namedImports: [
      'forwardRef',
      { name: 'ForwardRefExoticComponent', isTypeOnly: true },
      { name: 'RefAttributes', isTypeOnly: true },
    ],
  })

  const { propsTypeName, eventsTypeName } = addSourceFileImports({
    sourceFile,
    component,
    importSource: options.importSource,
    order: 'props-first',
    includeRegister: true,
    includeElementType: true,
  })
  addWrapperImports(sourceFile, slots.imports)

  addPropNamesVariable(sourceFile, uneval(props.map((prop) => prop.name)))
  addEventNameMapVariable(
    sourceFile,
    uneval(Object.fromEntries(eventHandlers.map((h) => [h.handlerName, h.eventName]))),
  )

  addPropsInterface({
    sourceFile,
    component,
    name: `${componentName}Props`,
    docs: [`Props for the {@link ${componentName}} Preact component.\n\n@public`],
    extendsTypes: [`HTMLAttributes<${componentName}Element>`],
    propsTypeName: hasProps ? propsTypeName : undefined,
    eventsTypeName: hasEvents ? eventsTypeName : undefined,
  })

  const renderPropsExpression = slots.renderPropsExpression ?? 'props'
  const wrapperPropsArgument = renderPropsExpression === 'props'
    ? 'props'
    : `props: ${renderPropsExpression}`
  const statements = [
    `register${componentName}Element();`,
    ...slots.setupStatements,
    `return createElement(PreactWrapper, { as: '${tagName}', propNames, eventNameMap, ${wrapperPropsArgument}, forwardedRef });`,
  ]

  sourceFile.addFunction({
    name: `${componentName}Component`,
    parameters: [
      { name: 'props', type: `${componentName}Props` },
      { name: 'forwardedRef', type: `Ref<${componentName}Element>` },
    ],
    statements,
  })

  sourceFile.addVariableStatement({
    isExported: true,
    declarationKind: VariableDeclarationKind.Const,
    docs: [`A Preact component that renders an \`${tagName}\` custom element.\n\n@public`],
    declarations: [
      {
        name: componentName,
        type: `ForwardRefExoticComponent<${componentName}Props & RefAttributes<${componentName}Element>>`,
        initializer: `/* @__PURE__ */ forwardRef(${componentName}Component)`,
      },
    ],
  })

  addEventTypeReExports(sourceFile, component, options.importSource)
}

function generateSolidComponentFile(
  sourceFile: SourceFile,
  component: ComponentInfo,
  options: GenerateOptions,
): void {
  const slots = getWrapperExtensionSlots(component, options)
  const {
    componentName,
    tagName,
    hasEvents,
    hasProps,
    props,
    eventHandlers,
  } = getComponentMeta(component, options.prefix)

  const { propsTypeName, eventsTypeName } = addSourceFileImports({
    sourceFile,
    component,
    importSource: options.importSource,
    order: 'events-first',
    includeRegister: true,
    includeElementType: true,
  })

  const needsSplitProps = hasProps || hasEvents

  if (needsSplitProps) {
    sourceFile.addImportDeclaration({
      moduleSpecifier: 'solid-js',
      namedImports: ['mergeProps', 'splitProps'],
    })
  }

  sourceFile.addImportDeclaration({
    moduleSpecifier: 'solid-js',
    namedImports: ['Component', 'JSX'],
    isTypeOnly: true,
  })

  sourceFile.addImportDeclaration({
    moduleSpecifier: 'solid-js/h',
    defaultImport: 'h',
  })
  addWrapperImports(sourceFile, slots.imports)

  addPropsInterface({
    sourceFile,
    component,
    name: `${componentName}Props`,
    docs: [`Props for the {@link ${componentName}} Solid component.\n\n@public`],
    extendsTypes: [`JSX.HTMLAttributes<${componentName}Element>`],
    propsTypeName: hasProps ? propsTypeName : undefined,
    eventsTypeName: hasEvents ? eventsTypeName : undefined,
  })

  const propNames = props.map((prop) => prop.name)
  const eventHandlerNames = eventHandlers.map((handler) => handler.handlerName)
  const splitPropsArgs = [
    ...(propNames.length > 0 ? [uneval(propNames)] : []),
    ...(eventHandlerNames.length > 0 ? [uneval(eventHandlerNames)] : []),
  ]
  const splitPropsTargets = [
    ...(propNames.length > 0 ? ['elementProps'] : []),
    ...(eventHandlerNames.length > 0 ? ['eventHandlers'] : []),
    'restProps',
  ]
  const splitPropsStatement = splitPropsArgs.length > 0
    ? `const [ ${splitPropsTargets.join(', ')} ] = splitProps(props, ${splitPropsArgs.join(', ')})`
    : 'const restProps = props'
  const propEntries = props.map(
    (prop) => `"prop:${prop.name}": ${slots.solidPropOverrides[prop.name] ?? `() => elementProps.${prop.name}`}`,
  )
  const eventEntries = eventHandlers.map(
    (handler) =>
      `"on:${handler.eventName}": (event: ${eventsTypeName}['${handler.eventName}']) => eventHandlers.${handler.handlerName}?.(event)`,
  )
  const elementPropsObject = `{${[...propEntries, ...eventEntries].join(', ')}}`
  const mergedProps = propEntries.length > 0 || eventEntries.length > 0
    ? `mergeProps(restProps, ${elementPropsObject})`
    : 'restProps'
  const setupStatements = joinStatements(slots.setupStatements)
  const setupBlock = setupStatements.length > 0 ? `\n\n${setupStatements}` : ''

  const componentInitializer = `(props): any => {
register${componentName}Element()

${splitPropsStatement}
${setupBlock}

return h(
  '${tagName}',
  ${mergedProps},
)
}`

  sourceFile.addVariableStatement({
    isExported: true,
    declarationKind: VariableDeclarationKind.Const,
    docs: [`A Solid component that renders an \`${tagName}\` custom element.\n\n@public`],
    declarations: [
      {
        name: componentName,
        type: `Component<${componentName}Props>`,
        initializer: componentInitializer,
      },
    ],
  })

  addEventTypeReExports(sourceFile, component, options.importSource)
}

function generateVueComponentFile(
  sourceFile: SourceFile,
  component: ComponentInfo,
  options: GenerateOptions,
): void {
  const slots = getWrapperExtensionSlots(component, options)
  const {
    componentName,
    tagName,
    hasEvents,
    hasProps,
    props,
    eventHandlers,
  } = getComponentMeta(component, options.prefix)

  sourceFile.addImportDeclaration({
    moduleSpecifier: 'vue',
    namedImports: [
      'defineComponent',
      'h',
      { name: 'DefineSetupFnComponent', isTypeOnly: true },
      { name: 'HTMLAttributes', isTypeOnly: true },
    ],
  })

  const propsDeclarationName = `${componentName}PropsDeclaration`

  const { propsTypeName, eventsTypeName } = addSourceFileImports({
    sourceFile,
    component,
    importSource: options.importSource,
    order: 'events-first',
    includeRegister: true,
    includeElementType: false,
    includePropsDeclaration: true,
  })
  addWrapperImports(sourceFile, slots.imports)

  addPropsInterface({
    sourceFile,
    component,
    name: `${componentName}Props`,
    docs: [`Props for the {@link ${componentName}} Vue component.\n\n@public`],
    propsTypeName: hasProps ? propsTypeName : undefined,
    eventsTypeName: hasEvents ? eventsTypeName : undefined,
  })

  const propNames = props.map((prop) => prop.name)
  const eventHandlerNames = eventHandlers.map((handler) => handler.handlerName)

  // Build Vue props option as object with defaults from PropsDeclaration
  const propsEntries: string[] = []
  for (const name of propNames) {
    propsEntries.push(`${name}: { default: ${propsDeclarationName}.${name}.default }`)
  }
  for (const name of eventHandlerNames) {
    propsEntries.push(`${name}: { type: Function }`)
  }
  const componentPropsInitializer = propsEntries.length > 0
    ? `({ ${propsEntries.join(', ')} }) as Record<string, unknown>`
    : '([])'

  let buildPropsBlock: string
  if (propNames.length > 0 || hasEvents) {
    const propSwitchCases = propNames.map((name) => `case ${JSON.stringify(name)}:`).join('\n          ')
    const eventSwitchCases = eventHandlers.map((handler) => `case ${JSON.stringify(handler.handlerName)}:`).join('\n          ')

    const allSwitchCases: string[] = []
    if (propNames.length > 0) {
      allSwitchCases.push(`${propSwitchCases}
          _props['.' + key] = value
          break`)
    }
    if (hasEvents) {
      allSwitchCases.push(`${eventSwitchCases}
          _eventHandlers[key] = value as Function
          break`)
    }

    buildPropsBlock = `const _props: Record<string, unknown> = {}
    for (const [key, value] of Object.entries(props)) {
      switch (key) {
        ${allSwitchCases.join('\n        ')}
        default:
          _props[key] = value
      }
    }`
  } else {
    buildPropsBlock = `const _props = { ...props }`
  }

  // Build event handling setup block (eventHandlers record + ref callback with addEventListener)
  let eventSetupBlock = ''
  let eventRefBlock = ''
  if (hasEvents) {
    const addEventListenerCalls = eventHandlers.map(
      (handler) =>
        `element.addEventListener(${JSON.stringify(handler.eventName)}, (event) => { _eventHandlers[${
          JSON.stringify(handler.handlerName)
        }]?.(event) }, { signal: abortSignal })`,
    )

    eventSetupBlock = `  const _eventHandlers: Record<string, Function> = {}

  const _ref = (element: HTMLElement | null | undefined) => {
    if (!element) {
      return
    }

    const abortController = new AbortController()
    const abortSignal = abortController.signal

    ${addEventListenerCalls.join('\n    ')}

    return () => {
      abortController.abort()
    }
  }

`
    eventRefBlock = `\n    _props["ref"] = _ref`
  }

  const setupStatements = joinStatements(slots.setupStatements)
  const setupBlock = setupStatements.length > 0
    ? `${indentBlock(setupStatements, 2)}\n\n`
    : ''
  const postBuildPropsStatements = joinStatements(slots.vuePostBuildPropsStatements)
  const postBuildPropsBlock = postBuildPropsStatements.length > 0
    ? `\n${indentBlock(postBuildPropsStatements, 4)}`
    : ''

  const componentInitializer = `/* @__PURE__ */ defineComponent<${componentName}Props & HTMLAttributes>(
(props, { slots }) => {
  register${componentName}Element()
${setupBlock}${eventSetupBlock}
  return () => {
    ${buildPropsBlock}
${postBuildPropsBlock}${eventRefBlock}
    return h('${tagName}', _props, slots.default?.())
  }
},
{ props: ${componentPropsInitializer} },
)`

  sourceFile.addVariableStatement({
    isExported: true,
    declarationKind: VariableDeclarationKind.Const,
    docs: [`A Vue component that renders an \`${tagName}\` custom element.\n\n@public`],
    declarations: [
      {
        name: componentName,
        type: `DefineSetupFnComponent<${componentName}Props & HTMLAttributes>`,
        initializer: componentInitializer,
      },
    ],
  })

  addEventTypeReExports(sourceFile, component, options.importSource)
}

function generateSvelteComponentFile(
  sourceFile: SourceFile,
  component: ComponentInfo,
  options: GenerateOptions,
): void {
  const { componentName, kebabName, tagName, hasEvents, hasProps } = getComponentMeta(component, options.prefix)

  sourceFile.addImportDeclaration({
    moduleSpecifier: `./${kebabName}.gen.svelte`,
    defaultImport: `${componentName}Component`,
  })

  const { propsTypeName, eventsTypeName } = addSourceFileImports({
    sourceFile,
    component,
    importSource: options.importSource,
    order: 'events-first',
    includeRegister: false,
    includeElementType: false,
  })

  sourceFile.addImportDeclaration({
    moduleSpecifier: 'svelte',
    isTypeOnly: true,
    namedImports: ['Component', 'Snippet'],
  })

  addPropsInterface({
    sourceFile,
    component,
    name: `${componentName}Props`,
    docs: [`Props for the {@link ${componentName}} Svelte component.\n\n@public`],
    propsTypeName: hasProps ? propsTypeName : undefined,
    eventsTypeName: hasEvents ? eventsTypeName : undefined,
    includeChildren: true,
  })

  sourceFile.addVariableStatement({
    isExported: true,
    declarationKind: VariableDeclarationKind.Const,
    docs: [`A Svelte component that renders an \`${tagName}\` custom element.\n\n@public`],
    declarations: [
      {
        name: componentName,
        type: `Component<${componentName}Props>`,
        initializer: `${componentName}Component as unknown as Component<${componentName}Props>`,
      },
    ],
  })

  addEventTypeReExports(sourceFile, component, options.importSource)
}

function generateSvelteComponentSvelteFile(component: ComponentInfo, options: GenerateOptions): string {
  const slots = getWrapperExtensionSlots(component, options)
  const { componentName, tagName, props, eventHandlers } = getComponentMeta(component, options.prefix)
  const propBindings = props.map((prop, index) => ({
    name: prop.name,
    variableName: `p${index}`,
  }))
  const eventBindings = eventHandlers.map((handler, index) => ({
    eventName: handler.eventName,
    handlerName: handler.handlerName,
    variableName: `p${propBindings.length + index}`,
  }))
  const destructureEntries = [
    ...propBindings.map((binding) => `${binding.name}: ${binding.variableName}`),
    ...eventBindings.map((binding) => `${binding.handlerName}: ${binding.variableName}`),
    'children = undefined',
    '...restProps',
  ]
  const destructureProps = `  let { ${destructureEntries.join(', ')} } = $props()`
  const extensionImports = slots.imports.map(
    (item) => `  import { ${item.namedImports.join(', ')} } from '${item.moduleSpecifier}'`,
  )
  const scriptStatements = slots.svelteScriptStatements.map((statement) => indentBlock(statement, 2))
  const propStatements = propBindings.map((binding) => {
    const expression = slots.sveltePropExpressions[binding.name]
    if (!expression) {
      return `    if (${binding.variableName} !== undefined) { element.${binding.name} = ${binding.variableName} }`
    }

    return `    {
      const propValue = ${binding.variableName}
      const value = ${expression}
      if (value !== undefined) {
        element.${binding.name} = value
      }
    }`
  })
  const eventStatements = eventBindings.map(
    (binding) =>
      `    if (${binding.variableName} !== undefined) { element.addEventListener('${binding.eventName}', ${binding.variableName}, { signal: abortSignal }) }`,
  )
  const needsAttachment = propStatements.length > 0 || eventStatements.length > 0
  const attachmentBlocks: string[] = []

  if (eventStatements.length > 0) {
    attachmentBlocks.push(`    const abortController = new AbortController()
    const abortSignal = abortController.signal`)
  }

  if (propStatements.length > 0 || eventStatements.length > 0) {
    attachmentBlocks.push([...propStatements, ...eventStatements].join('\n\n'))
  }

  if (eventStatements.length > 0) {
    attachmentBlocks.push(`    return () => {
      abortController.abort()
    }`)
  }

  const attachmentLines = needsAttachment
    ? [
      '',
      `  const attachment = (element) => {`,
      '    if (!element) return',
      ...(attachmentBlocks.length > 0 ? ['', attachmentBlocks.join('\n\n')] : []),
      '  }',
    ]
    : []
  const openingTag = needsAttachment
    ? `<${tagName} {...restProps} {@attach attachment}`
    : `<${tagName} {...restProps}`
  const scriptLines = [
    `<script lang="js">`,
    `  import { register${componentName}Element } from '${options.importSource}'`,
    ...extensionImports,
    `  register${componentName}Element()`,
    '',
    destructureProps,
    ...(
      scriptStatements.length > 0
        ? ['', ...scriptStatements]
        : []
    ),
    ...attachmentLines,
    `</script>`,
  ]

  return `${scriptLines.join('\n')}

${openingTag}>{@render children?.()}</${tagName}>
`
}

function getComponentMeta(component: ComponentInfo, prefix: string): ComponentMeta {
  const componentName = component.name
  const kebabName = toKebabCase(componentName)
  const props = [...component.props].sort((a, b) => a.name.localeCompare(b.name))
  const events = [...component.events].sort((a, b) => a.name.localeCompare(b.name))
  return {
    componentName,
    kebabName,
    tagName: `${prefix}-${kebabName}`,
    props,
    events,
    hasProps: props.length > 0,
    hasEvents: events.length > 0,
    eventHandlers: events.map((event) => {
      const handlerName = toEventHandlerName(event.name)
      return {
        eventName: event.name,
        handlerName,
      }
    }),
  }
}

function addSourceFileImports(
  options: SourceImportOptions,
): { propsTypeName: string; eventsTypeName: string } {
  const {
    sourceFile,
    component,
    importSource,
    order,
    includeRegister,
    includeElementType,
    includePropsDeclaration,
  } = options
  const componentName = component.name
  const propsTypeName = `${componentName}ElementProps`
  const eventsTypeName = `${componentName}Events`

  const namedImports: Array<{ name: string; alias?: string; isTypeOnly?: boolean }> = []

  if (includeRegister) {
    namedImports.push({ name: `register${componentName}Element` })
  }

  if (includeElementType) {
    namedImports.push({ name: `${componentName}Element`, isTypeOnly: true })
  }

  const propsImport = component.props.length > 0
    ? { name: `${componentName}Props`, alias: propsTypeName, isTypeOnly: true }
    : null
  const eventsImport = component.events.length > 0
    ? { name: `${componentName}Events`, isTypeOnly: true }
    : null

  if (order === 'props-first') {
    if (propsImport) namedImports.push(propsImport)
    if (eventsImport) namedImports.push(eventsImport)
  } else {
    if (eventsImport) namedImports.push(eventsImport)
    if (propsImport) namedImports.push(propsImport)
  }

  if (includePropsDeclaration && component.props.length > 0) {
    namedImports.push({ name: `${componentName}PropsDeclaration` })
  }

  if (namedImports.length > 0) {
    sourceFile.addImportDeclaration({
      moduleSpecifier: importSource,
      namedImports,
    })
  }

  return { propsTypeName, eventsTypeName }
}

function addPropsInterface(options: PropsInterfaceOptions): void {
  const {
    sourceFile,
    component,
    name,
    docs,
    extendsTypes,
    propsTypeName,
    eventsTypeName,
    includeChildren,
  } = options
  const propsInterface = sourceFile.addInterface({
    name,
    isExported: true,
    extends: extendsTypes,
    docs,
  })

  if (propsTypeName) {
    for (const prop of component.props) {
      propsInterface.addProperty({
        name: prop.name,
        type: `${propsTypeName}['${prop.name}']`,
        hasQuestionToken: true,
        docs: [prop.comment],
      })
    }
  }

  if (eventsTypeName) {
    for (const event of component.events) {
      const eventHandlerName = toEventHandlerName(event.name)
      propsInterface.addProperty({
        name: eventHandlerName,
        type: `(event: ${eventsTypeName}['${event.name}']) => void`,
        hasQuestionToken: true,
        docs: [event.comment],
      })
    }
  }

  if (includeChildren) {
    propsInterface.addProperty({
      name: 'children',
      type: 'Snippet',
      hasQuestionToken: true,
    })
    // TODO: is there any way that we can add correct HTML element props without using "unknonwn"?
    propsInterface.addIndexSignature({
      keyName: 'key',
      keyType: 'string',
      returnType: 'unknown',
    })
  }
}

function addPropNamesVariable(
  sourceFile: SourceFile,
  initializer: string,
): void {
  sourceFile.addVariableStatement({
    declarationKind: VariableDeclarationKind.Const,
    declarations: [
      {
        name: 'propNames',
        type: 'string[]',
        initializer,
      },
    ],
  })
}

function addEventNameMapVariable(
  sourceFile: SourceFile,
  initializer: string,
): void {
  sourceFile.addVariableStatement({
    declarationKind: VariableDeclarationKind.Const,
    declarations: [
      {
        name: 'eventNameMap',
        type: 'Record<string, string>',
        initializer,
      },
    ],
  })
}

function generateIndexFile(components: ComponentInfo[]): string {
  const lines: string[] = []
  const exportedEventTypes = new Set<string>()

  for (const component of components) {
    const fileName = getComponentFileName(component)
    const componentName = component.name
    const exports = [componentName, `type ${componentName}Props`]

    if (component.events.length > 0) {
      exports.push(`type ${componentName}Events`)
    }

    for (const event of component.events) {
      if (event.typeName && !exportedEventTypes.has(event.typeName)) {
        exportedEventTypes.add(event.typeName)
        exports.push(event.typeName)
      }
    }

    lines.push(
      `export { ${exports.join(', ')} } from './${fileName}'`,
    )
  }
  return lines.join('\n\n') + '\n'
}

function addEventTypeReExports(
  sourceFile: SourceFile,
  component: ComponentInfo,
  importSource: string,
): void {
  if (component.events.length === 0) return

  // Re-export the events interface type (e.g., PopoverRootEvents)
  const eventsTypeName = `${component.name}Events`
  sourceFile.addExportDeclaration({
    isTypeOnly: true,
    namedExports: [eventsTypeName],
  })

  // Re-export event classes (e.g., OpenChangeEvent)
  const eventTypeNames = getUniqueEventTypeNames(component)
  if (eventTypeNames.length > 0) {
    sourceFile.addExportDeclaration({
      moduleSpecifier: importSource,
      namedExports: eventTypeNames,
    })
  }
}

function getUniqueEventTypeNames(component: ComponentInfo): string[] {
  const seen = new Set<string>()
  for (const event of component.events) {
    if (event.typeName) {
      seen.add(event.typeName)
    }
  }
  return [...seen].sort()
}

function getComponentFileName(component: ComponentInfo): string {
  return `${toKebabCase(component.name)}.gen.ts`
}

function getSvelteComponentFileName(component: ComponentInfo): string {
  return `${toKebabCase(component.name)}.gen.svelte`
}

function toEventHandlerName(eventName: string): string {
  return `on${eventName.charAt(0).toUpperCase()}${eventName.slice(1)}`
}

function toKebabCase(str: string): string {
  return str.replaceAll(/([a-z])([A-Z])/g, '$1-$2').toLowerCase()
}
