/**
 * This file is auto-generated by the "@aria-ui/cli" tool. Do not edit this file directly.
 */

import {
  createElement,
  forwardRef,
  useCallback,
  useRef,
  type ForwardedRef,
  type ForwardRefExoticComponent,
  type HTMLAttributes,
  type RefAttributes,
  useLayoutEffect,
} from "react";
import {
  registerBlockHandlePopoverElement,
  type BlockHandlePopoverElement,
  type BlockHandlePopoverProps as BlockHandlePopoverElementProps,
  type BlockHandlePopoverEvents,
} from "@prosekit/web/block-handle";
import { useEditorContext } from "../../contexts/editor-context.ts";

/**
 * Props for the {@link BlockHandlePopover} React component.
 *
 * @public
 */
export interface BlockHandlePopoverProps extends HTMLAttributes<BlockHandlePopoverElement> {
  /**
   * The ProseKit editor instance.
   *
   * @default null
   * @hidden
   */
  editor?: BlockHandlePopoverElementProps["editor"];
  /**
   * The placement of the popover, relative to the hovered block.
   *
   * @default "left"
   */
  placement?: BlockHandlePopoverElementProps["placement"];
  /**
   * Whether to use the browser [Popover API](https://developer.mozilla.org/en-US/docs/Web/API/Popover_API)
   * to place the floating element on top of other page content.
   *
   * @default false
   */
  hoist?: BlockHandlePopoverElementProps["hoist"];
  /**
   * @default false
   * @hidden
   */
  flip?: BlockHandlePopoverElementProps["flip"];
  /**
   * @default false
   * @hidden
   */
  shift?: BlockHandlePopoverElementProps["shift"];
  /**
   * @default true
   * @hidden
   */
  hide?: BlockHandlePopoverElementProps["hide"];
  /**
   * The strategy to use for positioning
   *
   * @default "absolute"
   */
  strategy?: BlockHandlePopoverElementProps["strategy"];
  /**
   * Options to activate auto-update listeners
   *
   * @see https://floating-ui.com/docs/autoUpdate
   *
   * @default true
   */
  autoUpdate?: BlockHandlePopoverElementProps["autoUpdate"];
  /**
   * The distance between the reference and floating element.
   *
   * @default 6
   */
  offset?: BlockHandlePopoverElementProps["offset"];
  /**
   * Whether the floating element can overlap the reference element to keep it
   * in view.
   *
   * @default false
   */
  overlap?: BlockHandlePopoverElementProps["overlap"];
  /**
   * Whether to constrain the floating element's width and height to not exceed
   * the viewport.
   *
   * @default false
   */
  fitViewport?: BlockHandlePopoverElementProps["fitViewport"];
  /**
   * Whether to constrain the floating element's width so that it matches the
   * reference element.
   *
   * @default false
   */
  sameWidth?: BlockHandlePopoverElementProps["sameWidth"];
  /**
   * Whether to constrain the floating element's height so that it matches the
   * reference element.
   *
   * @default false
   */
  sameHeight?: BlockHandlePopoverElementProps["sameHeight"];
  /**
   * Whether to improve positioning for inline reference elements that span over
   * multiple lines.
   *
   * @default false
   */
  inline?: BlockHandlePopoverElementProps["inline"];
  /**
   * Describes the clipping element(s) or area that overflow will be checked relative to.
   * Please see https://floating-ui.com/docs/detectoverflow#boundary for more information.
   *
   * @default 'clippingAncestors'
   */
  boundary?: BlockHandlePopoverElementProps["boundary"];
  /**
   * Describes the root boundary that the element will be checked for overflow relative to.
   * Please see https://floating-ui.com/docs/detectoverflow#rootboundary for more information.
   *
   * @default 'viewport'
   */
  rootBoundary?: BlockHandlePopoverElementProps["rootBoundary"];
  /**
   * Describes the virtual padding around the boundary to check for overflow.
   * Please see https://floating-ui.com/docs/detectoverflow#padding for more information.
   *
   * @default 4
   */
  overflowPadding?: BlockHandlePopoverElementProps["overflowPadding"];
  /**
   * The element that will be used to check for overflow. Please see
   * https://floating-ui.com/docs/detectoverflow#elementcontext for more
   * information.
   *
   * @default 'floating'
   */
  elementContext?: BlockHandlePopoverElementProps["elementContext"];
  /**
   * Whether to check the alternate elementContext's boundary. Please see
   * https://floating-ui.com/docs/detectoverflow#altboundary for more
   * information.
   *
   * @default false
   */
  altBoundary?: BlockHandlePopoverElementProps["altBoundary"];
  /** Fired when the hovered block changes. */
  onStateChange?: (event: BlockHandlePopoverEvents["stateChange"]) => void;
}

function BlockHandlePopoverComponent(
  props: BlockHandlePopoverProps,
  forwardedRef: ForwardedRef<BlockHandlePopoverElement>,
) {
  registerBlockHandlePopoverElement();

  const elementRef = useRef<BlockHandlePopoverElement>(null);
  const handlersRef = useRef<Array<((event: Event) => void) | undefined>>([]);

  const p3Fallback = useEditorContext();

  const {
    altBoundary: p0,
    autoUpdate: p1,
    boundary: p2,
    editor: p3,
    elementContext: p4,
    fitViewport: p5,
    flip: p6,
    hide: p7,
    hoist: p8,
    inline: p9,
    offset: p10,
    overflowPadding: p11,
    overlap: p12,
    placement: p13,
    rootBoundary: p14,
    sameHeight: p15,
    sameWidth: p16,
    shift: p17,
    strategy: p18,
    onStateChange: e0,
    ...restProps
  } = props;

  useLayoutEffect(() => {
    const element = elementRef.current as Record<string, unknown> | null;
    if (!element) return;
    Object.assign(element, {
      altBoundary: p0,
      autoUpdate: p1,
      boundary: p2,
      editor: p3 ?? p3Fallback,
      elementContext: p4,
      fitViewport: p5,
      flip: p6,
      hide: p7,
      hoist: p8,
      inline: p9,
      offset: p10,
      overflowPadding: p11,
      overlap: p12,
      placement: p13,
      rootBoundary: p14,
      sameHeight: p15,
      sameWidth: p16,
      shift: p17,
      strategy: p18,
    });
    handlersRef.current = [e0] as Array<((event: Event) => void) | undefined>;
  });

  useLayoutEffect(() => {
    const element = elementRef.current;
    if (!element) return;
    const ac = new AbortController();
    for (const [index, eventName] of ["stateChange"].entries()) {
      element.addEventListener(
        eventName,
        (event: Event) => {
          handlersRef.current[index]?.(event);
        },
        { signal: ac.signal },
      );
    }
    return () => ac.abort();
  }, []);

  const mergedRef = useCallback((element: BlockHandlePopoverElement | null) => {
    elementRef.current = element;
    if (typeof forwardedRef === "function") {
      forwardedRef(element);
    } else if (forwardedRef) {
      forwardedRef.current = element;
    }
  }, []);

  return createElement("prosekit-block-handle-popover", {
    ...restProps,
    ref: mergedRef,
    suppressHydrationWarning: true,
  });
}

/**
 * A React component that renders an `prosekit-block-handle-popover` custom element.
 *
 * @public
 */
export const BlockHandlePopover: ForwardRefExoticComponent<
  BlockHandlePopoverProps & RefAttributes<BlockHandlePopoverElement>
> = /* @__PURE__ */ forwardRef(BlockHandlePopoverComponent);

export type { BlockHandlePopoverEvents };
export { BlockHandlePopoverStateChangeEvent } from "@prosekit/web/block-handle";
