/**
 * This file is auto-generated by the "@aria-ui/cli" tool. Do not edit this file directly.
 */

import { registerTableHandleDragPreviewElement, type TableHandleDragPreviewElement, type TableHandleDragPreviewProps as TableHandleDragPreviewElementProps } from '@prosekit/web/table-handle';
import { createElement, type HTMLAttributes, type Ref } from 'preact';
import { forwardRef, type ForwardRefExoticComponent, type RefAttributes } from 'preact/compat';
import { useCallback, useRef, useLayoutEffect } from 'preact/hooks';

import { useEditorContext } from '../../contexts/editor-context.ts';

/**
 * Props for the {@link TableHandleDragPreview} Preact component.
 *
 * @public
 */
export interface TableHandleDragPreviewProps extends HTMLAttributes<TableHandleDragPreviewElement> {
  /**
   * @default null
   * @hidden
   */
  editor?: TableHandleDragPreviewElementProps['editor'];
}

function TableHandleDragPreviewComponent(props: TableHandleDragPreviewProps, forwardedRef: Ref<TableHandleDragPreviewElement>) {
  registerTableHandleDragPreviewElement();

  const elementRef = useRef<TableHandleDragPreviewElement>(null);

  const p0Fallback = useEditorContext();

  const { editor: p0, ...restProps } = props;

  useLayoutEffect(() => {
    const element = elementRef.current as Record<string, unknown> | null;
    if (!element) return;
    Object.assign(element, { editor: p0 ?? p0Fallback });
  });

  const mergedRef = useCallback(
    (element: TableHandleDragPreviewElement | null) => {
      elementRef.current = element;
      if (typeof forwardedRef === 'function') {
        forwardedRef(element);
      } else if (forwardedRef) {
        forwardedRef.current = element;
      }
    },
    [forwardedRef],
  );

  return createElement('prosekit-table-handle-drag-preview', { ...restProps, ref: mergedRef, suppressHydrationWarning: true });
}

/**
 * A Preact component that renders an `prosekit-table-handle-drag-preview` custom element.
 *
 * @public
 */
export const TableHandleDragPreview: ForwardRefExoticComponent<TableHandleDragPreviewProps & RefAttributes<TableHandleDragPreviewElement>> = /* @__PURE__ */ forwardRef(TableHandleDragPreviewComponent);
