/**
 * This file is auto-generated by the "@aria-ui/cli" tool. Do not edit this file directly.
 */

import { registerTableHandleColumnPopupElement, type TableHandleColumnPopupElement } from '@prosekit/web/table-handle';
import { createElement, type HTMLAttributes, type Ref } from 'preact';
import { forwardRef, type ForwardRefExoticComponent, type RefAttributes } from 'preact/compat';
import { useCallback, useRef } from 'preact/hooks';

/**
 * Props for the {@link TableHandleColumnPopup} Preact component.
 *
 * @public
 */
export interface TableHandleColumnPopupProps {}

function TableHandleColumnPopupComponent(props: TableHandleColumnPopupProps, forwardedRef: Ref<TableHandleColumnPopupElement>) {
  registerTableHandleColumnPopupElement();

  const elementRef = useRef<TableHandleColumnPopupElement>(null);

  const { ...restProps } = props;

  const mergedRef = useCallback(
    (element: TableHandleColumnPopupElement | null) => {
      elementRef.current = element;
      if (typeof forwardedRef === 'function') {
        forwardedRef(element);
      } else if (forwardedRef) {
        forwardedRef.current = element;
      }
    },
    [forwardedRef],
  );

  return createElement('prosekit-table-handle-column-popup', { ...restProps, ref: mergedRef, suppressHydrationWarning: true });
}

/**
 * A Preact component that renders an `prosekit-table-handle-column-popup` custom element.
 *
 * @public
 */
export const TableHandleColumnPopup: ForwardRefExoticComponent<TableHandleColumnPopupProps & HTMLAttributes<TableHandleColumnPopupElement> & RefAttributes<TableHandleColumnPopupElement>> = /* @__PURE__ */ forwardRef(TableHandleColumnPopupComponent);
