/**
 * This file is auto-generated by the "@aria-ui/cli" tool. Do not edit this file directly.
 */

import { createElement, type HTMLAttributes, type Ref } from "preact";
import {
  forwardRef,
  type ForwardRefExoticComponent,
  type RefAttributes,
} from "preact/compat";
import { useCallback, useRef, useLayoutEffect } from "preact/hooks";
import {
  registerTableHandleColumnTriggerElement,
  type TableHandleColumnTriggerElement,
  type TableHandleColumnTriggerProps as TableHandleColumnTriggerElementProps,
} from "@prosekit/web/table-handle";
import { useEditorContext } from "../../contexts/editor-context.ts";

/**
 * Props for the {@link TableHandleColumnTrigger} Preact component.
 *
 * @public
 */
export interface TableHandleColumnTriggerProps extends HTMLAttributes<TableHandleColumnTriggerElement> {
  /**
   * @default null
   * @hidden
   */
  editor?: TableHandleColumnTriggerElementProps["editor"];
}

function TableHandleColumnTriggerComponent(
  props: TableHandleColumnTriggerProps,
  forwardedRef: Ref<TableHandleColumnTriggerElement>,
) {
  registerTableHandleColumnTriggerElement();

  const elementRef = useRef<TableHandleColumnTriggerElement>(null);

  const p0Fallback = useEditorContext();

  const { editor: p0, ...restProps } = props;

  useLayoutEffect(() => {
    const element = elementRef.current as Record<string, unknown> | null;
    if (!element) return;
    Object.assign(element, { editor: p0 ?? p0Fallback });
  });

  const mergedRef = useCallback(
    (element: TableHandleColumnTriggerElement | null) => {
      elementRef.current = element;
      if (typeof forwardedRef === "function") {
        forwardedRef(element);
      } else if (forwardedRef) {
        forwardedRef.current = element;
      }
    },
    [],
  );

  return createElement("prosekit-table-handle-column-trigger", {
    ...restProps,
    ref: mergedRef,
    suppressHydrationWarning: true,
  });
}

/**
 * A Preact component that renders an `prosekit-table-handle-column-trigger` custom element.
 *
 * @public
 */
export const TableHandleColumnTrigger: ForwardRefExoticComponent<
  TableHandleColumnTriggerProps & RefAttributes<TableHandleColumnTriggerElement>
> = /* @__PURE__ */ forwardRef(TableHandleColumnTriggerComponent);
