/**
 * This file is auto-generated by the "@aria-ui/cli" tool. Do not edit this file directly.
 */

import { PreactWrapper } from "@aria-ui-v2/integrations/preact";
import { createElement, type HTMLAttributes, type Ref } from "preact";
import {
  forwardRef,
  type ForwardRefExoticComponent,
  type RefAttributes,
} from "preact/compat";
import {
  registerTableHandleRowTriggerElement,
  type TableHandleRowTriggerElement,
  type TableHandleRowTriggerProps as TableHandleRowTriggerElementProps,
} from "@prosekit/web/table-handle";
import { useEditorContext } from "../../contexts/editor-context.ts";

const propNames: string[] = ["editor"];
const eventNameMap: Record<string, string> = {};

/**
 * Props for the {@link TableHandleRowTrigger} Preact component.
 *
 * @public
 */
export interface TableHandleRowTriggerProps extends HTMLAttributes<TableHandleRowTriggerElement> {
  /**
   * @default null
   * @hidden
   */
  editor?: TableHandleRowTriggerElementProps["editor"];
}

function TableHandleRowTriggerComponent(
  props: TableHandleRowTriggerProps,
  forwardedRef: Ref<TableHandleRowTriggerElement>,
) {
  registerTableHandleRowTriggerElement();
  const componentProps: TableHandleRowTriggerProps = { ...props };
  const editorContext = useEditorContext();
  if (componentProps.editor == null && editorContext != null) {
    componentProps.editor = editorContext;
  }

  return createElement(PreactWrapper, {
    as: "prosekit-table-handle-row-trigger",
    propNames,
    eventNameMap,
    props: componentProps,
    forwardedRef,
  });
}

/**
 * A Preact component that renders an `prosekit-table-handle-row-trigger` custom element.
 *
 * @public
 */
export const TableHandleRowTrigger: ForwardRefExoticComponent<
  TableHandleRowTriggerProps & RefAttributes<TableHandleRowTriggerElement>
> = /* @__PURE__ */ forwardRef(TableHandleRowTriggerComponent);
