/**
 * This file is auto-generated by the "@aria-ui/cli" tool. Do not edit this file directly.
 */

import { PreactWrapper } from "@aria-ui-v2/integrations/preact";
import { createElement, type HTMLAttributes, type Ref } from "preact";
import {
  forwardRef,
  type ForwardRefExoticComponent,
  type RefAttributes,
} from "preact/compat";
import {
  registerTableHandleRootElement,
  type TableHandleRootElement,
  type TableHandleRootProps as TableHandleRootElementProps,
} from "@prosekit/web/table-handle";
import { useEditorContext } from "../../contexts/editor-context.ts";

const propNames: string[] = ["editor"];
const eventNameMap: Record<string, string> = {};

/**
 * Props for the {@link TableHandleRoot} Preact component.
 *
 * @public
 */
export interface TableHandleRootProps extends HTMLAttributes<TableHandleRootElement> {
  /**
   * The ProseKit editor instance.
   *
   * @default null
   * @hidden
   */
  editor?: TableHandleRootElementProps["editor"];
}

function TableHandleRootComponent(
  props: TableHandleRootProps,
  forwardedRef: Ref<TableHandleRootElement>,
) {
  registerTableHandleRootElement();
  const componentProps: TableHandleRootProps = { ...props };
  const editorContext = useEditorContext();
  if (componentProps.editor == null && editorContext != null) {
    componentProps.editor = editorContext;
  }

  return createElement(PreactWrapper, {
    as: "prosekit-table-handle-root",
    propNames,
    eventNameMap,
    props: componentProps,
    forwardedRef,
  });
}

/**
 * A Preact component that renders an `prosekit-table-handle-root` custom element.
 *
 * @public
 */
export const TableHandleRoot: ForwardRefExoticComponent<
  TableHandleRootProps & RefAttributes<TableHandleRootElement>
> = /* @__PURE__ */ forwardRef(TableHandleRootComponent);
