/**
 * This file is auto-generated by the "@aria-ui/cli" tool. Do not edit this file directly.
 */

import { registerTableHandleRowMenuTriggerElement, type TableHandleRowMenuTriggerElement, type TableHandleRowMenuTriggerProps as TableHandleRowMenuTriggerElementProps } from '@prosekit/web/table-handle';
import { createElement, type HTMLAttributes, type Ref } from 'preact';
import { forwardRef, type ForwardRefExoticComponent, type RefAttributes } from 'preact/compat';
import { useCallback, useRef, useLayoutEffect } from 'preact/hooks';

import { useEditorContext } from '../../contexts/editor-context.ts';

/**
 * Props for the {@link TableHandleRowMenuTrigger} Preact component.
 *
 * @public
 */
export interface TableHandleRowMenuTriggerProps extends HTMLAttributes<TableHandleRowMenuTriggerElement> {
  /**
   * @default null
   * @hidden
   */
  editor?: TableHandleRowMenuTriggerElementProps['editor'];
}

function TableHandleRowMenuTriggerComponent(props: TableHandleRowMenuTriggerProps, forwardedRef: Ref<TableHandleRowMenuTriggerElement>) {
  registerTableHandleRowMenuTriggerElement();

  const elementRef = useRef<TableHandleRowMenuTriggerElement>(null);

  const p0Fallback = useEditorContext();

  const { editor: p0, ...restProps } = props;

  useLayoutEffect(() => {
    const element = elementRef.current as Record<string, unknown> | null;
    if (!element) return;
    Object.assign(element, { editor: p0 ?? p0Fallback });
  });

  const mergedRef = useCallback(
    (element: TableHandleRowMenuTriggerElement | null) => {
      elementRef.current = element;
      if (typeof forwardedRef === 'function') {
        forwardedRef(element);
      } else if (forwardedRef) {
        forwardedRef.current = element;
      }
    },
    [forwardedRef],
  );

  return createElement('prosekit-table-handle-row-menu-trigger', { ...restProps, ref: mergedRef, suppressHydrationWarning: true });
}

/**
 * A Preact component that renders an `prosekit-table-handle-row-menu-trigger` custom element.
 *
 * @public
 */
export const TableHandleRowMenuTrigger: ForwardRefExoticComponent<TableHandleRowMenuTriggerProps & RefAttributes<TableHandleRowMenuTriggerElement>> = /* @__PURE__ */ forwardRef(TableHandleRowMenuTriggerComponent);
