/**
 * This file is auto-generated by the "@aria-ui/cli" tool. Do not edit this file directly.
 */

import type { BlockHandleRootElement, BlockHandleRootEvents, BlockHandleRootProps as BlockHandleRootElementProps } from '@prosekit/web/block-handle';
import type { Component, Snippet } from 'svelte';
import type { HTMLAttributes } from 'svelte/elements';

import BlockHandleRootComponent from './block-handle-root.gen.svelte';

/**
 * Props for the {@link BlockHandleRoot} Svelte component.
 *
 * @public
 */
export interface BlockHandleRootProps {
  /**
   * The ProseKit editor instance.
   *
   * @default null
   * @hidden
   */
  editor?: BlockHandleRootElementProps['editor'];
  /** Fired when the hovered block changes. */
  onStateChange?: (event: BlockHandleRootEvents['stateChange']) => void;
  children?: Snippet;
}

/**
 * A Svelte component that renders an `prosekit-block-handle-root` custom element.
 *
 * @public
 */
export const BlockHandleRoot: Component<BlockHandleRootProps & HTMLAttributes<BlockHandleRootElement>> = BlockHandleRootComponent as Component<BlockHandleRootProps & HTMLAttributes<BlockHandleRootElement>>;
