/**
 * This file is auto-generated by the "@aria-ui/cli" tool. Do not edit this file directly.
 */

import type { BlockHandleAddProps as BlockHandleAddElementProps } from '@prosekit/web/block-handle';
import type { Component, Snippet } from 'svelte';

import BlockHandleAddComponent from './block-handle-add.gen.svelte';

/**
 * Props for the {@link BlockHandleAdd} Svelte component.
 *
 * @public
 */
export interface BlockHandleAddProps {
  /**
   * The ProseKit editor instance.
   *
   * @default null
   * @hidden
   */
  editor?: BlockHandleAddElementProps['editor'];
  children?: Snippet;
  [key: string]: unknown;
}

/**
 * A Svelte component that renders an `prosekit-block-handle-add` custom element.
 *
 * @public
 */
export const BlockHandleAdd: Component<BlockHandleAddProps> = BlockHandleAddComponent as unknown as Component<BlockHandleAddProps>;
