/**
 * This file is auto-generated by the "@aria-ui/cli" tool. Do not edit this file directly.
 */

import type { Component, Snippet } from 'svelte';

import BlockHandlePopupComponent from './block-handle-popup.gen.svelte';

/**
 * Props for the {@link BlockHandlePopup} Svelte component.
 *
 * @public
 */
export interface BlockHandlePopupProps {
  children?: Snippet;
  [key: string]: unknown;
}

/**
 * A Svelte component that renders an `prosekit-block-handle-popup` custom element.
 *
 * @public
 */
export const BlockHandlePopup: Component<BlockHandlePopupProps> = BlockHandlePopupComponent as unknown as Component<BlockHandlePopupProps>;
