<script lang="ts">
  // This file is auto-generated by "@aria-ui/cli". Do not edit this file directly.
  import { registerBlockHandlePopupElement } from '@prosekit/web/block-handle'
  registerBlockHandlePopupElement()

  let { children = undefined, ...restProps } = $props()
</script>

<prosekit-block-handle-popup {...restProps}>{@render children?.()}</prosekit-block-handle-popup>
