/**
 * This file is auto-generated by the "@aria-ui/cli" tool. Do not edit this file directly.
 */

import type {
  BlockHandlePopoverEvents,
  BlockHandlePopoverProps as BlockHandlePopoverElementProps,
} from "@prosekit/web/block-handle";
import type { Component, Snippet } from "svelte";

import BlockHandlePopoverComponent from "./block-handle-popover.gen.svelte";

/**
 * Props for the {@link BlockHandlePopover} Svelte component.
 *
 * @public
 */
export interface BlockHandlePopoverProps {
  /**
   * The ProseKit editor instance.
   *
   * @default null
   * @hidden
   */
  editor?: BlockHandlePopoverElementProps["editor"];
  /**
   * The placement of the popover, relative to the hovered block.
   *
   * @default "left"
   */
  placement?: BlockHandlePopoverElementProps["placement"];
  /**
   * Whether to use the browser [Popover API](https://developer.mozilla.org/en-US/docs/Web/API/Popover_API)
   * to place the floating element on top of other page content.
   *
   * @default false
   */
  hoist?: BlockHandlePopoverElementProps["hoist"];
  /**
   * @default false
   * @hidden
   */
  flip?: BlockHandlePopoverElementProps["flip"];
  /**
   * @default false
   * @hidden
   */
  shift?: BlockHandlePopoverElementProps["shift"];
  /**
   * @default true
   * @hidden
   */
  hide?: BlockHandlePopoverElementProps["hide"];
  /**
   * The strategy to use for positioning
   *
   * @default "absolute"
   */
  strategy?: BlockHandlePopoverElementProps["strategy"];
  /**
   * Options to activate auto-update listeners
   *
   * @see https://floating-ui.com/docs/autoUpdate
   *
   * @default true
   */
  autoUpdate?: BlockHandlePopoverElementProps["autoUpdate"];
  /**
   * The distance between the reference and floating element.
   *
   * @default 6
   */
  offset?: BlockHandlePopoverElementProps["offset"];
  /**
   * Whether the floating element can overlap the reference element to keep it
   * in view.
   *
   * @default false
   */
  overlap?: BlockHandlePopoverElementProps["overlap"];
  /**
   * Whether to constrain the floating element's width and height to not exceed
   * the viewport.
   *
   * @default false
   */
  fitViewport?: BlockHandlePopoverElementProps["fitViewport"];
  /**
   * Whether to constrain the floating element's width so that it matches the
   * reference element.
   *
   * @default false
   */
  sameWidth?: BlockHandlePopoverElementProps["sameWidth"];
  /**
   * Whether to constrain the floating element's height so that it matches the
   * reference element.
   *
   * @default false
   */
  sameHeight?: BlockHandlePopoverElementProps["sameHeight"];
  /**
   * Whether to improve positioning for inline reference elements that span over
   * multiple lines.
   *
   * @default false
   */
  inline?: BlockHandlePopoverElementProps["inline"];
  /**
   * Describes the clipping element(s) or area that overflow will be checked relative to.
   * Please see https://floating-ui.com/docs/detectoverflow#boundary for more information.
   *
   * @default 'clippingAncestors'
   */
  boundary?: BlockHandlePopoverElementProps["boundary"];
  /**
   * Describes the root boundary that the element will be checked for overflow relative to.
   * Please see https://floating-ui.com/docs/detectoverflow#rootboundary for more information.
   *
   * @default 'viewport'
   */
  rootBoundary?: BlockHandlePopoverElementProps["rootBoundary"];
  /**
   * Describes the virtual padding around the boundary to check for overflow.
   * Please see https://floating-ui.com/docs/detectoverflow#padding for more information.
   *
   * @default 4
   */
  overflowPadding?: BlockHandlePopoverElementProps["overflowPadding"];
  /**
   * The element that will be used to check for overflow. Please see
   * https://floating-ui.com/docs/detectoverflow#elementcontext for more
   * information.
   *
   * @default 'floating'
   */
  elementContext?: BlockHandlePopoverElementProps["elementContext"];
  /**
   * Whether to check the alternate elementContext's boundary. Please see
   * https://floating-ui.com/docs/detectoverflow#altboundary for more
   * information.
   *
   * @default false
   */
  altBoundary?: BlockHandlePopoverElementProps["altBoundary"];
  /** Fired when the hovered block changes. */
  onStateChange?: (event: BlockHandlePopoverEvents["stateChange"]) => void;
  children?: Snippet;
  [key: string]: unknown;
}

/**
 * A Svelte component that renders an `prosekit-block-handle-popover` custom element.
 *
 * @public
 */
export const BlockHandlePopover: Component<BlockHandlePopoverProps> =
  BlockHandlePopoverComponent as unknown as Component<BlockHandlePopoverProps>;

export type { BlockHandlePopoverEvents };
export { BlockHandlePopoverStateChangeEvent } from "@prosekit/web/block-handle";
