<!-- This file is auto-generated by the "@aria-ui/cli" tool. Do not edit this file directly. -->

<script lang="ts">
  import { registerBlockHandleDraggableElement } from '@prosekit/web/block-handle'
  import type { BlockHandleDraggableElement } from '@prosekit/web/block-handle'
  import { useEditorContext } from '../../contexts/editor-context.ts'
  registerBlockHandleDraggableElement()

  let { editor: p0, children = undefined, ...restProps } = $props()
  let element: BlockHandleDraggableElement | undefined

  const p0Fallback = useEditorContext()

  $effect(() => {
    if (!element) return

    Object.assign(element, { editor: p0 ?? p0Fallback })
  })
</script>

<prosekit-block-handle-draggable {...restProps} bind:this={element}>{@render children?.()}</prosekit-block-handle-draggable>
