/**
 * This file is auto-generated by the "@aria-ui/cli" tool. Do not edit this file directly.
 */

import { ReactWrapper } from "@aria-ui-v2/integrations/react";
import {
  createElement,
  forwardRef,
  type ForwardedRef,
  type ForwardRefExoticComponent,
  type HTMLAttributes,
  type RefAttributes,
} from "react";
import {
  registerResizableHandleElement,
  type ResizableHandleElement,
  type ResizableHandleProps as ResizableHandleElementProps,
} from "@prosekit/web/resizable";

const propNames: string[] = ["position"];
const eventNameMap: Record<string, string> = {};

/**
 * Props for the {@link ResizableHandle} React component.
 *
 * @public
 */
export interface ResizableHandleProps extends HTMLAttributes<ResizableHandleElement> {
  /**
   * The position of the handle.
   *
   * @default "bottom-right"
   */
  position?: ResizableHandleElementProps["position"];
}

function ResizableHandleComponent(
  props: ResizableHandleProps,
  forwardedRef: ForwardedRef<ResizableHandleElement>,
) {
  registerResizableHandleElement();
  return createElement(ReactWrapper, {
    as: "prosekit-resizable-handle",
    propNames,
    eventNameMap,
    props,
    forwardedRef,
  });
}

/**
 * A React component that renders an `prosekit-resizable-handle` custom element.
 *
 * @public
 */
export const ResizableHandle: ForwardRefExoticComponent<
  ResizableHandleProps & RefAttributes<ResizableHandleElement>
> = /* @__PURE__ */ forwardRef(ResizableHandleComponent);
