/**
 * This file is auto-generated by the "@aria-ui/cli" tool. Do not edit this file directly.
 */

import { ReactWrapper } from "@aria-ui-v2/integrations/react";
import {
  createElement,
  forwardRef,
  type ForwardedRef,
  type ForwardRefExoticComponent,
  type HTMLAttributes,
  type RefAttributes,
} from "react";
import {
  registerResizableRootElement,
  type ResizableRootElement,
  type ResizableRootProps as ResizableRootElementProps,
  type ResizableRootEvents,
} from "@prosekit/web/resizable";

const propNames: string[] = ["aspectRatio", "height", "width"];
const eventNameMap: Record<string, string> = {
  onResizeEnd: "resizeEnd",
  onResizeStart: "resizeStart",
};

/**
 * Props for the {@link ResizableRoot} React component.
 *
 * @public
 */
export interface ResizableRootProps extends HTMLAttributes<ResizableRootElement> {
  /**
   * The width of the resizable element.
   *
   * @default null
   */
  width?: ResizableRootElementProps["width"];
  /**
   * The height of the resizable element.
   *
   * @default null
   */
  height?: ResizableRootElementProps["height"];
  /**
   * The aspect ratio of the resizable element.
   *
   * @default null
   */
  aspectRatio?: ResizableRootElementProps["aspectRatio"];
  /** Emitted when a resize operation starts. */
  onResizeStart?: (event: ResizableRootEvents["resizeStart"]) => void;
  /** Emitted when a resize operation ends. */
  onResizeEnd?: (event: ResizableRootEvents["resizeEnd"]) => void;
}

function ResizableRootComponent(
  props: ResizableRootProps,
  forwardedRef: ForwardedRef<ResizableRootElement>,
) {
  registerResizableRootElement();
  return createElement(ReactWrapper, {
    as: "prosekit-resizable-root",
    propNames,
    eventNameMap,
    props,
    forwardedRef,
  });
}

/**
 * A React component that renders an `prosekit-resizable-root` custom element.
 *
 * @public
 */
export const ResizableRoot: ForwardRefExoticComponent<
  ResizableRootProps & RefAttributes<ResizableRootElement>
> = /* @__PURE__ */ forwardRef(ResizableRootComponent);

export type { ResizableRootEvents };
export { ResizeEndEvent, ResizeStartEvent } from "@prosekit/web/resizable";
