name: Cache Restore
description: Restore turbo cache

runs:
  using: composite
  steps:
    - name: Restore turbo cache
      uses: actions/cache/restore@v4
      with:
        path: .turbo/cache
        key: |
          turbo-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}-${{ github.run_id }}
        restore-keys: |
          turbo-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}
