/**
 * This file is auto-generated by the "@aria-ui/cli" tool. Do not edit this file directly.
 */

import type { TooltipTriggerProps as TooltipTriggerElementProps } from '@prosekit/web/tooltip';
import type { Component, Snippet } from 'svelte';

import TooltipTriggerComponent from './tooltip-trigger.gen.svelte';

/**
 * Props for the {@link TooltipTrigger} Svelte component.
 *
 * @public
 */
export interface TooltipTriggerProps {
  /**
   * Whether the component should ignore user interaction.
   * @default false
   */
  disabled?: TooltipTriggerElementProps['disabled'];
  /**
   * The delay in milliseconds before opening the tooltip on hover.
   * @default 600
   */
  openDelay?: TooltipTriggerElementProps['openDelay'];
  /**
   * The delay in milliseconds before closing the tooltip when hover/focus ends.
   * @default 0
   */
  closeDelay?: TooltipTriggerElementProps['closeDelay'];
  children?: Snippet;
  [key: string]: unknown;
}

/**
 * A Svelte component that renders an `prosekit-tooltip-trigger` custom element.
 *
 * @public
 */
export const TooltipTrigger: Component<TooltipTriggerProps> = TooltipTriggerComponent as unknown as Component<TooltipTriggerProps>;
