<!-- This file is auto-generated by the "@aria-ui/cli" tool. Do not edit this file directly. -->

<script lang="js">
  import { registerTooltipTriggerElement } from '@prosekit/web/tooltip'
  registerTooltipTriggerElement()

  let { closeDelay: p0, disabled: p1, openDelay: p2, children = undefined, ...restProps } = $props()

  const attachment = (element) => {
    if (!element) return

    if (p0 !== undefined) { element.closeDelay = p0 }

    if (p1 !== undefined) { element.disabled = p1 }

    if (p2 !== undefined) { element.openDelay = p2 }
  }
</script>

<prosekit-tooltip-trigger {...restProps} {@attach attachment}>{@render children?.()}</prosekit-tooltip-trigger>
