/**
 * This file is auto-generated by the "@aria-ui/cli" tool. Do not edit this file directly.
 */

import type { DropIndicatorProps as DropIndicatorElementProps } from '@prosekit/web/drop-indicator';
import type { Component, Snippet } from 'svelte';

import DropIndicatorComponent from './drop-indicator.gen.svelte';

/**
 * Props for the {@link DropIndicator} Svelte component.
 *
 * @public
 */
export interface DropIndicatorProps {
  /**
   * The ProseKit editor instance.
   *
   * @default null
   * @hidden
   */
  editor?: DropIndicatorElementProps['editor'];
  /**
   * The line width in pixels.
   *
   * @default 2
   */
  width?: DropIndicatorElementProps['width'];
  children?: Snippet;
  [key: string]: unknown;
}

/**
 * A Svelte component that renders an `prosekit-drop-indicator` custom element.
 *
 * @public
 */
export const DropIndicator: Component<DropIndicatorProps> = DropIndicatorComponent as unknown as Component<DropIndicatorProps>;
