// This file is auto-generated by "@aria-ui/cli". Do not edit this file directly.

import { registerColumnsPopoverPositionerElement, type ColumnsPopoverPositionerElement, type ColumnsPopoverPositionerProps as ColumnsPopoverPositionerElementProps } from '@prosekit/web/columns-popover';
import { createElement, type HTMLAttributes, type Ref } from 'preact';
import { forwardRef, type ForwardRefExoticComponent, type RefAttributes } from 'preact/compat';
import { useCallback, useRef, useLayoutEffect } from 'preact/hooks';

/** Props for the {@link ColumnsPopoverPositioner} Preact component. */
export interface ColumnsPopoverPositionerProps {
  /**
   * The placement of the popover, relative to the column node.
   *
   * @default "top"
   */
  placement?: ColumnsPopoverPositionerElementProps['placement'];
  /**
   * Whether to use the browser [Popover API](https://developer.mozilla.org/en-US/docs/Web/API/Popover_API)
   * to place the floating element on top of other page content.
   *
   * @default false
   */
  hoist?: ColumnsPopoverPositionerElementProps['hoist'];
  /**
   * @default false
   * @hidden
   */
  flip?: ColumnsPopoverPositionerElementProps['flip'];
  /**
   * @default false
   * @hidden
   */
  shift?: ColumnsPopoverPositionerElementProps['shift'];
  /**
   * @default true
   * @hidden
   */
  hide?: ColumnsPopoverPositionerElementProps['hide'];
  /**
   * The strategy to use for positioning
   *
   * @default "absolute"
   */
  strategy?: ColumnsPopoverPositionerElementProps['strategy'];
  /**
   * Options to activate auto-update listeners
   *
   * @see https://floating-ui.com/docs/autoUpdate
   *
   * @default true
   */
  autoUpdate?: ColumnsPopoverPositionerElementProps['autoUpdate'];
  /**
   * The distance between the reference and floating element.
   *
   * @default 6
   */
  offset?: ColumnsPopoverPositionerElementProps['offset'];
  /**
   * Whether the floating element can overlap the reference element to keep it
   * in view.
   *
   * @default false
   */
  overlap?: ColumnsPopoverPositionerElementProps['overlap'];
  /**
   * Whether to constrain the floating element's width and height to not exceed
   * the viewport.
   *
   * @default false
   */
  fitViewport?: ColumnsPopoverPositionerElementProps['fitViewport'];
  /**
   * Whether to constrain the floating element's width so that it matches the
   * reference element.
   *
   * @default false
   */
  sameWidth?: ColumnsPopoverPositionerElementProps['sameWidth'];
  /**
   * Whether to constrain the floating element's height so that it matches the
   * reference element.
   *
   * @default false
   */
  sameHeight?: ColumnsPopoverPositionerElementProps['sameHeight'];
  /**
   * Whether to improve positioning for inline reference elements that span over
   * multiple lines.
   *
   * @default false
   */
  inline?: ColumnsPopoverPositionerElementProps['inline'];
  /**
   * Describes the clipping element(s) or area that overflow will be checked relative to.
   * Please see https://floating-ui.com/docs/detectoverflow#boundary for more information.
   *
   * @default 'clippingAncestors'
   */
  boundary?: ColumnsPopoverPositionerElementProps['boundary'];
  /**
   * Describes the root boundary that the element will be checked for overflow relative to.
   * Please see https://floating-ui.com/docs/detectoverflow#rootboundary for more information.
   *
   * @default 'viewport'
   */
  rootBoundary?: ColumnsPopoverPositionerElementProps['rootBoundary'];
  /**
   * Describes the virtual padding around the boundary to check for overflow.
   * Please see https://floating-ui.com/docs/detectoverflow#padding for more information.
   *
   * @default 4
   */
  overflowPadding?: ColumnsPopoverPositionerElementProps['overflowPadding'];
  /**
   * The element that will be used to check for overflow. Please see
   * https://floating-ui.com/docs/detectoverflow#elementcontext for more
   * information.
   *
   * @default 'floating'
   */
  elementContext?: ColumnsPopoverPositionerElementProps['elementContext'];
  /**
   * Whether to check the alternate elementContext's boundary. Please see
   * https://floating-ui.com/docs/detectoverflow#altboundary for more
   * information.
   *
   * @default false
   */
  altBoundary?: ColumnsPopoverPositionerElementProps['altBoundary'];
}

function ColumnsPopoverPositionerComponent(props: ColumnsPopoverPositionerProps, forwardedRef: Ref<ColumnsPopoverPositionerElement>) {
  registerColumnsPopoverPositionerElement();

  const elementRef = useRef<ColumnsPopoverPositionerElement>(null);

  const { altBoundary: p0, autoUpdate: p1, boundary: p2, elementContext: p3, fitViewport: p4, flip: p5, hide: p6, hoist: p7, inline: p8, offset: p9, overflowPadding: p10, overlap: p11, placement: p12, rootBoundary: p13, sameHeight: p14, sameWidth: p15, shift: p16, strategy: p17, ...restProps } = props;

  useLayoutEffect(() => {
    const element = elementRef.current as Record<string, unknown> | null;
    if (!element) return;
    Object.assign(element, { altBoundary: p0, autoUpdate: p1, boundary: p2, elementContext: p3, fitViewport: p4, flip: p5, hide: p6, hoist: p7, inline: p8, offset: p9, overflowPadding: p10, overlap: p11, placement: p12, rootBoundary: p13, sameHeight: p14, sameWidth: p15, shift: p16, strategy: p17 });
  });

  const mergedRef = useCallback(
    (element: ColumnsPopoverPositionerElement | null) => {
      elementRef.current = element;
      if (typeof forwardedRef === 'function') {
        forwardedRef(element);
      } else if (forwardedRef) {
        forwardedRef.current = element;
      }
    },
    [forwardedRef],
  );

  return createElement('prosekit-columns-popover-positioner', { ...restProps, ref: mergedRef, suppressHydrationWarning: true });
}

/** A Preact component that renders an `prosekit-columns-popover-positioner` custom element. */
export const ColumnsPopoverPositioner: ForwardRefExoticComponent<ColumnsPopoverPositionerProps & HTMLAttributes<ColumnsPopoverPositionerElement> & RefAttributes<ColumnsPopoverPositionerElement>> = /* @__PURE__ */ forwardRef(ColumnsPopoverPositionerComponent);
