// This file is auto-generated by "@aria-ui/cli". Do not edit this file directly.

import { registerColumnsPopoverPopupElement, type ColumnsPopoverPopupElement } from '@prosekit/web/columns-popover';
import { createElement, type HTMLAttributes, type Ref } from 'preact';
import { forwardRef, type ForwardRefExoticComponent, type RefAttributes } from 'preact/compat';
import { useCallback, useRef } from 'preact/hooks';

/** Props for the {@link ColumnsPopoverPopup} Preact component. */
export interface ColumnsPopoverPopupProps {}

function ColumnsPopoverPopupComponent(props: ColumnsPopoverPopupProps, forwardedRef: Ref<ColumnsPopoverPopupElement>) {
  registerColumnsPopoverPopupElement();

  const elementRef = useRef<ColumnsPopoverPopupElement>(null);

  const { ...restProps } = props;

  const mergedRef = useCallback(
    (element: ColumnsPopoverPopupElement | null) => {
      elementRef.current = element;
      if (typeof forwardedRef === 'function') {
        forwardedRef(element);
      } else if (forwardedRef) {
        forwardedRef.current = element;
      }
    },
    [forwardedRef],
  );

  return createElement('prosekit-columns-popover-popup', { ...restProps, ref: mergedRef, suppressHydrationWarning: true });
}

/** A Preact component that renders an `prosekit-columns-popover-popup` custom element. */
export const ColumnsPopoverPopup: ForwardRefExoticComponent<ColumnsPopoverPopupProps & HTMLAttributes<ColumnsPopoverPopupElement> & RefAttributes<ColumnsPopoverPopupElement>> = /* @__PURE__ */ forwardRef(ColumnsPopoverPopupComponent);
