/**
 * This file is auto-generated by the "@aria-ui/cli" tool. Do not edit this file directly.
 */

import { registerTooltipRootElement, type TooltipRootElement, type TooltipRootEvents, type TooltipRootProps as TooltipRootElementProps } from '@prosekit/web/tooltip';
import { createEffect, createSignal, mergeProps, splitProps } from 'solid-js';
import type { Component, JSX } from 'solid-js';
import h from 'solid-js/h';

/**
 * Props for the {@link TooltipRoot} Solid component.
 *
 * @public
 */
export interface TooltipRootProps {
  /**
   * Whether the overlay is initially open.
   * @default false
   */
  defaultOpen?: TooltipRootElementProps['defaultOpen'];
  /**
   * Whether the overlay is currently open.
   * @default null
   */
  open?: TooltipRootElementProps['open'];
  /**
   * Whether the component should ignore user interaction.
   * @default false
   */
  disabled?: TooltipRootElementProps['disabled'];
  /** Emitted when the tooltip is opened or closed. */
  onOpenChange?: (event: TooltipRootEvents['openChange']) => void;
}

/**
 * A Solid component that renders an `prosekit-tooltip-root` custom element.
 *
 * @public
 */
export const TooltipRoot: Component<TooltipRootProps & JSX.HTMLAttributes<TooltipRootElement>> = (props): any => {
  registerTooltipRootElement();

  const [getElement, setElement] = createSignal<TooltipRootElement | null>(null);
  const handlers: Array<((event: any) => void) | undefined> = [];

  const [elementProps, eventHandlers, restProps] = splitProps(props, ['defaultOpen', 'disabled', 'open'], ['onOpenChange']);

  createEffect(() => {
    const element = getElement();
    if (!element) return;

    Object.assign(element, { defaultOpen: elementProps.defaultOpen, disabled: elementProps.disabled, open: elementProps.open });

    handlers.length = 0;
    handlers.push(eventHandlers.onOpenChange);
  });

  createEffect(() => {
    const element = getElement();
    if (!element) return;

    const ac = new AbortController();
    for (const [index, eventName] of ['openChange'].entries()) {
      element.addEventListener(
        eventName,
        (event) => {
          handlers[index]?.(event);
        },
        { signal: ac.signal },
      );
    }
    return () => ac.abort();
  });

  return () =>
    h(
      'prosekit-tooltip-root',
      mergeProps(restProps, {
        ref: (el: TooltipRootElement | null) => {
          setElement(el);
        },
      }),
    );
};
