/**
 * This file is auto-generated by the "@aria-ui/cli" tool. Do not edit this file directly.
 */

import { PreactWrapper } from "@aria-ui-v2/integrations/preact";
import { createElement, type HTMLAttributes, type Ref } from "preact";
import {
  forwardRef,
  type ForwardRefExoticComponent,
  type RefAttributes,
} from "preact/compat";
import {
  registerDropIndicatorElement,
  type DropIndicatorElement,
  type DropIndicatorProps as DropIndicatorElementProps,
} from "@prosekit/web/drop-indicator";
import { useEditorContext } from "../../contexts/editor-context.ts";

const propNames: string[] = ["editor", "width"];
const eventNameMap: Record<string, string> = {};

/**
 * Props for the {@link DropIndicator} Preact component.
 *
 * @public
 */
export interface DropIndicatorProps extends HTMLAttributes<DropIndicatorElement> {
  /**
   * The ProseKit editor instance.
   *
   * @default null
   * @hidden
   */
  editor?: DropIndicatorElementProps["editor"];
  /**
   * The line width in pixels.
   *
   * @default 2
   */
  width?: DropIndicatorElementProps["width"];
}

function DropIndicatorComponent(
  props: DropIndicatorProps,
  forwardedRef: Ref<DropIndicatorElement>,
) {
  registerDropIndicatorElement();
  const componentProps: DropIndicatorProps = { ...props };
  const editorContext = useEditorContext();
  if (componentProps.editor == null && editorContext != null) {
    componentProps.editor = editorContext;
  }

  return createElement(PreactWrapper, {
    as: "prosekit-drop-indicator",
    propNames,
    eventNameMap,
    props: componentProps,
    forwardedRef,
  });
}

/**
 * A Preact component that renders an `prosekit-drop-indicator` custom element.
 *
 * @public
 */
export const DropIndicator: ForwardRefExoticComponent<
  DropIndicatorProps & RefAttributes<DropIndicatorElement>
> = /* @__PURE__ */ forwardRef(DropIndicatorComponent);
