export { ProseKit, type ProseKitProps } from './components/prosekit.ts'
export { defineVueMarkView, type VueMarkViewComponent, type VueMarkViewOptions, type VueMarkViewProps } from './extensions/vue-mark-view.ts'
export { defineVueNodeView, type VueNodeViewComponent, type VueNodeViewOptions, type VueNodeViewProps } from './extensions/vue-node-view.ts'
export { useDocChange } from './hooks/use-doc-change.ts'
export { useEditorDerivedValue, type UseEditorDerivedOptions } from './hooks/use-editor-derived-value.ts'
export { useEditor } from './hooks/use-editor.ts'
export { useExtension, type UseExtensionOptions } from './hooks/use-extension.ts'
export { useKeymap } from './hooks/use-keymap.ts'
export { useStateUpdate } from './hooks/use-state-update.ts'
