// This file is generated from update-loader.ts

export const loaders = {
  'block-handle': () => import('./examples/block-handle').then((m) => ({ default: m.ExampleEditor })),
  'blockquote': () => import('./examples/blockquote').then((m) => ({ default: m.ExampleEditor })),
  'bold': () => import('./examples/bold').then((m) => ({ default: m.ExampleEditor })),
  'change-tracking': () => import('./examples/change-tracking').then((m) => ({ default: m.ExampleEditor })),
  'code': () => import('./examples/code').then((m) => ({ default: m.ExampleEditor })),
  'code-block': () => import('./examples/code-block').then((m) => ({ default: m.ExampleEditor })),
  'code-block-themes': () => import('./examples/code-block-themes').then((m) => ({ default: m.ExampleEditor })),
  'drop-cursor': () => import('./examples/drop-cursor').then((m) => ({ default: m.ExampleEditor })),
  'emoji-rules': () => import('./examples/emoji-rules').then((m) => ({ default: m.ExampleEditor })),
  'full': () => import('./examples/full').then((m) => ({ default: m.ExampleEditor })),
  'gap-cursor': () => import('./examples/gap-cursor').then((m) => ({ default: m.ExampleEditor })),
  'hard-break': () => import('./examples/hard-break').then((m) => ({ default: m.ExampleEditor })),
  'heading': () => import('./examples/heading').then((m) => ({ default: m.ExampleEditor })),
  'horizontal-rule': () => import('./examples/horizontal-rule').then((m) => ({ default: m.ExampleEditor })),
  'image-view': () => import('./examples/image-view').then((m) => ({ default: m.ExampleEditor })),
  'inline-menu': () => import('./examples/inline-menu').then((m) => ({ default: m.ExampleEditor })),
  'italic': () => import('./examples/italic').then((m) => ({ default: m.ExampleEditor })),
  'keymap': () => import('./examples/keymap').then((m) => ({ default: m.ExampleEditor })),
  'link': () => import('./examples/link').then((m) => ({ default: m.ExampleEditor })),
  'link-mark-view': () => import('./examples/link-mark-view').then((m) => ({ default: m.ExampleEditor })),
  'list': () => import('./examples/list').then((m) => ({ default: m.ExampleEditor })),
  'list-custom-checkbox': () => import('./examples/list-custom-checkbox').then((m) => ({ default: m.ExampleEditor })),
  'loro': () => import('./examples/loro').then((m) => ({ default: m.ExampleEditor })),
  'mark-rule': () => import('./examples/mark-rule').then((m) => ({ default: m.ExampleEditor })),
  'minimal': () => import('./examples/minimal').then((m) => ({ default: m.ExampleEditor })),
  'placeholder': () => import('./examples/placeholder').then((m) => ({ default: m.ExampleEditor })),
  'readonly': () => import('./examples/readonly').then((m) => ({ default: m.ExampleEditor })),
  'save-html': () => import('./examples/save-html').then((m) => ({ default: m.ExampleEditor })),
  'save-json': () => import('./examples/save-json').then((m) => ({ default: m.ExampleEditor })),
  'save-markdown': () => import('./examples/save-markdown').then((m) => ({ default: m.ExampleEditor })),
  'search': () => import('./examples/search').then((m) => ({ default: m.ExampleEditor })),
}
