/**
 * This file is auto-generated by the "@aria-ui/cli" tool. Do not edit this file directly.
 */

import { registerInlinePopoverPopupElement, type InlinePopoverPopupElement } from '@prosekit/web/inline-popover';
import type { Component, JSX } from 'solid-js';
import h from 'solid-js/h';

/**
 * Props for the {@link InlinePopoverPopup} Solid component.
 *
 * @public
 */
export interface InlinePopoverPopupProps {}

/**
 * A Solid component that renders an `prosekit-inline-popover-popup` custom element.
 *
 * @public
 */
export const InlinePopoverPopup: Component<InlinePopoverPopupProps & JSX.HTMLAttributes<InlinePopoverPopupElement>> = (props): any => {
  registerInlinePopoverPopupElement();

  const restProps = props;

  return () => h('prosekit-inline-popover-popup', restProps);
};
