// This file is auto-generated by "@aria-ui/cli". Do not edit this file directly.

import { registerInlinePopoverRootElement, type InlinePopoverRootElement, type InlinePopoverRootEvents, type InlinePopoverRootProps as InlinePopoverRootElementProps } from '@prosekit/web/inline-popover';
import { createEffect, createSignal, mergeProps, splitProps } from 'solid-js';
import type { Component, JSX } from 'solid-js';
import h from 'solid-js/h';

import { useEditorContext } from '../../contexts/editor-context.ts';

/** Props for the {@link InlinePopoverRoot} Solid component. */
export interface InlinePopoverRootProps {
  /**
   * The ProseKit editor instance.
   *
   * @default null
   * @hidden
   */
  editor?: InlinePopoverRootElementProps['editor'];
  /**
   * Whether the popover is open by default when some inline content is
   * selected.
   *
   * @default true
   */
  defaultOpen?: InlinePopoverRootElementProps['defaultOpen'];
  /**
   * Whether the inline popover should be dismissed when the editor receives an
   * Escape key press.
   *
   * @default true
   */
  dismissOnEscape?: InlinePopoverRootElementProps['dismissOnEscape'];
  /**
   * Whether the overlay is currently open.
   * @default null
   */
  open?: InlinePopoverRootElementProps['open'];
  /**
   * Whether the component should ignore user interaction.
   * @default false
   */
  disabled?: InlinePopoverRootElementProps['disabled'];
  /** Emitted when the open state of the popover changes. */
  onOpenChange?: (event: InlinePopoverRootEvents['openChange']) => void;
}

/** A Solid component that renders an `prosekit-inline-popover-root` custom element. */
export const InlinePopoverRoot: Component<InlinePopoverRootProps & JSX.HTMLAttributes<InlinePopoverRootElement>> = (props): any => {
  registerInlinePopoverRootElement();

  const [getElement, setElement] = createSignal<InlinePopoverRootElement | null>(null);
  const handlers: Array<((event: any) => void) | undefined> = [];

  const [elementProps, eventHandlers, restProps] = splitProps(props, ['defaultOpen', 'disabled', 'dismissOnEscape', 'editor', 'open'], ['onOpenChange']);

  const p3Fallback = useEditorContext();

  createEffect(() => {
    const element = getElement();
    if (!element) return;

    Object.assign(element, { defaultOpen: elementProps.defaultOpen, disabled: elementProps.disabled, dismissOnEscape: elementProps.dismissOnEscape, editor: elementProps.editor ?? p3Fallback, open: elementProps.open });

    handlers.length = 0;
    handlers.push(eventHandlers.onOpenChange);
  });

  createEffect(() => {
    const element = getElement();
    if (!element) return;

    const ac = new AbortController();
    for (const [index, eventName] of ['openChange'].entries()) {
      element.addEventListener(
        eventName,
        (event) => {
          handlers[index]?.(event);
        },
        { signal: ac.signal },
      );
    }
    return () => ac.abort();
  });

  return () =>
    h(
      'prosekit-inline-popover-root',
      mergeProps(restProps, {
        ref: (el: InlinePopoverRootElement | null) => {
          setElement(el);
        },
      }),
    );
};
