/**
 * This file is auto-generated by the "@aria-ui/cli" tool. Do not edit this file directly.
 */

import {
  registerInlinePopoverElement,
  type InlinePopoverElement,
  type InlinePopoverEvents,
  type InlinePopoverProps as InlinePopoverElementProps,
} from "@prosekit/web/inline-popover";
import { createEffect, createSignal, mergeProps, splitProps } from "solid-js";
import type { Component, JSX } from "solid-js";
import h from "solid-js/h";
import { useEditorContext } from "../../contexts/editor-context.ts";

/**
 * Props for the {@link InlinePopover} Solid component.
 *
 * @public
 */
export interface InlinePopoverProps extends JSX.HTMLAttributes<InlinePopoverElement> {
  /**
   * The ProseKit editor instance.
   *
   * @default null
   * @hidden
   */
  editor?: InlinePopoverElementProps["editor"];
  /**
   * Whether the popover is open by default when some inline content is
   * selected.
   *
   * When `defaultOpen` is true, the popover will open or close based on the
   * inline selection. When `defaultOpen` is false, the popover will never be
   * opened unless the `open` prop is true.
   *
   * @default true
   */
  defaultOpen?: InlinePopoverElementProps["defaultOpen"];
  /**
   * Whether the popover is open.
   *
   * Notice that the popover will be always hidden if the inline selection is
   * empty.
   *
   * @default false
   */
  open?: InlinePopoverElementProps["open"];
  /**
   * Whether the inline popover should be dismissed when the editor receives an
   * Escape key press.
   *
   * @default true
   */
  dismissOnEscape?: InlinePopoverElementProps["dismissOnEscape"];
  /** @default "top" */
  placement?: InlinePopoverElementProps["placement"];
  /** @default 12 */
  offset?: InlinePopoverElementProps["offset"];
  /** @default true */
  hide?: InlinePopoverElementProps["hide"];
  /** @default true */
  overlap?: InlinePopoverElementProps["overlap"];
  /** @default true */
  inline?: InlinePopoverElementProps["inline"];
  /** @default 8 */
  overflowPadding?: InlinePopoverElementProps["overflowPadding"];
  /**
   * The strategy to use for positioning
   *
   * @default "absolute"
   */
  strategy?: InlinePopoverElementProps["strategy"];
  /**
   * Options to activate auto-update listeners
   *
   * @see https://floating-ui.com/docs/autoUpdate
   *
   * @default true
   */
  autoUpdate?: InlinePopoverElementProps["autoUpdate"];
  /**
   * Whether to use the browser Popover API to place the floating element on
   * top of other page content.
   *
   * @default true
   */
  hoist?: InlinePopoverElementProps["hoist"];
  /**
   * Whether to flip the `placement` in order to keep it in view when the
   * preferred placement(s) will overflow the clipping boundary. You can also
   * provide an array of placements to try sequentially if the preferred
   * `placement` does not fit.
   *
   * @default true
   */
  flip?: InlinePopoverElementProps["flip"];
  /**
   * Whether the floating element should shift to keep it in view.
   *
   * @default true
   */
  shift?: InlinePopoverElementProps["shift"];
  /**
   * Whether to constrain the floating element's width and height to not exceed
   * the viewport.
   *
   * @default false
   */
  fitViewport?: InlinePopoverElementProps["fitViewport"];
  /**
   * Whether to constrain the floating element's width so that it matches the
   * reference element.
   *
   * @default false
   */
  sameWidth?: InlinePopoverElementProps["sameWidth"];
  /**
   * Whether to constrain the floating element's height so that it matches the
   * reference element.
   *
   * @default false
   */
  sameHeight?: InlinePopoverElementProps["sameHeight"];
  /**
   * Describes the clipping element(s) or area that overflow will be checked relative to.
   * Please see https://floating-ui.com/docs/detectoverflow#boundary for more information.
   *
   * @default 'clippingAncestors'
   */
  boundary?: InlinePopoverElementProps["boundary"];
  /**
   * Describes the root boundary that the element will be checked for overflow relative to.
   * Please see https://floating-ui.com/docs/detectoverflow#rootboundary for more information.
   *
   * @default 'viewport'
   */
  rootBoundary?: InlinePopoverElementProps["rootBoundary"];
  /**
   * The element that will be used to check for overflow. Please see
   * https://floating-ui.com/docs/detectoverflow#elementcontext for more
   * information.
   *
   * @default 'floating'
   */
  elementContext?: InlinePopoverElementProps["elementContext"];
  /**
   * Whether to check the alternate elementContext's boundary. Please see
   * https://floating-ui.com/docs/detectoverflow#altboundary for more
   * information.
   *
   * @default false
   */
  altBoundary?: InlinePopoverElementProps["altBoundary"];
  /** Fired when the open state changes. */
  onOpenChange?: (event: InlinePopoverEvents["openChange"]) => void;
}

/**
 * A Solid component that renders an `prosekit-inline-popover` custom element.
 *
 * @public
 */
export const InlinePopover: Component<InlinePopoverProps> = (props): any => {
  registerInlinePopoverElement();

  const [getElement, setElement] = createSignal<InlinePopoverElement | null>(
    null,
  );
  const handlers: Array<((event: any) => void) | undefined> = [];

  const [elementProps, eventHandlers, restProps] = splitProps(
    props,
    [
      "altBoundary",
      "autoUpdate",
      "boundary",
      "defaultOpen",
      "dismissOnEscape",
      "editor",
      "elementContext",
      "fitViewport",
      "flip",
      "hide",
      "hoist",
      "inline",
      "offset",
      "open",
      "overflowPadding",
      "overlap",
      "placement",
      "rootBoundary",
      "sameHeight",
      "sameWidth",
      "shift",
      "strategy",
    ],
    ["onOpenChange"],
  );

  const p5Fallback = useEditorContext();

  createEffect(() => {
    const element = getElement();
    if (!element) return;

    Object.assign(element, {
      altBoundary: elementProps.altBoundary,
      autoUpdate: elementProps.autoUpdate,
      boundary: elementProps.boundary,
      defaultOpen: elementProps.defaultOpen,
      dismissOnEscape: elementProps.dismissOnEscape,
      editor: elementProps.editor ?? p5Fallback,
      elementContext: elementProps.elementContext,
      fitViewport: elementProps.fitViewport,
      flip: elementProps.flip,
      hide: elementProps.hide,
      hoist: elementProps.hoist,
      inline: elementProps.inline,
      offset: elementProps.offset,
      open: elementProps.open,
      overflowPadding: elementProps.overflowPadding,
      overlap: elementProps.overlap,
      placement: elementProps.placement,
      rootBoundary: elementProps.rootBoundary,
      sameHeight: elementProps.sameHeight,
      sameWidth: elementProps.sameWidth,
      shift: elementProps.shift,
      strategy: elementProps.strategy,
    });

    handlers.length = 0;
    handlers.push(eventHandlers.onOpenChange);
  });

  createEffect(() => {
    const element = getElement();
    if (!element) return;

    const ac = new AbortController();
    for (const [index, eventName] of ["openChange"].entries()) {
      element.addEventListener(
        eventName,
        (event) => {
          handlers[index]?.(event);
        },
        { signal: ac.signal },
      );
    }
    return () => ac.abort();
  });

  return h(
    "prosekit-inline-popover",
    mergeProps(restProps, {
      ref: (el: InlinePopoverElement | null) => {
        setElement(el);
      },
    }),
  );
};

export type { InlinePopoverEvents };
export { OpenChangeEvent } from "@prosekit/web/inline-popover";
