/**
 * This file is auto-generated by the "@aria-ui/cli" tool. Do not edit this file directly.
 */

import { createElement, type HTMLAttributes, type Ref } from "preact";
import {
  forwardRef,
  type ForwardRefExoticComponent,
  type RefAttributes,
} from "preact/compat";
import { useCallback, useRef, useLayoutEffect } from "preact/hooks";
import {
  registerAutocompleteListElement,
  type AutocompleteListElement,
  type AutocompleteListProps as AutocompleteListElementProps,
  type AutocompleteListEvents,
} from "@prosekit/web/autocomplete";
import { useEditorContext } from "../../contexts/editor-context.ts";

/**
 * Props for the {@link AutocompleteList} Preact component.
 *
 * @public
 */
export interface AutocompleteListProps extends HTMLAttributes<AutocompleteListElement> {
  /**
   * The ProseKit editor instance.
   *
   * @default null
   * @hidden
   */
  editor?: AutocompleteListElementProps["editor"];
  /**
   * The filter function to determine if an item should be shown in the
   * listbox.
   *
   * @default defaultItemFilter
   */
  filter?: AutocompleteListElementProps["filter"];
  /**
   * Emitted when the selected value changes. Only available when multiple is
   * false.
   */
  onValueChange?: (event: AutocompleteListEvents["valueChange"]) => void;
  /**
   * Emitted when the selected values change. Only available when multiple is
   * true.
   */
  onValuesChange?: (event: AutocompleteListEvents["valuesChange"]) => void;
}

function AutocompleteListComponent(
  props: AutocompleteListProps,
  forwardedRef: Ref<AutocompleteListElement>,
) {
  registerAutocompleteListElement();

  const elementRef = useRef<AutocompleteListElement>(null);
  const handlersRef = useRef<Array<((event: Event) => void) | undefined>>([]);

  const p0Fallback = useEditorContext();

  const {
    editor: p0,
    filter: p1,
    onValueChange: e0,
    onValuesChange: e1,
    ...restProps
  } = props;

  useLayoutEffect(() => {
    const element = elementRef.current as Record<string, unknown> | null;
    if (!element) return;
    Object.assign(element, { editor: p0 ?? p0Fallback, filter: p1 });
    handlersRef.current = [e0, e1] as Array<
      ((event: Event) => void) | undefined
    >;
  });

  useLayoutEffect(() => {
    const element = elementRef.current;
    if (!element) return;
    const ac = new AbortController();
    for (const [index, eventName] of [
      "valueChange",
      "valuesChange",
    ].entries()) {
      element.addEventListener(
        eventName,
        (event: Event) => {
          handlersRef.current[index]?.(event);
        },
        { signal: ac.signal },
      );
    }
    return () => ac.abort();
  }, []);

  const mergedRef = useCallback((element: AutocompleteListElement | null) => {
    elementRef.current = element;
    if (typeof forwardedRef === "function") {
      forwardedRef(element);
    } else if (forwardedRef) {
      forwardedRef.current = element;
    }
  }, []);

  return createElement("prosekit-autocomplete-list", {
    ...restProps,
    ref: mergedRef,
    suppressHydrationWarning: true,
  });
}

/**
 * A Preact component that renders an `prosekit-autocomplete-list` custom element.
 *
 * @public
 */
export const AutocompleteList: ForwardRefExoticComponent<
  AutocompleteListProps & RefAttributes<AutocompleteListElement>
> = /* @__PURE__ */ forwardRef(AutocompleteListComponent);

export type { AutocompleteListEvents };
export {
  ValueChangeEvent,
  ValuesChangeEvent,
} from "@prosekit/web/autocomplete";
