// This file is auto-generated by "@aria-ui/cli". Do not edit this file directly.

import { registerAutocompleteRootElement, type AutocompleteRootEvents, type AutocompleteRootProps as AutocompleteRootElementProps } from '@prosekit/web/autocomplete';
import { defineComponent, h, type DefineSetupFnComponent, type HTMLAttributes, shallowRef, computed, watchEffect } from 'vue';

import { useEditorContext } from '../../injection/editor-context.ts';

/** Props for the {@link AutocompleteRoot} Vue component. */
export interface AutocompleteRootProps {
  /**
   * The ProseKit editor instance.
   *
   * @default null
   * @hidden
   */
  editor?: AutocompleteRootElementProps['editor'];
  /**
   * The regular expression to match the query text to autocomplete.
   *
   * @default null
   */
  regex?: AutocompleteRootElementProps['regex'];
  /**
   * The filter function to determine if an item should be shown in the
   * listbox.
   *
   * @default defaultItemFilter
   */
  filter?: AutocompleteRootElementProps['filter'];
  /**
   * An element to position the popup against. By default, the popup will be positioned against the text content that triggers the autocomplete.
   *
   * @default null
   */
  anchor?: AutocompleteRootElementProps['anchor'];
  /** Fired when the open state changes. */
  onOpenChange?: (event: AutocompleteRootEvents['openChange']) => void;
  /** Fired when the query changes. */
  onQueryChange?: (event: AutocompleteRootEvents['queryChange']) => void;
  /**
   * Emitted when the selected value changes. Only available when multiple is
   * false.
   */
  onValueChange?: (event: AutocompleteRootEvents['valueChange']) => void;
  /**
   * Emitted when the selected values change. Only available when multiple is
   * true.
   */
  onValuesChange?: (event: AutocompleteRootEvents['valuesChange']) => void;
}

/** A Vue component that renders an `prosekit-autocomplete-root` custom element. */
export const AutocompleteRoot: DefineSetupFnComponent<AutocompleteRootProps & HTMLAttributes> = /* @__PURE__ */ defineComponent<AutocompleteRootProps & HTMLAttributes>(
  (props, { slots }) => {
    registerAutocompleteRootElement();

    const elementRef = shallowRef<HTMLElement | null>(null);

    const p1Fallback = useEditorContext();

    const splittedProps = computed(() => {
      const { anchor: p0, editor: p1, filter: p2, regex: p3, onOpenChange: e0, onQueryChange: e1, onValueChange: e2, onValuesChange: e3, ...restProps } = props;
      return [[p0, p1, p2, p3, e0, e1, e2, e3], restProps] as const;
    });

    const handlers: Array<((event: any) => void) | undefined> = [];

    watchEffect(() => {
      const element = elementRef.value;
      if (!element) return;

      const [p0, p1, p2, p3, e0, e1, e2, e3] = splittedProps.value[0];

      Object.assign(element, { anchor: p0, editor: p1 ?? p1Fallback, filter: p2, regex: p3 });

      handlers.length = 0;
      handlers.push(e0);
      handlers.push(e1);
      handlers.push(e2);
      handlers.push(e3);
    });

    watchEffect(() => {
      const element = elementRef.value;
      if (!element) return;

      const ac = new AbortController();
      for (const [index, eventName] of ['openChange', 'queryChange', 'valueChange', 'valuesChange'].entries()) {
        element.addEventListener(
          eventName,
          (event: Event) => {
            handlers[index]?.(event);
          },
          { signal: ac.signal },
        );
      }
      return () => ac.abort();
    });

    return () => {
      const restProps = splittedProps.value[1];
      return h('prosekit-autocomplete-root', { ...restProps, ref: elementRef }, slots.default?.());
    };
  },
  { props: ['anchor', 'editor', 'filter', 'regex', 'onOpenChange', 'onQueryChange', 'onValueChange', 'onValuesChange'] },
);
