/**
 * This file is auto-generated by the "@aria-ui/cli" tool. Do not edit this file directly.
 */

import {
  registerAutocompletePopoverElement,
  type AutocompletePopoverEvents,
  type AutocompletePopoverProps as AutocompletePopoverElementProps,
} from "@prosekit/web/autocomplete";
import {
  defineComponent,
  h,
  type DefineSetupFnComponent,
  type HTMLAttributes,
  shallowRef,
  computed,
  watchEffect,
} from "vue";

import { useEditorContext } from "../../injection/editor-context.ts";

/**
 * Props for the {@link AutocompletePopover} Vue component.
 *
 * @public
 */
export interface AutocompletePopoverProps {
  /**
   * The ProseKit editor instance.
   *
   * @default null
   * @hidden
   */
  editor?: AutocompletePopoverElementProps["editor"];
  /**
   * The regular expression to match the query text to autocomplete.
   *
   * @default null
   */
  regex?: AutocompletePopoverElementProps["regex"];
  /**
   * The placement of the popover, relative to the text cursor.
   *
   * @default "bottom-start"
   */
  placement?: AutocompletePopoverElementProps["placement"];
  /**
   * The distance between the popover and the hovered block.
   *
   * @default 4
   */
  offset?: AutocompletePopoverElementProps["offset"];
  /** @default true */
  inline?: AutocompletePopoverElementProps["inline"];
  /** @default true */
  hoist?: AutocompletePopoverElementProps["hoist"];
  /** @default true */
  fitViewport?: AutocompletePopoverElementProps["fitViewport"];
  /** @default "The body element" */
  boundary?: AutocompletePopoverElementProps["boundary"];
  /** @default 8 */
  overflowPadding?: AutocompletePopoverElementProps["overflowPadding"];
  /**
   * The strategy to use for positioning
   *
   * @default "absolute"
   */
  strategy?: AutocompletePopoverElementProps["strategy"];
  /**
   * Options to activate auto-update listeners
   *
   * @see https://floating-ui.com/docs/autoUpdate
   *
   * @default true
   */
  autoUpdate?: AutocompletePopoverElementProps["autoUpdate"];
  /**
   * Whether to flip the `placement` in order to keep it in view when the
   * preferred placement(s) will overflow the clipping boundary. You can also
   * provide an array of placements to try sequentially if the preferred
   * `placement` does not fit.
   *
   * @default true
   */
  flip?: AutocompletePopoverElementProps["flip"];
  /**
   * Whether the floating element should shift to keep it in view.
   *
   * @default true
   */
  shift?: AutocompletePopoverElementProps["shift"];
  /**
   * Whether the floating element can overlap the reference element to keep it
   * in view.
   *
   * @default false
   */
  overlap?: AutocompletePopoverElementProps["overlap"];
  /**
   * Whether to constrain the floating element's width so that it matches the
   * reference element.
   *
   * @default false
   */
  sameWidth?: AutocompletePopoverElementProps["sameWidth"];
  /**
   * Whether to constrain the floating element's height so that it matches the
   * reference element.
   *
   * @default false
   */
  sameHeight?: AutocompletePopoverElementProps["sameHeight"];
  /**
   * Whether to hide the floating element when the reference element or the
   * floating element is fully clipped.
   *
   * @default false
   */
  hide?: AutocompletePopoverElementProps["hide"];
  /**
   * Describes the root boundary that the element will be checked for overflow relative to.
   * Please see https://floating-ui.com/docs/detectoverflow#rootboundary for more information.
   *
   * @default 'viewport'
   */
  rootBoundary?: AutocompletePopoverElementProps["rootBoundary"];
  /**
   * The element that will be used to check for overflow. Please see
   * https://floating-ui.com/docs/detectoverflow#elementcontext for more
   * information.
   *
   * @default 'floating'
   */
  elementContext?: AutocompletePopoverElementProps["elementContext"];
  /**
   * Whether to check the alternate elementContext's boundary. Please see
   * https://floating-ui.com/docs/detectoverflow#altboundary for more
   * information.
   *
   * @default false
   */
  altBoundary?: AutocompletePopoverElementProps["altBoundary"];
  /** Fired when the open state changes. */
  onOpenChange?: (event: AutocompletePopoverEvents["openChange"]) => void;
  /** Fired when the query changes. */
  onQueryChange?: (event: AutocompletePopoverEvents["queryChange"]) => void;
}

/**
 * A Vue component that renders an `prosekit-autocomplete-popover` custom element.
 *
 * @public
 */
export const AutocompletePopover: DefineSetupFnComponent<
  AutocompletePopoverProps & HTMLAttributes
> = /* @__PURE__ */ defineComponent<AutocompletePopoverProps & HTMLAttributes>(
  (props, { slots }) => {
    registerAutocompletePopoverElement();

    const elementRef = shallowRef<HTMLElement | null>(null);

    const p3Fallback = useEditorContext();

    const splittedProps = computed(() => {
      const {
        altBoundary: p0,
        autoUpdate: p1,
        boundary: p2,
        editor: p3,
        elementContext: p4,
        fitViewport: p5,
        flip: p6,
        hide: p7,
        hoist: p8,
        inline: p9,
        offset: p10,
        overflowPadding: p11,
        overlap: p12,
        placement: p13,
        regex: p14,
        rootBoundary: p15,
        sameHeight: p16,
        sameWidth: p17,
        shift: p18,
        strategy: p19,
        onOpenChange: e0,
        onQueryChange: e1,
        ...restProps
      } = props;
      return [
        [
          p0,
          p1,
          p2,
          p3,
          p4,
          p5,
          p6,
          p7,
          p8,
          p9,
          p10,
          p11,
          p12,
          p13,
          p14,
          p15,
          p16,
          p17,
          p18,
          p19,
          e0,
          e1,
        ],
        restProps,
      ] as const;
    });

    const handlers: (Function | undefined)[] = [];

    watchEffect(() => {
      const element = elementRef.value;
      if (!element) return;

      const [
        p0,
        p1,
        p2,
        p3,
        p4,
        p5,
        p6,
        p7,
        p8,
        p9,
        p10,
        p11,
        p12,
        p13,
        p14,
        p15,
        p16,
        p17,
        p18,
        p19,
        e0,
        e1,
      ] = splittedProps.value[0];

      Object.assign(element, {
        altBoundary: p0,
        autoUpdate: p1,
        boundary: p2,
        editor: p3 ?? p3Fallback,
        elementContext: p4,
        fitViewport: p5,
        flip: p6,
        hide: p7,
        hoist: p8,
        inline: p9,
        offset: p10,
        overflowPadding: p11,
        overlap: p12,
        placement: p13,
        regex: p14,
        rootBoundary: p15,
        sameHeight: p16,
        sameWidth: p17,
        shift: p18,
        strategy: p19,
      });

      handlers.length = 0;
      handlers.push(e0);
      handlers.push(e1);
    });

    watchEffect(() => {
      const element = elementRef.value;
      if (!element) return;

      const ac = new AbortController();
      for (const [index, eventName] of [
        "openChange",
        "queryChange",
      ].entries()) {
        element.addEventListener(
          eventName,
          (event: Event) => {
            handlers[index]?.(event);
          },
          { signal: ac.signal },
        );
      }
      return () => ac.abort();
    });

    return () => {
      const restProps = splittedProps.value[1];
      return h(
        "prosekit-autocomplete-popover",
        { ...restProps, ref: elementRef },
        slots.default?.(),
      );
    };
  },
  {
    props: [
      "altBoundary",
      "autoUpdate",
      "boundary",
      "editor",
      "elementContext",
      "fitViewport",
      "flip",
      "hide",
      "hoist",
      "inline",
      "offset",
      "overflowPadding",
      "overlap",
      "placement",
      "regex",
      "rootBoundary",
      "sameHeight",
      "sameWidth",
      "shift",
      "strategy",
      "onOpenChange",
      "onQueryChange",
    ],
  },
);

export type { AutocompletePopoverEvents };
export {
  AutocompletePopoverOpenChangeEvent,
  AutocompletePopoverQueryChangeEvent,
} from "@prosekit/web/autocomplete";
