/**
 * This file is auto-generated by the "@aria-ui/cli" tool. Do not edit this file directly.
 */

import { registerMenuTriggerElement, type MenuTriggerEvents, type MenuTriggerProps as MenuTriggerElementProps } from '@prosekit/web/menu';
import { defineComponent, h, type DefineSetupFnComponent, type HTMLAttributes, shallowRef, computed, watchEffect } from 'vue';

/**
 * Props for the {@link MenuTrigger} Vue component.
 *
 * @public
 */
export interface MenuTriggerProps {
  /**
   * Whether the component should ignore user interaction.
   *
   * @default false
   */
  disabled?: MenuTriggerElementProps['disabled'];
  /** Emitted when the menu is opened or closed. */
  onOpenChange?: (event: MenuTriggerEvents['openChange']) => void;
}

/**
 * A Vue component that renders an `prosekit-menu-trigger` custom element.
 *
 * @public
 */
export const MenuTrigger: DefineSetupFnComponent<MenuTriggerProps & HTMLAttributes> = /* @__PURE__ */ defineComponent<MenuTriggerProps & HTMLAttributes>(
  (props, { slots }) => {
    registerMenuTriggerElement();

    const elementRef = shallowRef<HTMLElement | null>(null);

    const splittedProps = computed(() => {
      const { disabled: p0, onOpenChange: e0, ...restProps } = props;
      return [[p0, e0], restProps] as const;
    });

    const handlers: Array<((event: any) => void) | undefined> = [];

    watchEffect(() => {
      const element = elementRef.value;
      if (!element) return;

      const [p0, e0] = splittedProps.value[0];

      Object.assign(element, { disabled: p0 });

      handlers.length = 0;
      handlers.push(e0);
    });

    watchEffect(() => {
      const element = elementRef.value;
      if (!element) return;

      const ac = new AbortController();
      for (const [index, eventName] of ['openChange'].entries()) {
        element.addEventListener(
          eventName,
          (event: Event) => {
            handlers[index]?.(event);
          },
          { signal: ac.signal },
        );
      }
      return () => ac.abort();
    });

    return () => {
      const restProps = splittedProps.value[1];
      return h('prosekit-menu-trigger', { ...restProps, ref: elementRef }, slots.default?.());
    };
  },
  { props: ['disabled', 'onOpenChange'] },
);
