// This file is auto-generated by "@aria-ui/cli". Do not edit this file directly.

import { registerMenuRootElement, type MenuRootEvents, type MenuRootProps as MenuRootElementProps } from '@prosekit/web/menu';
import { defineComponent, h, type DefineSetupFnComponent, type HTMLAttributes, shallowRef, computed, watchEffect } from 'vue';

/**
 * Props for the {@link MenuRoot} Vue component.
 *
 * @public
 */
export interface MenuRootProps {
  /**
   * Whether the overlay is initially open.
   * @default false
   */
  defaultOpen?: MenuRootElementProps['defaultOpen'];
  /**
   * Whether the overlay is currently open.
   * @default null
   */
  open?: MenuRootElementProps['open'];
  /**
   * Whether the component should ignore user interaction.
   * @default false
   */
  disabled?: MenuRootElementProps['disabled'];
  /** Emitted when the menu is opened or closed. */
  onOpenChange?: (event: MenuRootEvents['openChange']) => void;
}

/**
 * A Vue component that renders an `prosekit-menu-root` custom element.
 *
 * @public
 */
export const MenuRoot: DefineSetupFnComponent<MenuRootProps & HTMLAttributes> = /* @__PURE__ */ defineComponent<MenuRootProps & HTMLAttributes>(
  (props, { slots }) => {
    registerMenuRootElement();

    const elementRef = shallowRef<HTMLElement | null>(null);

    const splittedProps = computed(() => {
      const { defaultOpen: p0, disabled: p1, open: p2, onOpenChange: e0, ...restProps } = props;
      return [[p0, p1, p2, e0], restProps] as const;
    });

    const handlers: Array<((event: any) => void) | undefined> = [];

    watchEffect(() => {
      const element = elementRef.value;
      if (!element) return;

      const [p0, p1, p2, e0] = splittedProps.value[0];

      Object.assign(element, { defaultOpen: p0, disabled: p1, open: p2 });

      handlers.length = 0;
      handlers.push(e0);
    });

    watchEffect(() => {
      const element = elementRef.value;
      if (!element) return;

      const ac = new AbortController();
      for (const [index, eventName] of ['openChange'].entries()) {
        element.addEventListener(
          eventName,
          (event: Event) => {
            handlers[index]?.(event);
          },
          { signal: ac.signal },
        );
      }
      return () => ac.abort();
    });

    return () => {
      const restProps = splittedProps.value[1];
      return h('prosekit-menu-root', { ...restProps, ref: elementRef }, slots.default?.());
    };
  },
  { props: ['defaultOpen', 'disabled', 'open', 'onOpenChange'] },
);
