// This file is auto-generated by "@aria-ui/cli". Do not edit this file directly.

import { registerMenuSubmenuTriggerElement, type MenuSubmenuTriggerProps as MenuSubmenuTriggerElementProps } from '@prosekit/web/menu';
import { defineComponent, h, type DefineSetupFnComponent, type HTMLAttributes, shallowRef, computed, watchEffect } from 'vue';

/** Props for the {@link MenuSubmenuTrigger} Vue component. */
export interface MenuSubmenuTriggerProps {
  /**
   * The unique value for this submenu trigger in the parent menu.
   *
   * @default ""
   */
  value?: MenuSubmenuTriggerElementProps['value'];
  /**
   * Whether this submenu trigger is disabled.
   *
   * @default false
   */
  disabled?: MenuSubmenuTriggerElementProps['disabled'];
}

/** A Vue component that renders an `prosekit-menu-submenu-trigger` custom element. */
export const MenuSubmenuTrigger: DefineSetupFnComponent<MenuSubmenuTriggerProps & HTMLAttributes> = /* @__PURE__ */ defineComponent<MenuSubmenuTriggerProps & HTMLAttributes>(
  (props, { slots }) => {
    registerMenuSubmenuTriggerElement();

    const elementRef = shallowRef<HTMLElement | null>(null);

    const splittedProps = computed(() => {
      const { disabled: p0, value: p1, ...restProps } = props;
      return [[p0, p1], restProps] as const;
    });

    watchEffect(() => {
      const element = elementRef.value;
      if (!element) return;

      const [p0, p1] = splittedProps.value[0];

      Object.assign(element, { disabled: p0, value: p1 });
    });

    return () => {
      const restProps = splittedProps.value[1];
      return h('prosekit-menu-submenu-trigger', { ...restProps, ref: elementRef }, slots.default?.());
    };
  },
  { props: ['disabled', 'value'] },
);
