export { ProseKit, type ProseKitProps } from './components/prosekit'
export { useEditor } from './hooks/use-editor'
export { useExtension, type UseExtensionOptions } from './hooks/use-extension'
export { useKeymap } from './hooks/use-keymap'
export { useStateUpdate } from './hooks/use-state-update'
export type { MaybeAccessor, PropsWithChildren, PropsWithClass } from './types'
