export { ProseKit, type ProseKitProps } from './components/prosekit'
export { useEditor } from './hooks/use-editor'
export { useExtension } from './hooks/use-extension'
export { useKeymap } from './hooks/use-keymap'
export type { MaybeAccessor, PropsWithChildren, PropsWithClass } from './types'
