// This file is generated from gen-website-pages.ts
import { defineAsyncComponent } from 'vue'

export const loaders = {
  'minimal': defineAsyncComponent(() => import('./minimal/editor.vue')),
  'block-handle': defineAsyncComponent(() => import('./block-handle/editor.vue')),
  'blockquote': defineAsyncComponent(() => import('./blockquote/editor.vue')),
  'bold': defineAsyncComponent(() => import('./bold/editor.vue')),
  'code': defineAsyncComponent(() => import('./code/editor.vue')),
  'code-block': defineAsyncComponent(() => import('./code-block/editor.vue')),
  'code-block-themes': defineAsyncComponent(() => import('./code-block-themes/editor.vue')),
  'drop-cursor': defineAsyncComponent(() => import('./drop-cursor/editor.vue')),
  'full': defineAsyncComponent(() => import('./full/editor.vue')),
  'heading': defineAsyncComponent(() => import('./heading/editor.vue')),
  'horizontal-rule': defineAsyncComponent(() => import('./horizontal-rule/editor.vue')),
  'image-view': defineAsyncComponent(() => import('./image-view/editor.vue')),
  'inline-menu': defineAsyncComponent(() => import('./inline-menu/editor.vue')),
  'italic': defineAsyncComponent(() => import('./italic/editor.vue')),
  'keymap': defineAsyncComponent(() => import('./keymap/editor.vue')),
  'link': defineAsyncComponent(() => import('./link/editor.vue')),
  'link-mark-view': defineAsyncComponent(() => import('./link-mark-view/editor.vue')),
  'list': defineAsyncComponent(() => import('./list/editor.vue')),
  'mark-rule': defineAsyncComponent(() => import('./mark-rule/editor.vue')),
  'placeholder': defineAsyncComponent(() => import('./placeholder/editor.vue')),
  'readonly': defineAsyncComponent(() => import('./readonly/editor.vue')),
  'save-html': defineAsyncComponent(() => import('./save-html/editor.vue')),
  'save-json': defineAsyncComponent(() => import('./save-json/editor.vue')),
  'save-markdown': defineAsyncComponent(() => import('./save-markdown/editor.vue')),
  'slash-menu': defineAsyncComponent(() => import('./slash-menu/editor.vue')),
  'strike': defineAsyncComponent(() => import('./strike/editor.vue')),
  'table': defineAsyncComponent(() => import('./table/editor.vue')),
  'text-align': defineAsyncComponent(() => import('./text-align/editor.vue')),
  'text-color': defineAsyncComponent(() => import('./text-color/editor.vue')),
  'toolbar': defineAsyncComponent(() => import('./toolbar/editor.vue')),
  'typography': defineAsyncComponent(() => import('./typography/editor.vue')),
  'underline': defineAsyncComponent(() => import('./underline/editor.vue')),
  'unmount': defineAsyncComponent(() => import('./unmount/editor.vue')),
  'user-menu': defineAsyncComponent(() => import('./user-menu/editor.vue')),
  'user-menu-dynamic': defineAsyncComponent(() => import('./user-menu-dynamic/editor.vue')),
  'word-counter': defineAsyncComponent(() => import('./word-counter/editor.vue')),
}
