// This file is generated from update-website-pages.ts
import { defineAsyncComponent } from 'vue'

export const loaders = {
  'block-handle': defineAsyncComponent(() => import('prosekit-registry/vue/examples/block-handle').then((m) => m.ExampleEditor)),
  'blockquote': defineAsyncComponent(() => import('prosekit-registry/vue/examples/blockquote').then((m) => m.ExampleEditor)),
  'bold': defineAsyncComponent(() => import('prosekit-registry/vue/examples/bold').then((m) => m.ExampleEditor)),
  'code': defineAsyncComponent(() => import('prosekit-registry/vue/examples/code').then((m) => m.ExampleEditor)),
  'code-block': defineAsyncComponent(() => import('prosekit-registry/vue/examples/code-block').then((m) => m.ExampleEditor)),
  'code-block-themes': defineAsyncComponent(() => import('prosekit-registry/vue/examples/code-block-themes').then((m) => m.ExampleEditor)),
  'drop-cursor': defineAsyncComponent(() => import('prosekit-registry/vue/examples/drop-cursor').then((m) => m.ExampleEditor)),
  'emoji-rules': defineAsyncComponent(() => import('prosekit-registry/vue/examples/emoji-rules').then((m) => m.ExampleEditor)),
  'full': defineAsyncComponent(() => import('prosekit-registry/vue/examples/full').then((m) => m.ExampleEditor)),
  'gap-cursor': defineAsyncComponent(() => import('prosekit-registry/vue/examples/gap-cursor').then((m) => m.ExampleEditor)),
  'hard-break': defineAsyncComponent(() => import('prosekit-registry/vue/examples/hard-break').then((m) => m.ExampleEditor)),
  'heading': defineAsyncComponent(() => import('prosekit-registry/vue/examples/heading').then((m) => m.ExampleEditor)),
  'horizontal-rule': defineAsyncComponent(() => import('prosekit-registry/vue/examples/horizontal-rule').then((m) => m.ExampleEditor)),
  'image-view': defineAsyncComponent(() => import('prosekit-registry/vue/examples/image-view').then((m) => m.ExampleEditor)),
  'inline-menu': defineAsyncComponent(() => import('prosekit-registry/vue/examples/inline-menu').then((m) => m.ExampleEditor)),
  'italic': defineAsyncComponent(() => import('prosekit-registry/vue/examples/italic').then((m) => m.ExampleEditor)),
  'keymap': defineAsyncComponent(() => import('prosekit-registry/vue/examples/keymap').then((m) => m.ExampleEditor)),
  'link': defineAsyncComponent(() => import('prosekit-registry/vue/examples/link').then((m) => m.ExampleEditor)),
  'list': defineAsyncComponent(() => import('prosekit-registry/vue/examples/list').then((m) => m.ExampleEditor)),
  'list-custom-checkbox': defineAsyncComponent(() => import('prosekit-registry/vue/examples/list-custom-checkbox').then((m) => m.ExampleEditor)),
  'loro': defineAsyncComponent(() => import('prosekit-registry/vue/examples/loro').then((m) => m.ExampleEditor)),
  'minimal': defineAsyncComponent(() => import('prosekit-registry/vue/examples/minimal').then((m) => m.ExampleEditor)),
  'placeholder': defineAsyncComponent(() => import('prosekit-registry/vue/examples/placeholder').then((m) => m.ExampleEditor)),
  'search': defineAsyncComponent(() => import('prosekit-registry/vue/examples/search').then((m) => m.ExampleEditor)),
  'slash-menu': defineAsyncComponent(() => import('prosekit-registry/vue/examples/slash-menu').then((m) => m.ExampleEditor)),
  'strike': defineAsyncComponent(() => import('prosekit-registry/vue/examples/strike').then((m) => m.ExampleEditor)),
  'table': defineAsyncComponent(() => import('prosekit-registry/vue/examples/table').then((m) => m.ExampleEditor)),
  'text-color': defineAsyncComponent(() => import('prosekit-registry/vue/examples/text-color').then((m) => m.ExampleEditor)),
  'toolbar': defineAsyncComponent(() => import('prosekit-registry/vue/examples/toolbar').then((m) => m.ExampleEditor)),
  'typography': defineAsyncComponent(() => import('prosekit-registry/vue/examples/typography').then((m) => m.ExampleEditor)),
  'underline': defineAsyncComponent(() => import('prosekit-registry/vue/examples/underline').then((m) => m.ExampleEditor)),
  'user-menu': defineAsyncComponent(() => import('prosekit-registry/vue/examples/user-menu').then((m) => m.ExampleEditor)),
  'word-counter': defineAsyncComponent(() => import('prosekit-registry/vue/examples/word-counter').then((m) => m.ExampleEditor)),
  'yjs': defineAsyncComponent(() => import('prosekit-registry/vue/examples/yjs').then((m) => m.ExampleEditor)),
}
