<!-- This file is auto-generated by the "@aria-ui/cli" tool. Do not edit this file directly. -->

<script lang="ts">
  import { registerInlinePopoverRootElement } from '@prosekit/web/inline-popover'
  import type { InlinePopoverRootElement } from '@prosekit/web/inline-popover'
  import { useEditorContext } from '../../contexts/editor-context.ts'
  registerInlinePopoverRootElement()

  let { defaultOpen: p0, disabled: p1, dismissOnEscape: p2, editor: p3, open: p4, onOpenChange: e0, children = undefined, ...restProps } = $props()
  let element: InlinePopoverRootElement | undefined
  const handlers: EventListener[] = []

  const p3Fallback = useEditorContext()

  $effect(() => {
    if (!element) return

    Object.assign(element, { defaultOpen: p0, disabled: p1, dismissOnEscape: p2, editor: p3 ?? p3Fallback, open: p4 })

    handlers.length = 0
    handlers.push(e0)
  })

  $effect(() => {
    if (!element) return

    const ac = new AbortController()
    for (const [index, eventName] of ["openChange"].entries()) {
      element.addEventListener(eventName, (event) => handlers[index]?.(event), { signal: ac.signal })
    }
    return () => ac.abort()
  })
</script>

<prosekit-inline-popover-root {...restProps} bind:this={element}>{@render children?.()}</prosekit-inline-popover-root>
