<!-- This file is auto-generated by the "@aria-ui/cli" tool. Do not edit this file directly. -->

<script lang="js">
  import { registerInlinePopoverElement } from '@prosekit/web/inline-popover'
  import { useEditorContext } from '../../contexts/editor-context.ts'
  registerInlinePopoverElement()

  let { altBoundary: p0, autoUpdate: p1, boundary: p2, defaultOpen: p3, dismissOnEscape: p4, editor: p5, elementContext: p6, fitViewport: p7, flip: p8, hide: p9, hoist: p10, inline: p11, offset: p12, open: p13, overflowPadding: p14, overlap: p15, placement: p16, rootBoundary: p17, sameHeight: p18, sameWidth: p19, shift: p20, strategy: p21, onOpenChange: e0, children = undefined, ...restProps } = $props()
  let element
  const handlers = []

  const p5Fallback = useEditorContext()

  $effect.pre(() => {
    if (!element) return

    Object.assign(element, { altBoundary: p0, autoUpdate: p1, boundary: p2, defaultOpen: p3, dismissOnEscape: p4, editor: p5 ?? p5Fallback, elementContext: p6, fitViewport: p7, flip: p8, hide: p9, hoist: p10, inline: p11, offset: p12, open: p13, overflowPadding: p14, overlap: p15, placement: p16, rootBoundary: p17, sameHeight: p18, sameWidth: p19, shift: p20, strategy: p21 })

    handlers.length = 0
    handlers.push(e0)
  })

  $effect.pre(() => {
    if (!element) return

    const ac = new AbortController()
    for (const [index, eventName] of ["openChange"].entries()) {
      element.addEventListener(eventName, (event) => handlers[index]?.(event), { signal: ac.signal })
    }
    return () => ac.abort()
  })
</script>

<prosekit-inline-popover {...restProps} bind:this={element}>{@render children?.()}</prosekit-inline-popover>
