/**
 * This file is auto-generated by the "@aria-ui/cli" tool. Do not edit this file directly.
 */

import type { InlinePopoverRootEvents, InlinePopoverRootProps as InlinePopoverRootElementProps } from '@prosekit/web/inline-popover';
import type { Component, Snippet } from 'svelte';

import InlinePopoverRootComponent from './inline-popover-root.gen.svelte';

/**
 * Props for the {@link InlinePopoverRoot} Svelte component.
 *
 * @public
 */
export interface InlinePopoverRootProps {
  /**
   * The ProseKit editor instance.
   *
   * @default null
   * @hidden
   */
  editor?: InlinePopoverRootElementProps['editor'];
  /**
   * Whether the popover is open by default when some inline content is
   * selected.
   *
   * @default true
   */
  defaultOpen?: InlinePopoverRootElementProps['defaultOpen'];
  /**
   * Whether the inline popover should be dismissed when the editor receives an
   * Escape key press.
   *
   * @default true
   */
  dismissOnEscape?: InlinePopoverRootElementProps['dismissOnEscape'];
  /**
   * Whether the overlay is currently open.
   * @default null
   */
  open?: InlinePopoverRootElementProps['open'];
  /**
   * Whether the component should ignore user interaction.
   * @default false
   */
  disabled?: InlinePopoverRootElementProps['disabled'];
  /** */
  onOpenChange?: (event: InlinePopoverRootEvents['openChange']) => void;
  children?: Snippet;
  [key: string]: unknown;
}

/**
 * A Svelte component that renders an `prosekit-inline-popover-root` custom element.
 *
 * @public
 */
export const InlinePopoverRoot: Component<InlinePopoverRootProps> = InlinePopoverRootComponent as unknown as Component<InlinePopoverRootProps>;

export type { InlinePopoverRootEvents };
