<!-- This file is auto-generated by the "@aria-ui/cli" tool. Do not edit this file directly. -->

<script lang="ts">
  import { registerInlinePopoverPopupElement } from '@prosekit/web/inline-popover'
  registerInlinePopoverPopupElement()

  let { children = undefined, ...restProps } = $props()
</script>

<prosekit-inline-popover-popup {...restProps}>{@render children?.()}</prosekit-inline-popover-popup>
