<script lang="ts">
  // This file is auto-generated by "@aria-ui/cli". Do not edit this file directly.
  import { registerInlinePopoverPopupElement } from '@prosekit/web/inline-popover'
  registerInlinePopoverPopupElement()

  let { children = undefined, ...restProps } = $props()
</script>

<prosekit-inline-popover-popup {...restProps}>{@render children?.()}</prosekit-inline-popover-popup>
