// This file is generated from update-loader.ts
import { defineAsyncComponent } from 'vue'

export const loaders = {
  'block-handle': defineAsyncComponent(() => import('./examples/block-handle').then((m) => m.ExampleEditor)),
  'blockquote': defineAsyncComponent(() => import('./examples/blockquote').then((m) => m.ExampleEditor)),
  'bold': defineAsyncComponent(() => import('./examples/bold').then((m) => m.ExampleEditor)),
  'change-tracking': defineAsyncComponent(() => import('./examples/change-tracking').then((m) => m.ExampleEditor)),
  'code': defineAsyncComponent(() => import('./examples/code').then((m) => m.ExampleEditor)),
  'code-block': defineAsyncComponent(() => import('./examples/code-block').then((m) => m.ExampleEditor)),
  'code-block-themes': defineAsyncComponent(() => import('./examples/code-block-themes').then((m) => m.ExampleEditor)),
  'drop-cursor': defineAsyncComponent(() => import('./examples/drop-cursor').then((m) => m.ExampleEditor)),
  'emoji-rules': defineAsyncComponent(() => import('./examples/emoji-rules').then((m) => m.ExampleEditor)),
  'full': defineAsyncComponent(() => import('./examples/full').then((m) => m.ExampleEditor)),
  'gap-cursor': defineAsyncComponent(() => import('./examples/gap-cursor').then((m) => m.ExampleEditor)),
  'hard-break': defineAsyncComponent(() => import('./examples/hard-break').then((m) => m.ExampleEditor)),
  'heading': defineAsyncComponent(() => import('./examples/heading').then((m) => m.ExampleEditor)),
  'horizontal-rule': defineAsyncComponent(() => import('./examples/horizontal-rule').then((m) => m.ExampleEditor)),
  'image-view': defineAsyncComponent(() => import('./examples/image-view').then((m) => m.ExampleEditor)),
  'inline-menu': defineAsyncComponent(() => import('./examples/inline-menu').then((m) => m.ExampleEditor)),
  'italic': defineAsyncComponent(() => import('./examples/italic').then((m) => m.ExampleEditor)),
  'keymap': defineAsyncComponent(() => import('./examples/keymap').then((m) => m.ExampleEditor)),
  'link': defineAsyncComponent(() => import('./examples/link').then((m) => m.ExampleEditor)),
  'link-mark-view': defineAsyncComponent(() => import('./examples/link-mark-view').then((m) => m.ExampleEditor)),
  'list': defineAsyncComponent(() => import('./examples/list').then((m) => m.ExampleEditor)),
  'list-custom-checkbox': defineAsyncComponent(() => import('./examples/list-custom-checkbox').then((m) => m.ExampleEditor)),
  'loro': defineAsyncComponent(() => import('./examples/loro').then((m) => m.ExampleEditor)),
  'mark-rule': defineAsyncComponent(() => import('./examples/mark-rule').then((m) => m.ExampleEditor)),
  'minimal': defineAsyncComponent(() => import('./examples/minimal').then((m) => m.ExampleEditor)),
  'placeholder': defineAsyncComponent(() => import('./examples/placeholder').then((m) => m.ExampleEditor)),
  'readonly': defineAsyncComponent(() => import('./examples/readonly').then((m) => m.ExampleEditor)),
  'search': defineAsyncComponent(() => import('./examples/search').then((m) => m.ExampleEditor)),
  'slash-menu': defineAsyncComponent(() => import('./examples/slash-menu').then((m) => m.ExampleEditor)),
  'strike': defineAsyncComponent(() => import('./examples/strike').then((m) => m.ExampleEditor)),
  'table': defineAsyncComponent(() => import('./examples/table').then((m) => m.ExampleEditor)),
  'text-align': defineAsyncComponent(() => import('./examples/text-align').then((m) => m.ExampleEditor)),
  'text-color': defineAsyncComponent(() => import('./examples/text-color').then((m) => m.ExampleEditor)),
  'toolbar': defineAsyncComponent(() => import('./examples/toolbar').then((m) => m.ExampleEditor)),
  'typography': defineAsyncComponent(() => import('./examples/typography').then((m) => m.ExampleEditor)),
  'underline': defineAsyncComponent(() => import('./examples/underline').then((m) => m.ExampleEditor)),
  'unmount': defineAsyncComponent(() => import('./examples/unmount').then((m) => m.ExampleEditor)),
  'user-menu': defineAsyncComponent(() => import('./examples/user-menu').then((m) => m.ExampleEditor)),
  'word-counter': defineAsyncComponent(() => import('./examples/word-counter').then((m) => m.ExampleEditor)),
  'yjs': defineAsyncComponent(() => import('./examples/yjs').then((m) => m.ExampleEditor)),
}
