/**
 * This file is auto-generated by the "@aria-ui/cli" tool. Do not edit this file directly.
 */

import { PreactWrapper } from "@aria-ui-v2/integrations/preact";
import { createElement, type HTMLAttributes, type Ref } from "preact";
import {
  forwardRef,
  type ForwardRefExoticComponent,
  type RefAttributes,
} from "preact/compat";
import {
  registerResizableRootElement,
  type ResizableRootElement,
  type ResizableRootProps as ResizableRootElementProps,
  type ResizableRootEvents,
} from "@prosekit/web/resizable";

const propNames: string[] = ["aspectRatio", "height", "width"];
const eventNameMap: Record<string, string> = {
  onResizeEnd: "resizeEnd",
  onResizeStart: "resizeStart",
};

/**
 * Props for the {@link ResizableRoot} Preact component.
 *
 * @public
 */
export interface ResizableRootProps extends HTMLAttributes<ResizableRootElement> {
  /**
   * The width of the resizable element.
   *
   * @default null
   */
  width?: ResizableRootElementProps["width"];
  /**
   * The height of the resizable element.
   *
   * @default null
   */
  height?: ResizableRootElementProps["height"];
  /**
   * The aspect ratio of the resizable element.
   *
   * @default null
   */
  aspectRatio?: ResizableRootElementProps["aspectRatio"];
  /** Emitted when a resize operation starts. */
  onResizeStart?: (event: ResizableRootEvents["resizeStart"]) => void;
  /** Emitted when a resize operation ends. */
  onResizeEnd?: (event: ResizableRootEvents["resizeEnd"]) => void;
}

function ResizableRootComponent(
  props: ResizableRootProps,
  forwardedRef: Ref<ResizableRootElement>,
) {
  registerResizableRootElement();
  return createElement(PreactWrapper, {
    as: "prosekit-resizable-root",
    propNames,
    eventNameMap,
    props,
    forwardedRef,
  });
}

/**
 * A Preact component that renders an `prosekit-resizable-root` custom element.
 *
 * @public
 */
export const ResizableRoot: ForwardRefExoticComponent<
  ResizableRootProps & RefAttributes<ResizableRootElement>
> = /* @__PURE__ */ forwardRef(ResizableRootComponent);

export type { ResizableRootEvents };
export { ResizeEndEvent, ResizeStartEvent } from "@prosekit/web/resizable";
