/**
 * This file is auto-generated by the "@aria-ui/cli" tool. Do not edit this file directly.
 */

import {
  registerBlockHandlePopoverElement,
  type BlockHandlePopoverElement,
  type BlockHandlePopoverEvents,
  type BlockHandlePopoverProps as BlockHandlePopoverElementProps,
} from "@prosekit/web/block-handle";
import { createEffect, createSignal, mergeProps, splitProps } from "solid-js";
import type { Component, JSX } from "solid-js";
import h from "solid-js/h";
import { useEditorContext } from "../../contexts/editor-context.ts";

/**
 * Props for the {@link BlockHandlePopover} Solid component.
 *
 * @public
 */
export interface BlockHandlePopoverProps extends JSX.HTMLAttributes<BlockHandlePopoverElement> {
  /**
   * The ProseKit editor instance.
   *
   * @default null
   * @hidden
   */
  editor?: BlockHandlePopoverElementProps["editor"];
  /**
   * The placement of the popover, relative to the hovered block.
   *
   * @default "left"
   */
  placement?: BlockHandlePopoverElementProps["placement"];
  /**
   * Whether to use the browser [Popover API](https://developer.mozilla.org/en-US/docs/Web/API/Popover_API)
   * to place the floating element on top of other page content.
   *
   * @default false
   */
  hoist?: BlockHandlePopoverElementProps["hoist"];
  /**
   * @default false
   * @hidden
   */
  flip?: BlockHandlePopoverElementProps["flip"];
  /**
   * @default false
   * @hidden
   */
  shift?: BlockHandlePopoverElementProps["shift"];
  /**
   * @default true
   * @hidden
   */
  hide?: BlockHandlePopoverElementProps["hide"];
  /**
   * The strategy to use for positioning
   *
   * @default "absolute"
   */
  strategy?: BlockHandlePopoverElementProps["strategy"];
  /**
   * Options to activate auto-update listeners
   *
   * @see https://floating-ui.com/docs/autoUpdate
   *
   * @default true
   */
  autoUpdate?: BlockHandlePopoverElementProps["autoUpdate"];
  /**
   * The distance between the reference and floating element.
   *
   * @default 6
   */
  offset?: BlockHandlePopoverElementProps["offset"];
  /**
   * Whether the floating element can overlap the reference element to keep it
   * in view.
   *
   * @default false
   */
  overlap?: BlockHandlePopoverElementProps["overlap"];
  /**
   * Whether to constrain the floating element's width and height to not exceed
   * the viewport.
   *
   * @default false
   */
  fitViewport?: BlockHandlePopoverElementProps["fitViewport"];
  /**
   * Whether to constrain the floating element's width so that it matches the
   * reference element.
   *
   * @default false
   */
  sameWidth?: BlockHandlePopoverElementProps["sameWidth"];
  /**
   * Whether to constrain the floating element's height so that it matches the
   * reference element.
   *
   * @default false
   */
  sameHeight?: BlockHandlePopoverElementProps["sameHeight"];
  /**
   * Whether to improve positioning for inline reference elements that span over
   * multiple lines.
   *
   * @default false
   */
  inline?: BlockHandlePopoverElementProps["inline"];
  /**
   * Describes the clipping element(s) or area that overflow will be checked relative to.
   * Please see https://floating-ui.com/docs/detectoverflow#boundary for more information.
   *
   * @default 'clippingAncestors'
   */
  boundary?: BlockHandlePopoverElementProps["boundary"];
  /**
   * Describes the root boundary that the element will be checked for overflow relative to.
   * Please see https://floating-ui.com/docs/detectoverflow#rootboundary for more information.
   *
   * @default 'viewport'
   */
  rootBoundary?: BlockHandlePopoverElementProps["rootBoundary"];
  /**
   * Describes the virtual padding around the boundary to check for overflow.
   * Please see https://floating-ui.com/docs/detectoverflow#padding for more information.
   *
   * @default 4
   */
  overflowPadding?: BlockHandlePopoverElementProps["overflowPadding"];
  /**
   * The element that will be used to check for overflow. Please see
   * https://floating-ui.com/docs/detectoverflow#elementcontext for more
   * information.
   *
   * @default 'floating'
   */
  elementContext?: BlockHandlePopoverElementProps["elementContext"];
  /**
   * Whether to check the alternate elementContext's boundary. Please see
   * https://floating-ui.com/docs/detectoverflow#altboundary for more
   * information.
   *
   * @default false
   */
  altBoundary?: BlockHandlePopoverElementProps["altBoundary"];
  /** Fired when the hovered block changes. */
  onStateChange?: (event: BlockHandlePopoverEvents["stateChange"]) => void;
}

/**
 * A Solid component that renders an `prosekit-block-handle-popover` custom element.
 *
 * @public
 */
export const BlockHandlePopover: Component<BlockHandlePopoverProps> = (
  props,
): any => {
  registerBlockHandlePopoverElement();

  const [getElement, setElement] =
    createSignal<BlockHandlePopoverElement | null>(null);
  const handlers: Array<((event: any) => void) | undefined> = [];

  const [elementProps, eventHandlers, restProps] = splitProps(
    props,
    [
      "altBoundary",
      "autoUpdate",
      "boundary",
      "editor",
      "elementContext",
      "fitViewport",
      "flip",
      "hide",
      "hoist",
      "inline",
      "offset",
      "overflowPadding",
      "overlap",
      "placement",
      "rootBoundary",
      "sameHeight",
      "sameWidth",
      "shift",
      "strategy",
    ],
    ["onStateChange"],
  );

  const p3Fallback = useEditorContext();

  createEffect(() => {
    const element = getElement();
    if (!element) return;

    Object.assign(element, {
      altBoundary: elementProps.altBoundary,
      autoUpdate: elementProps.autoUpdate,
      boundary: elementProps.boundary,
      editor: elementProps.editor ?? p3Fallback,
      elementContext: elementProps.elementContext,
      fitViewport: elementProps.fitViewport,
      flip: elementProps.flip,
      hide: elementProps.hide,
      hoist: elementProps.hoist,
      inline: elementProps.inline,
      offset: elementProps.offset,
      overflowPadding: elementProps.overflowPadding,
      overlap: elementProps.overlap,
      placement: elementProps.placement,
      rootBoundary: elementProps.rootBoundary,
      sameHeight: elementProps.sameHeight,
      sameWidth: elementProps.sameWidth,
      shift: elementProps.shift,
      strategy: elementProps.strategy,
    });

    handlers.length = 0;
    handlers.push(eventHandlers.onStateChange);
  });

  createEffect(() => {
    const element = getElement();
    if (!element) return;

    const ac = new AbortController();
    for (const [index, eventName] of ["stateChange"].entries()) {
      element.addEventListener(
        eventName,
        (event) => {
          handlers[index]?.(event);
        },
        { signal: ac.signal },
      );
    }
    return () => ac.abort();
  });

  return h(
    "prosekit-block-handle-popover",
    mergeProps(restProps, {
      ref: (el: BlockHandlePopoverElement | null) => {
        setElement(el);
      },
    }),
  );
};

export type { BlockHandlePopoverEvents };
export { BlockHandlePopoverStateChangeEvent } from "@prosekit/web/block-handle";
