// This file is auto-generated by "@aria-ui/cli". Do not edit this file directly.

import { registerBlockHandleAddElement, type BlockHandleAddElement, type BlockHandleAddProps as BlockHandleAddElementProps } from '@prosekit/web/block-handle';
import { createEffect, createSignal, mergeProps, splitProps } from 'solid-js';
import type { Component, JSX } from 'solid-js';
import h from 'solid-js/h';

import { useEditorContext } from '../../contexts/editor-context.ts';

/** Props for the {@link BlockHandleAdd} Solid component. */
export interface BlockHandleAddProps {
  /**
   * The ProseKit editor instance.
   *
   * @default null
   * @hidden
   */
  editor?: BlockHandleAddElementProps['editor'];
}

/** A Solid component that renders an `prosekit-block-handle-add` custom element. */
export const BlockHandleAdd: Component<BlockHandleAddProps & JSX.HTMLAttributes<BlockHandleAddElement>> = (props): any => {
  registerBlockHandleAddElement();

  const [getElement, setElement] = createSignal<BlockHandleAddElement | null>(null);

  const [elementProps, restProps] = splitProps(props, ['editor']);

  const p0Fallback = useEditorContext();

  createEffect(() => {
    const element = getElement();
    if (!element) return;

    Object.assign(element, { editor: elementProps.editor ?? p0Fallback });
  });

  return () =>
    h(
      'prosekit-block-handle-add',
      mergeProps(restProps, {
        ref: (el: BlockHandleAddElement | null) => {
          setElement(el);
        },
      }),
    );
};
