/**
 * This file is auto-generated by the "@aria-ui/cli" tool. Do not edit this file directly.
 */

export {
  InlinePopover,
  type InlinePopoverProps,
  type InlinePopoverEvents,
  OpenChangeEvent,
} from "./inline-popover.gen.ts";
