/**
 * This file is auto-generated by the "@aria-ui/cli" tool. Do not edit this file directly.
 */

import {
  defineComponent,
  h,
  type DefineSetupFnComponent,
  type HTMLAttributes,
} from "vue";
import { registerPopoverPopupElement } from "@prosekit/web/popover";

/**
 * Props for the {@link PopoverPopup} Vue component.
 *
 * @public
 */
export interface PopoverPopupProps {}

/**
 * A Vue component that renders an `prosekit-popover-popup` custom element.
 *
 * @public
 */
export const PopoverPopup: DefineSetupFnComponent<
  PopoverPopupProps & HTMLAttributes
> = /* @__PURE__ */ defineComponent<PopoverPopupProps & HTMLAttributes>(
  (props, { slots }) => {
    registerPopoverPopupElement();

    return () => {
      const _props = { ...props };
      return h("prosekit-popover-popup", _props, slots.default?.());
    };
  },
  { props: [] },
);
