// This file is auto-generated by "@aria-ui/cli". Do not edit this file directly.

import { registerPopoverPopupElement } from '@prosekit/web/popover';
import { defineComponent, h, type DefineSetupFnComponent, type HTMLAttributes } from 'vue';

/** Props for the {@link PopoverPopup} Vue component. */
export interface PopoverPopupProps {}

/** A Vue component that renders an `prosekit-popover-popup` custom element. */
export const PopoverPopup: DefineSetupFnComponent<PopoverPopupProps & HTMLAttributes> = /* @__PURE__ */ defineComponent<PopoverPopupProps & HTMLAttributes>(
  (props, { slots }) => {
    registerPopoverPopupElement();

    return () => {
      return h('prosekit-popover-popup', props, slots.default?.());
    };
  },
  { props: [] },
);
