/**
 * This file is auto-generated by the "@aria-ui/cli" tool. Do not edit this file directly.
 */

import {
  defineComponent,
  h,
  type DefineSetupFnComponent,
  type HTMLAttributes,
} from "vue";
import {
  registerPopoverTriggerElement,
  type PopoverTriggerEvents,
  type PopoverTriggerProps as PopoverTriggerElementProps,
  PopoverTriggerPropsDeclaration,
} from "@prosekit/web/popover";

/**
 * Props for the {@link PopoverTrigger} Vue component.
 *
 * @public
 */
export interface PopoverTriggerProps {
  /**
   * Whether the component should ignore user interaction.
   * @default false
   */
  disabled?: PopoverTriggerElementProps["disabled"];
  /**
   * Whether the popover should also open when the trigger is hovered.
   * @default false
   */
  openOnHover?: PopoverTriggerElementProps["openOnHover"];
  /**
   * The delay in milliseconds before opening the popover when hovering.
   * Only applies when `openOnHover` is true.
   * @default 300
   */
  delay?: PopoverTriggerElementProps["delay"];
  /**
   * The delay in milliseconds before closing the popover when hover ends.
   * Only applies when `openOnHover` is true.
   * @default 0
   */
  closeDelay?: PopoverTriggerElementProps["closeDelay"];
  /** Emitted when the popover is opened or closed. */
  onOpenChange?: (event: PopoverTriggerEvents["openChange"]) => void;
}

/**
 * A Vue component that renders an `prosekit-popover-trigger` custom element.
 *
 * @public
 */
export const PopoverTrigger: DefineSetupFnComponent<
  PopoverTriggerProps & HTMLAttributes
> = /* @__PURE__ */ defineComponent<PopoverTriggerProps & HTMLAttributes>(
  (props, { slots }) => {
    registerPopoverTriggerElement();
    const _eventHandlers: Record<string, Function> = {};
    let _abortController: AbortController | undefined;

    const _ref = (element: HTMLElement | null | undefined) => {
      _abortController?.abort();
      _abortController = undefined;

      if (!element) {
        return;
      }

      _abortController = new AbortController();
      const abortSignal = _abortController.signal;

      element.addEventListener(
        "openChange",
        (event) => {
          _eventHandlers["onOpenChange"]?.(event);
        },
        { signal: abortSignal },
      );
    };

    return () => {
      const _props: Record<string, unknown> = {};
      for (const [key, value] of Object.entries(props)) {
        switch (key) {
          case "closeDelay":
          case "delay":
          case "disabled":
          case "openOnHover":
            _props["." + key] = value;
            break;
          case "onOpenChange":
            _eventHandlers[key] = value as Function;
            break;
          default:
            _props[key] = value;
        }
      }

      _props["ref"] = _ref;
      return h("prosekit-popover-trigger", _props, slots.default?.());
    };
  },
  {
    props: {
      closeDelay: {
        default: PopoverTriggerPropsDeclaration.closeDelay.default,
      },
      delay: { default: PopoverTriggerPropsDeclaration.delay.default },
      disabled: { default: PopoverTriggerPropsDeclaration.disabled.default },
      openOnHover: {
        default: PopoverTriggerPropsDeclaration.openOnHover.default,
      },
      onOpenChange: { type: Function },
    } as Record<string, unknown>,
  },
);

export type { PopoverTriggerEvents };
export { OpenChangeEvent } from "@prosekit/web/popover";
