// This file is auto-generated by "@aria-ui/cli". Do not edit this file directly.

import { registerDropIndicatorElement, type DropIndicatorProps as DropIndicatorElementProps } from '@prosekit/web/drop-indicator';
import { defineComponent, h, type DefineSetupFnComponent, type HTMLAttributes, shallowRef, computed, watchEffect } from 'vue';

import { useEditorContext } from '../../injection/editor-context.ts';

/** Props for the {@link DropIndicator} Vue component. */
export interface DropIndicatorProps {
  /**
   * The ProseKit editor instance.
   *
   * @default null
   * @hidden
   */
  editor?: DropIndicatorElementProps['editor'];
  /**
   * The line width in pixels.
   *
   * @default 2
   */
  width?: DropIndicatorElementProps['width'];
}

/** A Vue component that renders an `prosekit-drop-indicator` custom element. */
export const DropIndicator: DefineSetupFnComponent<DropIndicatorProps & HTMLAttributes> = /* @__PURE__ */ defineComponent<DropIndicatorProps & HTMLAttributes>(
  (props, { slots }) => {
    registerDropIndicatorElement();

    const elementRef = shallowRef<HTMLElement | null>(null);

    const p0Fallback = useEditorContext();

    const splittedProps = computed(() => {
      const { editor: p0, width: p1, ...restProps } = props;
      return [[p0, p1], restProps] as const;
    });

    watchEffect(() => {
      const element = elementRef.value;
      if (!element) return;

      const [p0, p1] = splittedProps.value[0];

      Object.assign(element, { editor: p0 ?? p0Fallback, width: p1 });
    });

    return () => {
      const restProps = splittedProps.value[1];
      return h('prosekit-drop-indicator', { ...restProps, ref: elementRef }, slots.default?.());
    };
  },
  { props: ['editor', 'width'] },
);
