/**
 * This file is auto-generated by the "@aria-ui/cli" tool. Do not edit this file directly.
 */

import {
  defineComponent,
  h,
  type DefineSetupFnComponent,
  type HTMLAttributes,
} from "vue";
import {
  registerResizableRootElement,
  type ResizableRootEvents,
  type ResizableRootProps as ResizableRootElementProps,
  ResizableRootPropsDeclaration,
} from "@prosekit/web/resizable";

/**
 * Props for the {@link ResizableRoot} Vue component.
 *
 * @public
 */
export interface ResizableRootProps {
  /**
   * The width of the resizable element.
   *
   * @default null
   */
  width?: ResizableRootElementProps["width"];
  /**
   * The height of the resizable element.
   *
   * @default null
   */
  height?: ResizableRootElementProps["height"];
  /**
   * The aspect ratio of the resizable element.
   *
   * @default null
   */
  aspectRatio?: ResizableRootElementProps["aspectRatio"];
  /** Emitted when a resize operation starts. */
  onResizeStart?: (event: ResizableRootEvents["resizeStart"]) => void;
  /** Emitted when a resize operation ends. */
  onResizeEnd?: (event: ResizableRootEvents["resizeEnd"]) => void;
}

/**
 * A Vue component that renders an `prosekit-resizable-root` custom element.
 *
 * @public
 */
export const ResizableRoot: DefineSetupFnComponent<
  ResizableRootProps & HTMLAttributes
> = /* @__PURE__ */ defineComponent<ResizableRootProps & HTMLAttributes>(
  (props, { slots }) => {
    registerResizableRootElement();
    const _eventHandlers: Record<string, Function> = {};

    const _ref = (element: HTMLElement | null | undefined) => {
      if (!element) {
        return;
      }

      const abortController = new AbortController();
      const abortSignal = abortController.signal;

      element.addEventListener(
        "resizeEnd",
        (event) => {
          _eventHandlers["onResizeEnd"]?.(event);
        },
        { signal: abortSignal },
      );
      element.addEventListener(
        "resizeStart",
        (event) => {
          _eventHandlers["onResizeStart"]?.(event);
        },
        { signal: abortSignal },
      );

      return () => {
        abortController.abort();
      };
    };

    return () => {
      const _props: Record<string, unknown> = {};
      for (const [key, value] of Object.entries(props)) {
        switch (key) {
          case "aspectRatio":
          case "height":
          case "width":
            _props["." + key] = value;
            break;
          case "onResizeEnd":
          case "onResizeStart":
            _eventHandlers[key] = value as Function;
            break;
          default:
            _props[key] = value;
        }
      }

      _props["ref"] = _ref;
      return h("prosekit-resizable-root", _props, slots.default?.());
    };
  },
  {
    props: {
      aspectRatio: {
        default: ResizableRootPropsDeclaration.aspectRatio.default,
      },
      height: { default: ResizableRootPropsDeclaration.height.default },
      width: { default: ResizableRootPropsDeclaration.width.default },
      onResizeEnd: { type: Function },
      onResizeStart: { type: Function },
    } as Record<string, unknown>,
  },
);

export type { ResizableRootEvents };
export { ResizeEndEvent, ResizeStartEvent } from "@prosekit/web/resizable";
