import { describe, expect, it } from 'vitest'

import { renderHTML } from '../src/react/examples/full'

describe('sample content full', () => {
  it('should render the sample content', () => {
    expect(typeof document).not.toBe('undefined')
    const html = renderHTML(document)
    expect(html).toMatchInlineSnapshot(`
      "<div><h1>The editor that thinks like you</h1><p>Every keystroke flows naturally. Every feature appears exactly when you need it. This is <strong>writing without barriers</strong>.</p><h2>Text that shines.</h2><p>Make your words <strong>bold</strong>, <em>italic</em>, <u>underlined</u>, or <s>crossed out</s>. Add <code>inline code</code> that stands out. Create <a href="https://prosekit.dev">links</a> that connect.</p><p>Select any text to format it. Type <code>@</code> to mention <span data-id="39" data-mention="user">@someone</span> or <code>#</code> for <span data-id="1" data-mention="tag">#topics</span>. Press <code>/</code> and discover what's possible.</p><h2>Lists that organize.</h2><div class="prosemirror-flat-list" data-list-kind="bullet"><div class="list-marker list-marker-click-target" contenteditable="false"></div><div class="list-content"><p>Bullet points that guide thoughts</p></div></div><div class="prosemirror-flat-list" data-list-kind="bullet" data-list-collapsable=""><div class="list-marker list-marker-click-target" contenteditable="false"></div><div class="list-content"><p>Nested lists for complex ideas</p><div class="prosemirror-flat-list" data-list-kind="bullet"><div class="list-marker list-marker-click-target" contenteditable="false"></div><div class="list-content"><p>Sub-points flow naturally</p></div></div></div></div><div class="prosemirror-flat-list" data-list-kind="bullet" data-list-collapsable=""><div class="list-marker list-marker-click-target" contenteditable="false"></div><div class="list-content"><p>Tasks that focus</p><div class="prosemirror-flat-list" data-list-kind="task" data-list-checked=""><div class="list-marker list-marker-click-target" contenteditable="false"><label><input type="checkbox" checked=""></label></div><div class="list-content"><p>Done feels good</p></div></div><div class="prosemirror-flat-list" data-list-kind="task"><div class="list-marker list-marker-click-target" contenteditable="false"><label><input type="checkbox"></label></div><div class="list-content"><p>Todo drives action</p></div></div></div></div><div class="prosemirror-flat-list" data-list-kind="ordered"><div class="list-marker list-marker-click-target" contenteditable="false"></div><div class="list-content"><p>Numbered steps</p></div></div><div class="prosemirror-flat-list" data-list-kind="ordered"><div class="list-marker list-marker-click-target" contenteditable="false"></div><div class="list-content"><p>Sequential thinking</p></div></div><div class="prosemirror-flat-list" data-list-kind="ordered"><div class="list-marker list-marker-click-target" contenteditable="false"></div><div class="list-content"><p>Clear progress</p></div></div><h2>Code that inspires.</h2><pre data-language="javascript"><code class="language-javascript">// Code that reads like poetry
      const magic = createEditor()
      magic.transform(thoughts)
      </code></pre><h2>Images that captivate.</h2><img src="https://static.photos/season/320x240/107"><p>Drag the handle in the bottom right corner to resize.</p><h2>Tables that structure.</h2><table><tbody><tr><td><p><strong>Feature</strong></p></td><td><p><strong>How to use</strong></p></td><td><p><strong>Result</strong></p></td></tr><tr><td><p>Format text</p></td><td><p>Select and choose</p></td><td><p>Perfect styling</p></td></tr><tr><td><p>Add mentions</p></td><td><p>Type @ and name</p></td><td><p>Connected ideas</p></td></tr><tr><td><p>Insert anything</p></td><td><p>Press / for menu</p></td><td><p>Endless possibilities</p></td></tr></tbody></table><h2>Math that renders.</h2><p>Inline math like <span class="prosekit-math-inline"><code>e^{i\\pi} + 1 = 0</code></span> appears within text. Type <code>$...$</code> to insert an inline equation.</p><div class="prosekit-math-block"><pre><code>\\int_{-\\infty}^{\\infty} e^{-x^2} \\, dx = \\sqrt{\\pi}</code></pre></div><p>Type <code>$$</code> in a new line and press Enter to create a block equation.</p><h2>Quotes that inspire.</h2><blockquote><p>"This is not just an editor. This is how writing should feel."</p></blockquote><div class="prosekit-horizontal-rule"><hr></div><p>Start typing. Everything else just flows.</p></div>"
    `)
  })
})
