<!-- This file is auto-generated by the "@aria-ui/cli" tool. Do not edit this file directly. -->

<script lang="js">
  import { registerPopoverTriggerElement } from '@prosekit/web/popover'
  registerPopoverTriggerElement()

  let { closeDelay: p0, delay: p1, disabled: p2, openOnHover: p3, onOpenChange: p4, children = undefined, ...restProps } = $props()

  const attachment = (element) => {
    if (!element) return

    const abortController = new AbortController()
    const abortSignal = abortController.signal

    if (p0 !== undefined) { element.closeDelay = p0 }

    if (p1 !== undefined) { element.delay = p1 }

    if (p2 !== undefined) { element.disabled = p2 }

    if (p3 !== undefined) { element.openOnHover = p3 }

    if (p4 !== undefined) { element.addEventListener('openChange', p4, { signal: abortSignal }) }

    return () => {
      abortController.abort()
    }
  }
</script>

<prosekit-popover-trigger {...restProps} {@attach attachment}>{@render children?.()}</prosekit-popover-trigger>
