<script lang="ts">
  // This file is auto-generated by "@aria-ui/cli". Do not edit this file directly.
  import { registerPopoverTriggerElement } from '@prosekit/web/popover'
  import type { PopoverTriggerElement } from '@prosekit/web/popover'
  registerPopoverTriggerElement()

  let { closeDelay: p0, delay: p1, disabled: p2, openOnHover: p3, onOpenChange: e0, children = undefined, ...restProps } = $props()
  let element: PopoverTriggerElement | undefined
  const handlers: EventListener[] = []

  $effect(() => {
    if (!element) return

    Object.assign(element, { closeDelay: p0, delay: p1, disabled: p2, openOnHover: p3 })

    handlers.length = 0
    handlers.push(e0)
  })

  $effect(() => {
    if (!element) return

    const ac = new AbortController()
    for (const [index, eventName] of ["openChange"].entries()) {
      element.addEventListener(eventName, (event) => handlers[index]?.(event), { signal: ac.signal })
    }
    return () => ac.abort()
  })
</script>

<prosekit-popover-trigger {...restProps} bind:this={element}>{@render children?.()}</prosekit-popover-trigger>
