// This file is auto-generated by "@aria-ui/cli". Do not edit this file directly.

import type { PopoverPopupElement } from '@prosekit/web/popover';
import type { Component, Snippet } from 'svelte';
import type { HTMLAttributes } from 'svelte/elements';

import PopoverPopupComponent from './popover-popup.gen.svelte';

/**
 * Props for the {@link PopoverPopup} Svelte component.
 *
 * @public
 */
export interface PopoverPopupProps {
  children?: Snippet;
}

/**
 * A Svelte component that renders an `prosekit-popover-popup` custom element.
 *
 * @public
 */
export const PopoverPopup: Component<PopoverPopupProps & HTMLAttributes<PopoverPopupElement>> = PopoverPopupComponent as Component<PopoverPopupProps & HTMLAttributes<PopoverPopupElement>>;
