<!-- This file is auto-generated by the "@aria-ui/cli" tool. Do not edit this file directly. -->

<script lang="ts">
  import { registerPopoverRootElement } from '@prosekit/web/popover'
  import type { PopoverRootElement } from '@prosekit/web/popover'
  registerPopoverRootElement()

  let { defaultOpen: p0, disabled: p1, modal: p2, open: p3, onOpenChange: e0, children = undefined, ...restProps } = $props()
  let element: PopoverRootElement | undefined
  const handlers: EventListener[] = []

  $effect(() => {
    if (!element) return

    Object.assign(element, { defaultOpen: p0, disabled: p1, modal: p2, open: p3 })

    handlers.length = 0
    handlers.push(e0)
  })

  $effect(() => {
    if (!element) return

    const ac = new AbortController()
    for (const [index, eventName] of ["openChange"].entries()) {
      element.addEventListener(eventName, (event) => handlers[index]?.(event), { signal: ac.signal })
    }
    return () => ac.abort()
  })
</script>

<prosekit-popover-root {...restProps} bind:this={element}>{@render children?.()}</prosekit-popover-root>
