name: "commitlint"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  lint-pr-title:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Install commitlint
        run: npm install -g @commitlint/config-conventional@19 @commitlint/cli@19

      - name: Configure commitlint
        run: |
          echo "export default { extends: ['@commitlint/config-conventional'] };" > commitlint.config.mjs

      - name: Check PR Title
        run: |
          echo The Title of your PR is "$PR_TITLE"
          echo "$PR_TITLE" | commitlint --verbose
        env:
          # Use an intermediate environment variable to avoid script injection attacks
          # https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions
          PR_TITLE: ${{ github.event.pull_request.title }}
