# https://autofix.ci/setup

name: autofix.ci

on:
  pull_request:

permissions:
  contents: read

jobs:
  fix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - uses: ./.github/actions/setup

      - name: Fix
        run: pnpm run fix

      - uses: autofix-ci/action@c5b2d67aa2274e7b5a18224e8171550871fc7e4a # v1.3.4
