name: hide-bot-comment

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  hide-bot-comment:
    runs-on: ubuntu-latest

    steps:
      - id: hide-comment
        if: >-
          github.event.pull_request.head.repo.full_name == github.repository &&
          github.event.pull_request.user.login != 'dependabot[bot]'
        uses: int128/hide-comment-action@95dd081d51b1cae55a0d089db892cea5835e4e15 # v1.67.0
        with:
          authors: |
            github-actions
            changeset-bot
            coderabbitai
            pkg-pr-new
