name: hide-bot-comment

on:
  pull_request:

jobs:
  hide-bot-comment:
    runs-on: ubuntu-latest

    steps:
      - id: hide-comment
        if: github.event.pull_request.head.repo.full_name == github.repository
        uses: int128/hide-comment-action@42badf94b3efd95bf2138bd9c74da19203e83f40 # v1.55.0
        with:
          authors: |
            github-actions
            changeset-bot
            coderabbitai
            pkg-pr-new
