name: hide-bot-comment

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  hide-bot-comment:
    runs-on: ubuntu-latest

    steps:
      - id: hide-comment
        if: >-
          github.event.pull_request.head.repo.full_name == github.repository &&
          github.event.pull_request.user.login != 'dependabot[bot]'
        uses: int128/hide-comment-action@d77998fe0fbeb1cafd88f2cc4549c9ffd997656b # v1.71.0
        with:
          authors: |
            github-actions
            changeset-bot
            coderabbitai
            pkg-pr-new
